### ISSUE TITLE
Explain `keys` purpose in yaml file clearly in documentation

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1003]

**Comment by Didayolo** [comment]
Indeed, this is very important and not clearly explicited in the wiki.

I guess it should be explained in this page :
https://github.com/codalab/codabench/wiki/Yaml-Structure

I don't know if there is also a page about scoring program.

Basically, the keys need to match the keys of the `scores.txt` file output by the scoring program.
