### ISSUE TITLE
Terms and conditions

### ISSUE THREAD

**Issue by madclam** [codalab/codabench#1004]
The terms and conditions are visible by the participants only a the time of registration, when the accept them. They should be available for review from the website pages as well, for later consultation.

### TODO

- [x] Automatically add a "Terms" page in the main tab. It should be pointing to the actual terms - editing the terms through the editor should edit this page.

**Comment by Didayolo** [comment]
@acletournel Isabelle is refering to the terms of a given competition, usually given by the file `terms.html`.

It is good that the page is visible during registration, but it should be added as one independant page in the main tab.
