### ISSUE TITLE
Boldface not working on competition pages

### ISSUE THREAD

**Issue by madclam** [codalab/codabench#1005]
**This is bold**

does not result in boldface fonts.

**Comment by Didayolo** [comment]
@madclam 

Do you have a specific example?

You can see in this competition main page that "classification tasks" is in bold:
https://www.codabench.org/competitions/870/

Your problem may be that the markdown is not interpreted because it is mixed with HTML:
- #879

**Comment by Didayolo** [comment]
I close this issue to keep track of this in the new issue
