### ISSUE TITLE
"Show detailed results" only show the html from 1 task

### ISSUE THREAD

**Issue by ktgiahieu** [codalab/codabench#1009]
In our [competition](https://www.codabench.org/competitions/1084/?secret_key=7b1088c2-9b96-41b4-9bf3-3565ffcea796), clicking on **"Show detailed results"** button only shows the html results from 1 task (AI-Author) instead of 2 (AI-Author and AI-reviewer):
<img width="1166" alt="image" src="https://github.com/codalab/codabench/assets/42331617/abb11964-4e25-4b73-bb9e-96e723b5baec">

**Comment by ihsaan-ullah** [comment]
Solved by: #967. will be merged soon

**Comment by Didayolo** [comment]
I close the issue as it is tracked by the PR #967
