### ISSUE TITLE
Bug - Login possible even without account activation

### ISSUE THREAD

**Issue by dtuantran** [codalab/codabench#1017]
After creating an account, click on "[Forgot your password ?](https://www.codabench.org/accounts/password_reset/)"
Then click on "Reset password" and we can log in without activating the account.

**Comment by dtuantran** [comment]
![image](https://github.com/codalab/codabench/assets/7440668/15d169f8-60fe-4fa2-81e0-dd5cebf98b02)
The user can see all benchmarks even private one

**Comment by dtuantran** [comment]
This only works with "email" authentication, not with "username".

**Comment by ihsaan-ullah** [comment]
When a new account is created:

- you can login with `email` and `password` without verifying your account
- you cannot login with `username` and `password` without verifying your account
- after account verification, you can use both `email` and `username` to login

**Comment by Didayolo** [comment]
Tracking in the PR.
