### ISSUE TITLE
Participants joining emails still sent to removed admins

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1019]
When you add an admin and then remove the admin, that person still receives emails about participants joining the competition

**Comment by ihsaan-ullah** [comment]
I think i reported this wrong. I am receiving the emails even I am removed because the emails are sent to a group email where I am added. 

If someone can verify this, we can close this issue

**Comment by Didayolo** [comment]
Linked to #1006

**Comment by ihsaan-ullah** [comment]
looks like wrongly reported issue
