### ISSUE TITLE
Access fact sheet in scoring_program

### ISSUE THREAD

**Issue by ktgiahieu** [codalab/codabench#1026]
Hi,

May I ask if there is a way to access the value in Fact Sheet during the scoring program? I am trying to add the Fact Sheet to the output HTML files so that the contestants know which HTML associates with which submission.

**Comment by ihsaan-ullah** [comment]
The scoring program cannot access factsheet but in the editor of the competition you can check `show on leaderboard` and then the leaderboard row will show the factsheet answer

Check this competition to get an idea:
https://www.codabench.org/competitions/674/#/results-tab

**Comment by Didayolo** [comment]
Indeed, the scoring program can't access the fact sheets.

You can either:

- Display the fact sheets in the leaderboard as suggested by Ihsan
- Add a fact sheets file submitted by the participants inside their submissions (for instance a `fact_sheets.yaml`) that will be read by the scoring program

Feel free to re-open the issue to pursue the discussion
