### ISSUE TITLE
Problem with phases dates (v1 bundle?)

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1027]
When the first phase ending date is exactly the same as the second phase starting, we got the following error:

<img width="889" alt="Capture d’écran 2023-07-21 à 18 25 47" src="https://github.com/codalab/codabench/assets/11784999/634ea2f7-a06d-4123-9fa7-6c87dae4f1b3">

But I think this is what we got when uploading v1 bundle, with only starting dates (no end dates). Note sure if we have the same problem with v2 bundles. The upload works, but then when we edit a phase, even without changing the date, the problem appears.

**Comment by ihsaan-ullah** [comment]
@Didayolo, The following is observed after testing

### V2 Bundle
1. If phase is NOT the last phase, then uploading such bundle gives error that it should have and end date
2. If phase is the last date, without end date their is not error
3. If you have two phases, phase 1 end date and phase 2 start date can be same (bundle uploads)

Point 3 leads to the error mentioned in this issue

### V1 Bundle
1. If a phase has no end date and it is not the last phase, the next phase start date is used as the end date for this phase

Point 1 leads to the error mentioned in this issue


### Possible solutions:
1. V1 bundle: if a phase has no end date, use the next phase (start date - 1) as its end date
2. V2 bundle: check if a phase start date and previous phase end date is same, then give error

**Comment by Didayolo** [comment]
I close this issue to keep track in the PR.
