### ISSUE TITLE
[Feature] Add "Cancel" button in Edit Profile

### ISSUE THREAD

**Issue by ktgiahieu** [codalab/codabench#1035]
Hi,

In the "Edit Profile" page:
<img width="614" alt="image" src="https://github.com/codalab/codabench/assets/42331617/56dbeb5a-e952-4ab7-b08f-d228a01e62c1">

Can we add a "Cancel" button here (next to "Submit") that redirects to the homepage? Thank you
<img width="1167" alt="image" src="https://github.com/codalab/codabench/assets/42331617/42e67010-0947-4603-b522-aec393e25756">

**Comment by ihsaan-ullah** [comment]
I think `Cancel` button is not needed because it is not a modal dialog but a full page. Normally people add cancel to dialogs/modals when they appear on top of the page hiding the content behind.
