### ISSUE TITLE
[Feature] After "Log In" or "Sign Up" from the competition's page, redirect back to the competition

### ISSUE THREAD

**Issue by ktgiahieu** [codalab/codabench#1036]
Hi,

After finishing the "Log In" or "Sign Up" step from the competition's page:
<img width="1004" alt="image" src="https://github.com/codalab/codabench/assets/42331617/9cf576a3-691f-4fe3-8b38-e826f5aa853d">

I got redirected to the homepage:
<img width="1295" alt="image" src="https://github.com/codalab/codabench/assets/42331617/8f556038-3194-473f-a338-ddade3a3b10e">

Can we make it redirects to the competition after logging in? Thanks

**Comment by ihsaan-ullah** [comment]
After login from here, you are always redirected to competition page.

**Comment by ihsaan-ullah** [comment]
login will not take you to the competition page if you haven't clicked it from the submission tab. If you go to login page the normal way i.e from the top manu, then you will be redirected to home page

**Comment by Didayolo** [comment]
Indeed, if you use the "Log In" link from the submission tab, you get redirected to the competition.

@ihsaan-ullah I don't know if the Sign Up have redirection with the `?next` GET variable? Or this is only for login?

**Comment by ihsaan-ullah** [comment]
> Indeed, if you use the "Log In" link from the submission tab, you get redirected to the competition.
> 
> @ihsaan-ullah I don't know if the Sign Up have redirection with the `?next` GET variable? Or this is only for login?

it is only for login. Signup is multiple step process and the signup page is opened in next tab so it looks ok to me to not have `next` in signup

**Comment by Didayolo** [comment]
OK, I guess we can let everything as it is right now.
