### ISSUE TITLE
Force submissions to leaderboard

### ISSUE THREAD

**Issue by madclam** [codalab/codabench#1038]
In spite of ndcatng that the last submission should be forced to the leaderboard:
<img width="1007" alt="Screen Shot 2023-07-26 at 6 24 24 PM" src="https://github.com/codalab/codabench/assets/7594063/0abcba52-74ed-4762-a614-450eb677d38b">

It is possible for PARITICIPANTS to OVERWRITE this decision and submit whatever submission they want
<img width="1016" alt="Screen Shot 2023-07-26 at 6 23 16 PM" src="https://github.com/codalab/codabench/assets/7594063/5b03fac2-06b8-471b-b4a6-c786178ab3ba">
<img width="1004" alt="Screen Shot 2023-07-26 at 6 23 47 PM" src="https://github.com/codalab/codabench/assets/7594063/e7b94780-d84f-45e0-a34d-c6ba8be186e1">

This is not the desired behavior. In challenges, it is important to AVOID that participants can hide submissions and make such changes because then the leaderboard jumps around and people are not stimulated to make submssions by seeing the submissions of others.

**Comment by madclam** [comment]
This is the example competition: https://www.codabench.org/competitions/1145/

**Comment by Didayolo** [comment]
Nice catch, thank you for reporting.

**Comment by Didayolo** [comment]
@madclam Actually, this feature is working. It is just that, when you are admin of the platform, you can outpass this constraint.
