### ISSUE TITLE
You can see only your own detailed results

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1043]
When you click on the the detailed results from the leaderboard, you can the page only if you are the author of the submission, except if you are an admin of the platform.

<img width="230" alt="Capture d’écran 2023-07-29 à 01 46 21" src="https://github.com/codalab/codabench/assets/11784999/b425bfb6-a1a5-4974-b45e-c39fd21a8200">

<img width="461" alt="Capture d’écran 2023-07-29 à 01 46 25" src="https://github.com/codalab/codabench/assets/11784999/1ca4918c-35a2-46b4-8d17-39b848b9d2f8">

**Comment by Didayolo** [comment]
@ihsaan-ullah Are you organizer of this competition? I think being admin or organizer outpasses this limitation.

**Comment by ihsaan-ullah** [comment]
> @ihsaan-ullah Are you organizer of this competition? I think being admin or organizer outpasses this limitation.

yes I am an organizer. I will test this with another account
