### ISSUE TITLE
Meta Info in competition page

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1050]
When you share a competition link e.g. in skype, you can only see the following image.
<img width="314" alt="Screenshot 2023-08-02 at 6 08 41 PM" src="https://github.com/codalab/codabench/assets/13259262/da0ae2d3-f46b-4044-9e53-1eab63bd9162">

This can be improved to add a title (Competition name), description (competition description), URL (competition URL) and competition logo. 

An example page from hugging face with all this info is below:
<img width="316" alt="Screenshot 2023-08-02 at 6 10 56 PM" src="https://github.com/codalab/codabench/assets/13259262/f5bae077-6a1b-4782-95c9-017168c956d1">

Another example: when you share codabench github repo:
<img width="311" alt="Screenshot 2023-08-02 at 6 14 15 PM" src="https://github.com/codalab/codabench/assets/13259262/7a13c36c-1b00-4087-89cd-876883f9aa28">

**Comment by Didayolo** [comment]
Possible image here

![codabench_preview](https://github.com/codalab/codabench/assets/11784999/7315b195-4e26-4269-9fca-5c4390f73977)

**Comment by ihsaan-ullah** [comment]
shifted to dicussion #1334
