### ISSUE TITLE
n/a scores on leaderboard if Submission Rule is Force Last

### ISSUE THREAD

**Issue by ktgiahieu** [codalab/codabench#1055]
Hi,

I noticed that if the competition has 2 tasks, and the Submission Rule is Force Last:
- If you submit a solution to both tasks and wait for it to finish: everything works fine
- If you submit a solution to both tasks but then submit another one before the first submission finish: there will be a n/a score for the task that finish after (although the submission's ingestion and scoring program run successfully).

Here is our competition: https://www.codabench.org/competitions/1145/

An example of the error is submission ID: 15757, which is submitted only 10min after submission ID: 15736. (so the first submission is not finished when the second submission is submitted).

An example of a successful submission is submission ID 15796, which is submitted 2 hrs after submission ID 15793 (so the first submission is finished already).

<img width="1164" alt="image" src="https://github.com/codalab/codabench/assets/42331617/28a756a8-1248-4eb8-8444-a9609a769e54">

**Comment by ktgiahieu** [comment]
Hi guys,

Thank you for your latest update of the competition's UI and submission count. It looks great.

May I ask if we have any plans for this "n/a scores" bug?

**Comment by Didayolo** [comment]
I close this issue to merge and keep track of it here: #1540.
