### ISSUE TITLE
Score in submission panel

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1075]
@Didayolo what do you think if we change this `Score` to primary column too?

<img width="426" alt="Screenshot 2023-08-14 at 3 07 36 PM" src="https://github.com/codalab/codabench/assets/13259262/e359503e-d59d-4460-8459-607d536c7e1d">

**Comment by Didayolo** [comment]
Yes, I think that would make more sense. The primary column of the first task.

**Comment by ihsaan-ullah** [comment]
Closing this because a submission may not have a leaderboard in the submission panel. If there is no leaderboard, we cannot have its primary column.

More problems: we can have multiple leaderboards.

**Comment by Didayolo** [comment]
OK, anyway this score here is just an indicator.

**Comment by Didayolo** [comment]
> Closing this because a submission may not have a leaderboard in the submission panel. If there is no leaderboard, we cannot have its primary column.

About this, what do you mean? How can we have no leaderboard?
