### ISSUE TITLE
Remove from leaderboard

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1076]
When i press this `tick` button to remove a submission from leaderboard.
<img width="544" alt="Screenshot 2023-08-14 at 3 15 40 PM" src="https://github.com/codalab/codabench/assets/13259262/f59246ec-f86d-4972-9ae0-72d194a81ff7">

I get this error:
<img width="766" alt="Screenshot 2023-08-14 at 3 15 53 PM" src="https://github.com/codalab/codabench/assets/13259262/407fea1f-7a8e-4987-92fe-00ccbf293773">

I am admin/organizer of the competition

Competition: https://www.codabench.org/competitions/1152

**Comment by Didayolo** [comment]
I think it is the excepted behavior

**Comment by ihsaan-ullah** [comment]
Not a bug
