### ISSUE TITLE
RabbitMQ and Flower links not working in server status page

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1105]
As an admin, RabbitMQ and Flower links are not working in server status page:

<img width="1209" alt="Capture d’écran 2023-08-22 à 17 31 32" src="https://github.com/codalab/codabench/assets/11784999/b71e261f-0d03-4634-950d-b524a58fbcfa">

More info here: https://github.com/codalab/codabench/wiki/Administrator-procedures

**Comment by Didayolo** [comment]
In the production environment, it works only when using `http` instead of `https`.

**Comment by ihsaan-ullah** [comment]
> In the production environment, it works only when using `http` instead of `https`.

Assuming on codabench-test it will also work with http. Creating a new PR with http

**Comment by Didayolo** [comment]
Is this fixed?

**Comment by ihsaan-ullah** [comment]
> Is this fixed?

I think yes with https://github.com/codalab/codabench/pull/1153

**Comment by Didayolo** [comment]
I just deployed the last changes to the test server and it seems to not be working

**Comment by Didayolo** [comment]
Deployed on prod, it works

**Comment by ihsaan-ullah** [comment]
@Didayolo this can be closed
