### ISSUE TITLE
competition dump with files

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1108]
when you create a dump (by default it is created with files) but you can still see the keys in the yaml file.

<img width="544" alt="Screenshot 2023-08-23 at 1 42 52 PM" src="https://github.com/codalab/codabench/assets/13259262/e4d23177-663f-47b2-a229-52288f1e10cc">

**Comment by Didayolo** [comment]
I am a bit confused because I thought we had the dump with files but not the dump with keys. See:

- #880 

I think only one of the two options is working right now. We should test and merge the two issues into one.

**Comment by ihsaan-ullah** [comment]
I just tested and the key if for a task. So this issue can be closed

**Comment by Didayolo** [comment]
But even if it is for a task, you should not have keys if you create a dump with files.

**Comment by Didayolo** [comment]
I confirm that when you dump using files and then re-upload the bundle, the tasks are linked to the previous tasks. No new tasks are created (see screenshot).

<img width="1159" alt="Capture d’écran 2023-08-24 à 13 51 53" src="https://github.com/codalab/codabench/assets/11784999/a8a63e2f-085d-474a-903a-42f6e0118504">


I think we would like that:
- For dumps with keys, we link to the previous tasks,
- For dump with files, we create new tasks from scratch using the files.

**Comment by ihsaan-ullah** [comment]
When you create a dump with files, you can see a key for each task in YAML file. If you remove that key and upload the bundle, do you still see the new competition linked to already existing tasks?

**Comment by ihsaan-ullah** [comment]
This issue needs some discussion.

1. why we have key in tasks when we create dump.
2. If an already existing task can be linked through a key then why do we have keys for the datasets (when creating dumps with keys)
3. What should be done for both cases: with keys, with files

**Comment by Didayolo** [comment]
- For the files case, we want the bundle to be **self-contained**. Therefore, we should not store the tasks keys in this case,
- For the keys case, I think it is OK to keep both tasks keys and programs/data keys, but we should do some testing to so how it behaves.

**Comment by ihsaan-ullah** [comment]
# Tests

### Download Dump with files `OK`
- Task in yaml has keys
- Uploading this bundle -> uses already existing tasks

### Download Dump with files `OK`
- Task in yaml has keys 
- Delete the tasks 
- Uploading this bundle -> gives error

### Download Dump with files `OK`
- Task in yaml has keys -> remove keys
- Uploading this bundle -> this competition uses new tasks

### Download Dump with keys `OK`
- Task in yaml has keys
- Dataset in yaml has keys
- Uploading this bundle ->  uses already existing tasks

### Download Dump with keys `OK`
- Task in yaml has keys -> remove task keys
- Dataset in yaml has keys
- Uploading this bundle ->  creates new tasks

### Download Dump with keys `OK`
- Task in yaml has keys 
- Dataset in yaml has keys -> remove dataset keys
- Uploading this bundle ->  uses already existing tasks


The only problem I see is that when you create dump with files, for tasks keys should not be there
