### ISSUE TITLE
Clean Codabench Test and Prod

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1109]
There are untracked/unused migrations in the test and prod server. Cleaning both servers are important to make sure there are no inconsistencies or possible crashes in the future

- [x] Clean Test server
Already cleaned together with Tuan

- [x] Clean production server

**Comment by ihsaan-ullah** [comment]
I did the following:

1. deleted all the branches except develop
2. deleted all uncommitted files

**Comment by bbearce** [comment]
And migrations? What did you do for those? Were there "merge" migrations that are not apart of the repo that you cleaned up?

**Comment by ihsaan-ullah** [comment]
> And migrations? What did you do for those? Were there "merge" migrations that are not apart of the repo that you cleaned up?

I just deleted the unused migrations. If some are not part of the code, they should not be there right?
