### ISSUE TITLE
Display name already exists - bug with editing profile

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1115]
Steps to reproduce:

- Create an account
- Go to edit profile
- Add a profile picture and try to save
- You should get this empty error message (not cool that it is empty by the way):

<img width="1190" alt="262934499-3a39e941-a69d-42db-8577-f22815c03e53" src="https://github.com/codalab/codabench/assets/11784999/a220ecac-be7c-4451-8d39-f689bb4ad2be">

Django error logs:

```python
[...]
codabench-django-1       |     return executor(sql, params, many, context)
codabench-django-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
codabench-django-1       |     return self.cursor.execute(sql, params)
codabench-django-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
codabench-django-1       |     raise dj_exc_value.with_traceback(traceback) from exc_value
codabench-django-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
codabench-django-1       |     return self.cursor.execute(sql, params)
codabench-django-1       | django.db.utils.IntegrityError: duplicate key value violates unique constraint "profiles_user_display_name_key"
codabench-django-1       | DETAIL:  Key (display_name)=() already exists.
```

The error log suggests that there is a unique constraint on the `display_name` field in the database schema, and the code is attempting to insert or update a record that would cause this constraint to be violated. Specifically, the error suggests that a record with an empty display name (`display_name=()`) already exists, and another record with an empty display name is being attempted to be saved.

Indeed, if you fill in the display name then you can save without problems.

Why is the unique constraint that is violated? Updating the display name, even with an empty field, should not duplicate the entry. Just update it, or do nothing.

I confirm that the problem happens anytime you try to save an empty "Display name". As it if was a not-null constraint instead of a unique constraint.

**Comment by ihsaan-ullah** [comment]
Why do we have display name? It is just used in the organization and never used anywhere else. I think we can remove it

**Comment by Didayolo** [comment]
It is also used as the name displayed on the leaderboard:

<img width="494" alt="Capture d’écran 2023-08-30 à 20 24 42" src="https://github.com/codalab/codabench/assets/11784999/f54256f1-c722-4ea6-bf05-e0a5097b4cb6">

<img width="691" alt="Capture d’écran 2023-08-30 à 20 24 52" src="https://github.com/codalab/codabench/assets/11784999/4d7df9aa-320d-4ee2-980f-eb6960a6ac73">

So this is useful, because it is very common that users want to change their usernames. This way they keep their identifier but can change the display name if needed.
