### ISSUE TITLE
Remove submission from leaderboad

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1125]
# Todos:

- [x] fix empty error when admin is removing someone else's submission

***

I want to remove a submission for leaderboard. There are two problems:

1. Whan an admin wants to do that (for his own submission), it says this: 
<img width="657" alt="Screenshot 2023-08-28 at 10 27 32 PM" src="https://github.com/codalab/codabench/assets/13259262/acefbde8-ec91-43cf-ba59-ac67c942008e">

2. When an admin wants to do it for someone else's submission, this is shown
<img width="627" alt="Screenshot 2023-08-28 at 8 27 50 PM" src="https://github.com/codalab/codabench/assets/13259262/c265985e-76fa-44f9-8b8b-149ce66088bd">

**Comment by Didayolo** [comment]
I think it is not a big problem if admins can't remove a submission from the leaderboard if it is not allowed by the setting of the competition. Of course the blank error message is problematic.

**Comment by ihsaan-ullah** [comment]
> I think it is not a big problem if admins can't remove a submission from the leaderboard if it is not allowed by the setting of the competition. 

Where can I set this in competition settings? I think once a submission is added to leaderboard, you cannot remove it.
