### ISSUE TITLE
Allowed submission per day hack

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1128]
You can bypass the restriction of allowed submissions per day or per person by deleting your submissions.

**Comment by Didayolo** [comment]
Using the resources interface? Is that allowed for non-admins?

**Comment by ihsaan-ullah** [comment]
> Using the resources interface? Is that allowed for non-admins?

Yes, if you are admin, you can delete a submission

**Comment by ihsaan-ullah** [comment]
Seems not a problem now as only admins can delete submissions.
