### ISSUE TITLE
Custom Docker Image for submission

### ISSUE THREAD

**Issue by bbearce** [codalab/codabench#1149]
This is the beginning of a conversation around making it possible for participants to privide their own docker image for submssions.

Design ideas:
![image](https://github.com/codalab/codabench/assets/7649007/715190c8-f28e-4139-95d4-6c04808389a1)
![image](https://github.com/codalab/codabench/assets/7649007/928fc982-9565-4626-861b-ec204463fcb2)

Possible concerns:  
* What can someone attempt to do with a docker image meant to do malicious activity?  
* Should we use podman instead?  
* Should we automatically pull from dockerhub?  
  - Can we support custom or private repos so docker images aren't public (if we want private images)?  
  - If so how will participants access? We need a way for them to authenticate and upload their images somewhere sequestered.

**Comment by Didayolo** [comment]
Just a note here about this: using the same docker image for all submissions in a given benchmark is a very good feature because it avoids lot of problems, and make the evaluation and scoring fair and equal for all submissions.
