### ISSUE TITLE
Can't edit shared task

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1156]
When you share a task with another users, they are not able to edit the task.

I don't know if they are able to remove it.

<img width="1125" alt="Capture d’écran 2023-09-13 à 12 19 54" src="https://github.com/codalab/codabench/assets/11784999/9d304728-dc03-40a8-9d3f-856926e94ecf">

<img width="1156" alt="Capture d’écran 2023-09-13 à 12 17 46" src="https://github.com/codalab/codabench/assets/11784999/4324e152-c023-4dcf-a9c4-2c0253f8a26c">

# Todo:

- [x] show edit/delete buttons to owner only

**Comment by Didayolo** [comment]
Sorry I did not save a screenshot, but it happens like this: the button is visible, you access to the interface, but when you try to save the changes, you get a red box error message stating something like "Error in saving the task".

**Comment by ihsaan-ullah** [comment]
What should be done in this case. I think only owner should see edit/delete buttons. If this task is shared with someone, that user can just use it. What do you think?

**Comment by Didayolo** [comment]
Hey, I just edited my previous comment

**Comment by Didayolo** [comment]
Indeed, at least if the buttons are hidden then it is a feature and not a bug.
