### ISSUE TITLE
Re-run submissions without creating new submissions

### ISSUE THREAD

**Issue by dtuantran** [codalab/codabench#1162]
Before re-running my submissions from Iris competition, I had 31 submissions. After re-running the submissions, it incremented to 62 submissions.

![image](https://github.com/codalab/codabench/assets/7440668/bf6d3868-2f43-45d6-a93e-1a5bdc349ca9)

I believe that it created new 31 submissions from the old ones. Then, everytime we re-run all submissions, Codabench will double the submissions number.

**Comment by ihsaan-ullah** [comment]
This is exactly what is happening on rerun
https://github.com/codalab/codabench/blob/7b1742a439d49e8f28bbe631a5e2f649a80cfe1e/src/apps/competitions/models.py#L508

**Comment by Didayolo** [comment]
I close this issue to keep track of it only in #1182.
