### ISSUE TITLE
Add loading animation to public benchmarks page

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1173]
The page is quite long to load, and we have the following display:

<img width="1217" alt="Capture d’écran 2023-09-22 à 18 00 40" src="https://github.com/codalab/codabench/assets/11784999/a5187f36-8565-4514-b417-ccecd6cd23be">

These buttons were hidden in the past but it was buggy so we put them back. The best would be to have a loading animation while it is loading, and then everything appears.

- [x] Add loading animation (#1285)

**Comment by lbeziaud** [comment]
@Didayolo it might be interesting to have smaller and/or compressed logos on this page. Loading for e.g. a [beautiful 1.41 MB logo](https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-public/logos/2023-07-06-1688648800/b3ccca9ea50f/logo.png) to display a 60x60 px thumbnail is what makes the page slow on my side :)

**Comment by Didayolo** [comment]
@lbeziaud Very good remark indeed!
