### ISSUE TITLE
Migration with "Force Last" setting gives n/a scores

### ISSUE THREAD

**Issue by ktgiahieu** [codalab/codabench#1174]
Hi,

I want to report a bug where the scores on the leaderboard returns n/a on the Final Phase of this competition: https://www.codabench.org/competitions/1285. 
<img width="936" alt="image" src="https://github.com/codalab/codabench/assets/42331617/14afc297-2ae5-45d7-a853-f493b470817a">

Although the chosen submissions are run successfully:
<img width="826" alt="image" src="https://github.com/codalab/codabench/assets/42331617/65f099c0-abff-4e6c-b89b-cc44309c1697">

**Comment by ihsaan-ullah** [comment]
Can you please share more details about:
- how you got it 
- steps to reproduce the bug

competition bundle and sample submission

**Comment by ktgiahieu** [comment]
@Didayolo My apology. I made the competition Private by accident. It should work now.

**Comment by Didayolo** [comment]
My bad, I thought that as an admin I should be able to see it even if it's private

**Comment by ihsaan-ullah** [comment]
@ktgiahieu can you upload the following from the failing submission here
<img width="366" alt="Screenshot 2023-09-26 at 9 24 10 PM" src="https://github.com/codalab/codabench/assets/13259262/cf8b2796-f419-4faf-8b88-042cb9087f93">

**Comment by ktgiahieu** [comment]
@ihsaan-ullah Sorry for the confusion. The chosen submissions are all run successfully and produces the scores.json file, and have their scores available in the "My Submissions" tab. The error is that the leaderboard shows n/a even though the chosen submissions are run successfully. 

Here are the files you asked for my chosen submission:
[scoring_result.zip](https://github.com/codalab/codabench/files/12729915/scoring_result.zip)
[prediction_result.zip](https://github.com/codalab/codabench/files/12729916/prediction_result.zip)

**Comment by bethard** [comment]
I'm seeing the same problem with "Force Best" on this competition: https://www.codabench.org/competitions/1481/#/results-tab.

If I switch the leaderboard from "Force Best" to "Add" and manually add submissions to the leaderboard, I get real scores instead of the "n/a"s.

FWIW, out of curiosity, I tried Force_Latest_Multiple, and with that the "n/a"s only show up on the one ranked 1st. Rank 2nd and later seem to be rendered okay.

**Comment by Didayolo** [comment]
I encountered a problem while testing auto-migration on the test server.

Here is the test competition:
https://codabench-test.lri.fr/competitions/143

Here is what I did:
- Make several submissions in development phase from 2 users ("pavao" and "testos")
- Have only 2 submissions on the leaderboard (1 for each user)
- Select "auto-migration" option, and wait for the final phase to start

When the final phase started, the two submissions got run, so the change worked (only leaderboard submissions got run).

In the logs, I can find the scores and everything, so the submissions worked well:

<img width="748" alt="Capture d’écran 2024-04-19 à 13 48 59" src="https://github.com/codalab/codabench/assets/11784999/e944cb22-081e-4164-b933-130b6d25ef4b">

However, on the final phase leaderboard, the scores are N/A and the detailed results lead to 404 error:

<img width="1149" alt="Capture d’écran 2024-04-19 à 13 49 26" src="https://github.com/codalab/codabench/assets/11784999/b247b483-cacd-4412-af3a-bcdeae52497a">

**Comment by Didayolo** [comment]
I close this issue to merge and keep track of it here: #1540.
