### ISSUE TITLE
missing string format in log

### ISSUE THREAD

**Issue by lbeziaud** [codalab/codabench#1176]
https://github.com/codalab/codabench/blob/b728d062712e09e462f8cf422ce90a8166c79244/compute_worker/compute_worker.py#L685

**Comment by Didayolo** [comment]
Good catch

**Comment by Didayolo** [comment]
Fixed: https://github.com/codalab/codabench/commit/932672ff1a2f32a15ba8bc8ade034ef43a7516a7
