### ISSUE TITLE
deleting rerun submission also deletes previous submission

### ISSUE THREAD

**Issue by lbeziaud** [codalab/codabench#1178]
The submission ID 26121 in the following screenshot is a rerun of submission 8330. The other submissions are children of the initial submission 8330 (see https://github.com/codalab/codabench/issues/1177). When deleting submission 26121, everything is deleted. If this is expected then the warning is not explicit enough… I deleted all submissions on a challenge while cleaning up reruns after a test session. There should be a way to delete a rerun without deleting the previous submission.

![Screenshot 2023-10-01 at 14-50-42 Codabench](https://github.com/codalab/codabench/assets/4895292/c2dae715-ed84-4359-b95b-7d54ed40a26f)

**Comment by Didayolo** [comment]
Indeed. I think when using "auto-migration" to run submissions in a final phase, there is the same problem. If you delete the new submissions, the old one gets removed. This can be problematic.

**Comment by Didayolo** [comment]
I mark it as a bug, but it is open for discussion.

**Comment by Didayolo** [comment]
I close this issue to keep track of it only in #1182.
