### ISSUE TITLE
Manual Competition Creation has bug with pages not able to be shown

### ISSUE THREAD

**Issue by bbearce** [codalab/codabench#1180]
# Overview
Manual Competition Creation finishes the creation and saves the competition, but the pages have a bug where you can't select them.

## Own Instance
In my instance I created a competition with pages and info. However only the Terms and Files tabs work after I select anything other than Overview. After this even Overview won't work:

![custom_challenge_tabs_not_working](https://github.com/codalab/codabench/assets/7649007/c796751b-f38d-42ee-b631-d20a9948922a)

## Did the same on Prod
[Comp Ex](https://www.codabench.org/competitions/1445/)
I have the same issue where Overview won't work after clicking off of it.
![comp_creation_tabs_master_branch](https://github.com/codalab/codabench/assets/7649007/dccdb588-fba4-49c0-81a3-7ce976cefe33)

## Challenge Creation Details:
![comp_creation_details](https://github.com/codalab/codabench/assets/7649007/bb10d18e-a792-4f5f-964d-83624151adca)
![comp_creation_pages](https://github.com/codalab/codabench/assets/7649007/0d63597f-8d0e-4a02-931d-a059aafc5835)
![comp_creation_phases](https://github.com/codalab/codabench/assets/7649007/710a4add-6962-40bb-bc88-4693fe6ed9b8)
![comp_creation_leaderboard](https://github.com/codalab/codabench/assets/7649007/577e5e69-e1c4-4f34-9890-f42a06332900)
![comp_creation_administrators](https://github.com/codalab/codabench/assets/7649007/0d906d20-4277-44c2-b560-d599158f77da)

**Comment by bbearce** [comment]
Yeah, We can always reopen if I'm wrong. Better to be lean.

**Comment by ff98li** [comment]
Hi, I am stuck with exactly the same issue. I have tried opening the competition page in different browsers on different machines and none of the page tabs are clickable (except for terms). May I ask how you resolved this?

**Comment by ff98li** [comment]
> So upon further investigation I cannot reproduce: https://www.codabench.org/competitions/1676/ https://www.codabench.org/competitions/1445/

@Didayolo @bbearce Upon further investigation, I have figured out the cause. This bug would be triggered when the current date is not within a competition's phase. So the page tabs in the above instances are no longer clickable at this point. You might consider reopening this issue?

**Comment by Didayolo** [comment]
Apperently is not only a problem with manual competition creation. Ihsan will upload an example bundle.

**Comment by bbearce** [comment]
Was able to reproduce and fix as suggested by Didayolo and Ihsaan-ullah. First, the upload worked in general. Then I deleted the final phase and reproduced the bug. Finally, I changed the dates so that current date is within the phase begin and end dates. Now there is no issue. This is an FYI as I work forward.
