### ISSUE TITLE
Problems with re-running submissions

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1182]
I group here all problems we encounter related to re-running submissions. Click on the relevant issues for more information.

***

## Auto-migration

When a phase allow the advanced option "Auto migrate to this phase", the behavior is a bit problematic: it runs **all** successful submissions of the previous phase in the new phase. I think we want to run only leaderboard submissions. 

Also, it seems that deleting the new submissions created by the migrations delete the original submissions (linked to the point above).

- [x] Auto-migrate only leaderboard submissions
Solved by: #1341. The problem of deletion is solved by: #1311 

***

## Rerun whole phase runs child submissions too

@lbeziaud noticed that re-running submissions in a multi-tasks competition creates independant submissions for all children task: 

- #1177

When rerunning a unique submission (with the button in the action column), the behavior is as expected. The issue only concerns the "rerun all submissions per phase" button. It might be related to:

- #604

- [x] Fix the behavior of "re-run all" functionality
Solved by: #1323

***

## Deleting a re-run submission also delete the original submission

- #1178

I think this is not the expected behavior. We should be able to remove the new submissions withtout removing the original submissions that got re-run. 

- [x] Fix the removal of re-run submissions
Solved by: #1311 

***

## Re-run submission on deleted task

@ihsaan-ullah reported that if you re-run submissions after deleting the task, the submissions get stuck in "Submitting":

- #1179

- [x] Show warning when deleting a task
Solved by: #1301
- [x] Produce error when this happens (error message + avoid creating the new submission)
Solved by: #1301

## Re-creation of submissions when using the re-run functionality

EDIT: we chose to ignore this point and to continue counting the re-runs as new submissions.

@dtuantran noted that using re-run creates new submissions:

- #1162

I think that what he wanted to point out is that the number of submissions of the competition (and then of the platform) is also increased, not reflecting the number of submissions made by participants.

- Do not count re-runs in the submissions count

***

**Comment by ihsaan-ullah** [comment]
> ## Re-creation of submissions when using the re-run functionality
> @dtuantran noted that using re-run creates new submissions:
> 
> * [Re-run submissions without creating new submissions #1162](https://github.com/codalab/codabench/issues/1162)
> 
> I think that what he wanted to point out is that the number of submissions of the competition (and then of the platform) is also increased, not reflecting the number of submissions made by participants.
> 
> * [ ]  Do not count re-runs in the submissions count

Are you sure? I think Tuan wanted to see the same submission run again without creating a new submission

**Comment by ihsaan-ullah** [comment]
> ## Re-creation of submissions when using the re-run functionality
> @dtuantran noted that using re-run creates new submissions:
> 
> * [Re-run submissions without creating new submissions #1162](https://github.com/codalab/codabench/issues/1162)
> 
> I think that what he wanted to point out is that the number of submissions of the competition (and then of the platform) is also increased, not reflecting the number of submissions made by participants.
> 
> * [ ]  Do not count re-runs in the submissions count

@Didayolo are you sure, I think he wanted to rerun the same submission without creating new one
