### ISSUE TITLE
Personalization of Codabench front page with logos of servers hosting organizations

### ISSUE THREAD

**Issue by acletournel** [codalab/codabench#1185]
To better publicize the hosting servers organization of an instance, their logos are added on the front page:

- [x] White version of the logos will be inserted aligned right, in the top banner of Codabench (#1219):
![image](https://github.com/codalab/codabench/assets/19392699/2dbb4e36-8ad8-4142-84c5-d8ad3ce5123a)
- [x] The url of each institution is linked to the logos (#1219):
www.lisn.upsaclay.fr
www.universite-paris-saclay.fr
www.cnrs.fr
- [x] Documentation of the feature in the wiki should allow any Codabench instance admin to personalize his front page with his own logos/urls, as a new production server setting step: https://github.com/codalab/codabench/wiki/How-to-deploy-Codabench-on-your-server

**Comment by ihsaan-ullah** [comment]
@Didayolo @acletournel 
I have updated the documentation here: https://github.com/codalab/codabench/wiki/How-to-deploy-Codabench-on-your-server#personalize-main-banner
Please check if this is ok
