### ISSUE TITLE
non public solutions made available during challenge

### ISSUE THREAD

**Issue by lbeziaud** [codalab/codabench#1190]
Hello,

I may have misunderstood the concept of "solutions" but recent changes have ended up with my challenges displaying the solutions of tasks in the File tab while the challenge is running, which is a big issue since these are indeed the solutions…

The issue was just reported to me on challenge https://www.codabench.org/competitions/879/ and I manually deleted the files to try to save the challenge, and is still visible on https://www.codabench.org/competitions/880/ (where it is not an issue).

The file tab displays solutions files (here on my main challenge before manual deletion):

![Screenshot 2023-10-09 at 03-59-55 Codabench](https://github.com/codalab/codabench/assets/4895292/2bd48194-c223-4a22-b484-b148af548f17)

And here on competition 880:

![Screenshot 2023-10-09 at 04-42-50 Codabench](https://github.com/codalab/codabench/assets/4895292/16d483f2-f9fc-48d0-9b0b-b87e7bc662ba)

However all these are not set as "Public":

![Screen Shot 2023-10-09 at 04 45 02](https://github.com/codalab/codabench/assets/4895292/5574cc0d-d278-438c-87a7-fac5102df9f4)

This was not the case previously (I cannot pinpoint the exact date but I demoed the challenge several times without noticing that).

Is there some setting I am missing? Displaying and making available the non-public solutions of a running challenge seems like a bug and will be a issue for the results of my challenge…

Edit:

The "In Use" indicator not showing anything is also surprising  since the solution is definitely used:

![Screenshot from 2023-10-09 05-25-43](https://github.com/codalab/codabench/assets/4895292/c06aca24-ca15-43fd-90e4-ded061e37b7d)

**Comment by lbeziaud** [comment]
Would that be the result of this line? Was that intended?

https://github.com/codalab/codabench/blob/1c3d36618bc760963d5b1e37a599e1ef3254b481/src/static/riot/competitions/detail/_tabs.tag#L280

**Comment by Didayolo** [comment]
Indeed, I think this is very misleading, however it is not a bug. I will try to clarify.

### Solution

The "solution" associated to a task is supposed to be an example of working submission. Basically, this is were you put your starting kit submission (either code submission or result submission). The feature is not complete, in the sense that the interface is here but never really used, except in the "files" tab. The ultimate goal is to use the "solution" to validate that the task is working. I find that the name "solution" is counter-intuitive, as it suggests that it is the ground truth (which is not the case). The ground truth of a task should be put in "reference data", which is never publicly available to participants.

### Files tab

The goal of the files tab is to communicate files with the participants. As an organizer, you see all files, and the column "Available" indicates if they are available to download for the participants. By default, "public data", "starting kit", and "solution" (being an example submission) are always available to participants. "scoring program", "ingestion program" and "input data" can be optionnaly made available. "reference data" is never available.
This feature was recently added, that is why you did not have this problem in the past. 

TDLR: "solution" is a misleading naming.

Fix: do not put in "solution" any data that you don't want the participants to access. Use "reference data" for this.

In the future: we need to improve the documentation of these features, and the naming.

**Comment by Didayolo** [comment]
Done: https://github.com/codalab/competition-examples/commit/066200929108994825b1704e38f005a897b181d2
