### ISSUE TITLE
Codabench activation link expired

### ISSUE THREAD

**Issue by Priyarsha31** [codalab/codabench#1198]
Hi, I have created an account in codabench on October 17th, but then forgot to activate it using the link through the registered email. When I tried to activate it on October 24th, it showed that the activation link is invalid, I guess the link expired. And when I tried to sign up again it showed my email already exists but I couldn't login as the account is not active.

**Comment by Didayolo** [comment]
Related to:
- #1018

Please send an email to info@codalab.org with the same email you registered with so we can manually activate your account.
