### ISSUE TITLE
Where to find user profiles?

### ISSUE THREAD

**Issue by bbearce** [codalab/codabench#1200]
There is an organization system in codabench where groups of participants can join an org or group and make submissions as such. One of the features is that you can click a user to see about them:
![image](https://github.com/codalab/codabench/assets/7649007/d166c4ce-a65c-4f85-aee8-1bc936abe106)
![image](https://github.com/codalab/codabench/assets/7649007/e5b57155-4df1-485f-92a1-f3012fa19c40)
![image](https://github.com/codalab/codabench/assets/7649007/9b5b20b3-2996-4188-80d0-90070bfa51cd)

Right now you can only get your either your profile or someone else's from an org you are both in. Maybe this is good. 

My suggestion is that organizers have a convenient way of getting to these profiles. Right now one needs to navigate to https://DN/profiles/user/USERNAME to go to anyone's profile. I suggest we tie these links to the dialog that loads when an admin clicks "Participants" from the competition home screen.
![image](https://github.com/codalab/codabench/assets/7649007/41a1cab2-f755-4037-b469-2d21b3fe6a75)

Thoughts?

**Comment by Didayolo** [comment]
> Right now you can only get your either your profile or someone else's from an org you are both in

You can also see clickable usernames in the leaderboard, and in "Tasks" and "Server status" pages.

Indeed, the "Participants" organizer tab should feature clickable links to.

**Comment by Didayolo** [comment]
The change needed looks like this:

- https://github.com/codalab/codabench/pull/1112/files

**Comment by bbearce** [comment]
Perfect. I'll make a PR. Plan is this:
                
                
```html
...
            <tbody>
            <tr each="{participants}">
                <td><a href="/profiles/user/{username}">{username}</a></td>
                <td>{email}</td>
                <td>{is_bot}</td>
...
```

**Comment by Didayolo** [comment]
Done: 

- #1287
