### ISSUE TITLE
Rabbit connection refused

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1211]
Locally the compute worker logs are showing this:

<img width="1106" alt="Screenshot 2023-11-01 at 6 09 08 PM" src="https://github.com/codalab/codabench/assets/13259262/c0be874f-c980-4336-9343-c300135ce999">

Deleted rabbit from var folder but still did not succeed. I am running the latest develop branch

**Comment by Didayolo** [comment]
I think you need to re-build the dockers, especially rabbit:

https://github.com/codalab/codabench/wiki/Upgrade-RabbitMQ

Also, check that your `docker-compose.yml` match the lastest changes.

**Comment by ihsaan-ullah** [comment]
> I think you need to re-build the dockers, especially rabbit:
> 
> https://github.com/codalab/codabench/wiki/Upgrade-RabbitMQ
> 
> Also, check that your `docker-compose.yml` match the lastest changes.

Solved by following these instructions
