### ISSUE TITLE
Submission stuck in `submitting`

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1212]
In this competition: https://www.codabench.org/competitions/1612/?secret_key=b30e243c-5669-42de-974a-e02c81de4381 submission `28209` is stuck in status `submitting` without any logs

Competitinon has 10 tasks

**Comment by ihsaan-ullah** [comment]
submission `28220` has failed (both ingestion and scoring but the status showing is `Finished`

**Comment by Didayolo** [comment]
Can you provide more information? What queue are you using? Etc.

**Comment by ihsaan-ullah** [comment]
> Can you provide more information? What queue are you using? Etc.

Default queue

**Comment by ihsaan-ullah** [comment]
closing this for now. Will report again if this happens again
