### ISSUE TITLE
Test server: no logos

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1221]
On https://codabench-test.lri.fr/

<img width="1226" alt="Capture d’écran 2023-11-10 à 17 29 06" src="https://github.com/codalab/codabench/assets/11784999/5ebf4f6f-3b04-45a9-b407-1d3d97da8d77">

Uploads are not working either

**Comment by dtuantran** [comment]
It's because of the minio-test.lri.fr certificate expired. I've renewed it, it works now.
