### ISSUE TITLE
Leaderboard data of last entry

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1231]
When we have Force last multiple rule for leaderboard, the title in the column `data of last entry` is misleading.

<img width="443" alt="Screenshot 2023-11-17 at 5 57 47 PM" src="https://github.com/codalab/codabench/assets/13259262/58db7d1a-53ed-4ef0-bea0-b7e2b0160ccd">

each submission on the leaderboard is showing its own date
- either we show just the last submission date for all submissions
- or we plan something else

**Comment by Didayolo** [comment]
How can you tell this is not the date of last entry of the participant?

But yes maybe we should put the date of the given entry instead of date of last entry.

**Comment by ihsaan-ullah** [comment]
> How can you tell this is not the date of last entry of the participant?

Sorry, my mistake. This is indeed the last entry date
