### ISSUE TITLE
Download all submissions (on leaderboard) button

### ISSUE THREAD

**Issue by fchuffar** [codalab/codabench#1232]
Dears, 

First of all, thank you for the incredible work you do.

Question: On the Codalab platform, for the challenge administrator, on the leader board, there's a "Download all submissions on leaderboard" button. This feature has disappeared on the Codabench palteform. Do you plan to reintroduce this feature in Codabench?

https://www.codabench.org/competitions/1043/?secret_key=391dd24a-9cd7-4496-a4bc-bc6333fe7d2e

https://codalab.lisn.upsaclay.fr/competitions/9090?secret_key=703243e6-f0e8-4014-aeaa-64baab683a36

**Comment by fchuffar** [comment]
In the same way, is it possible to add a button in the "submissions" admin tab to download the programs for all submissions?

**Comment by Didayolo** [comment]
More generally, a "download all submissions" is an important feature.

**Comment by Didayolo** [comment]
Referring to the submissions dialog for a project, I think it would be good to have all the actions which are available for single individual entries available with a bulk action button for all those entries which are checked (download, delete ...)

**Comment by Didayolo** [comment]
@nicomy
