### ISSUE TITLE
Files Available not cancelable

### ISSUE THREAD

**Issue by fchuffar** [codalab/codabench#1234]
Dears, 

It is possible to make programs and/or input data available by checking the "Make XXX available" checkboxes in the edit menu. But once validated, the checkboxes remain unchecked when the challenge is re-edited. It is therefore impossible to go back. 

https://www.codabench.org/competitions/1692/?secret_key=439a40e9-9de7-4336-918f-ac983d5dd22c

**Comment by ihsaan-ullah** [comment]
Hi, I am not sure what issue are you facing.

I tried to reproduce and everything looks fine

Before I make programs and datasets available, I see this in files tab:
<img width="920" alt="Screenshot 2023-11-19 at 4 48 54 PM" src="https://github.com/codalab/codabench/assets/13259262/e8cacc36-0ac7-4b0b-aa14-6e4df7818119">

Edit competition in this case shows:
<img width="337" alt="Screenshot 2023-11-19 at 4 47 23 PM" src="https://github.com/codalab/codabench/assets/13259262/6717426d-af28-4dc6-bf54-ecd20d20dc16">

When I edit competition and check make programs and data available, I see this in files tab:
<img width="913" alt="Screenshot 2023-11-19 at 4 47 55 PM" src="https://github.com/codalab/codabench/assets/13259262/3b4f9a57-6049-4eb3-8254-d75e80c70ee1">

Edit competition shows this now:
<img width="270" alt="Screenshot 2023-11-19 at 4 48 08 PM" src="https://github.com/codalab/codabench/assets/13259262/dbc1000a-39ac-4f78-8d41-fe96de4c2a0b">

**Comment by Didayolo** [comment]
I did not face the issue either. I also tried with a non super-user account and could not reproduce the problem.

Are you sure the changes are getting saved? Can you retry the whole procedure?

**Comment by ihsaan-ullah** [comment]
Possibly linked to #1236

**Comment by fchuffar** [comment]
Sorry, 
Adrien is right, I hadn't saved the changes. I had clicked on the "save" button, but the high latency (probably due to my network) led me astray.
The behavior is as expected.
