### ISSUE TITLE
Files available not working (when task does not have input data or ingestion program)

### ISSUE THREAD

**Issue by Aktsvigun** [codalab/codabench#1236]
Competition link: https://www.codabench.org/competitions/1711/

Hi, I've set the parameters `Make Programs Available` and `Make Input Data Available` to True (kindly see the attached image 1), however, nothing is still visible from the `Files` tab (attached image 2). Could you please help me fix this? Thanks!

<img width="236" alt="Screenshot 2023-11-20 at 19 17 38" src="https://github.com/codalab/codabench/assets/36672861/0e8e7549-e55f-45e2-87df-e6609ad4d146">
<img width="932" alt="Screenshot 2023-11-20 at 19 19 15" src="https://github.com/codalab/codabench/assets/36672861/bf5918df-e376-41b8-a49e-933c0ad9b13a">

**Comment by Didayolo** [comment]
Thank you for reporting this problem. I am able witness it on your competition indeed.

We are going to investigate this issue. Some questions:

- Did you create this competition using a bundle submission or the form ("upload" or "create")?
- Is it happening again when you re-create the same competition?
- If you used a bundle file, could you please share it?

It seems that the dumps are also failing for this competition:
<img width="1116" alt="Capture d’écran 2023-11-20 à 22 23 02" src="https://github.com/codalab/codabench/assets/11784999/a361c8ac-979b-4a71-8c21-cb8e1d31bd29">

**Comment by Aktsvigun** [comment]
Hi Adrien,

Thanks! Regarding your questions:

1. I created it from scratch (“create”)
2. Will check this tomorrow and let you know!
3. Not applicable

**Comment by Didayolo** [comment]
I could dump the re-upload the competition, and the problem happens again.

The fact that you used the form ("create") is an interesting information. The problem may be there.

**Comment by Aktsvigun** [comment]
Thanks Adrien,

I'm however unable to create the competition using the "upload" form as I get the following error.

<img width="550" alt="Screenshot 2023-11-21 at 09 07 42" src="https://github.com/codalab/codabench/assets/36672861/4d24ada5-0561-4a14-95c7-df24817ddff4">


An interesting thing here is that if I download your `bundle.zip`, extract it, and zip it back, it is not anymore accepted by the server.

**Comment by ihsaan-ullah** [comment]
> I could dump the re-upload the competition, and the problem happens again.

Can you please share the dump with me

**Comment by ihsaan-ullah** [comment]
> Thanks Adrien,
> 
> I'm however unable to create the competition using the "upload" form as I get the following error.
> 
> <img alt="Screenshot 2023-11-21 at 09 07 42" width="550" src="https://user-images.githubusercontent.com/36672861/284505877-4d24ada5-0561-4a14-95c7-df24817ddff4.png">

This is because your zip bundle is missing `competition.yaml` file or your are zipping the folder. 
If you have the first problem of missing yaml file then please check these example bundles: https://github.com/codalab/competition-examples/tree/master/codabench

If your yaml file is there then make sure to zip the contents of the folder where you have your yaml and other files (do not zip the parent folder )

**Comment by Aktsvigun** [comment]
Hi Insah,

I'm completely sure my bundle has the `competition.yaml` file in the main directory. Please find it attached.
[bundle_2.zip](https://github.com/codalab/codabench/files/13423593/bundle_2.zip)

**Comment by Aktsvigun** [comment]
Apologies if my question is primitive, do you mean `zip -r bundle.zip bundle/*` ?

**Comment by ihsaan-ullah** [comment]
You can use the following

```
cd bundle
```

```
zip -r bundle.zip ./*
```

**Comment by Aktsvigun** [comment]
Thanks a lot, Insah,

I've created the competition using the `upload` form: https://www.codabench.org/competitions/1714/

Yet, `Make programs available` still does not work for me (I'm testing this from another account).

**Comment by ihsaan-ullah** [comment]
<img width="1144" alt="Screenshot 2023-11-21 at 2 17 34 PM" src="https://github.com/codalab/codabench/assets/13259262/f3738e44-c048-4afb-94c2-1259e290deaa">

I see them clearly in the files tab

**Comment by Aktsvigun** [comment]
Yes, starting kit and public data are the `publicly visible` files that I set in the `competition.yaml` file. It seems that `make programs available` (and probably `make input files available` as well) cannot be changed after creation, which may be a bug.

**Comment by ihsaan-ullah** [comment]
Noting this down. We will look into this soon.

**Comment by ihsaan-ullah** [comment]
# Todos:

- checking make programs available and make input data available does not work.
- this bundle when uploaded can reproduce this bug [Bundle](https://github.com/codalab/codabench/files/13423593/bundle_2.zip)
- also check this when a comp is created using the UI

**Comment by Didayolo** [comment]
Other issues related to the Files tab:

- #1229

**Comment by Didayolo** [comment]
@Aktsvigun 

How did you upload the scoring program and input data?

I am thiking maybe you have the same problem of including a folder in the root of the zip instead of zipping the files directly.

Is that the case? I am not sure but the problem may be linked to this.

Could you try to zip the scoring program and input data using Ihsan's procedure, re-upload them, and re-create a task, to see if it solves the problem?

```
cd folder
zip -r program.zip *
```

**Comment by Didayolo** [comment]
The problem may comes from below this line: https://github.com/codalab/codabench/blob/1f93bbc518d1c5b63a052d04985069d523716832/src/static/riot/competitions/detail/_tabs.tag#L227

**Comment by Didayolo** [comment]
I confirm it is specifically linked to tasks, and not to competition. When changing to another task it works, then back to this task it fails.

The only difference I can think of right now is that the failing task does not have an ingestion program.

**Comment by Didayolo** [comment]
I confirm that the bug raises when the task does not have an ingestion program.

**Comment by Aktsvigun** [comment]
Dear @Didayolo , this indeed works, thank you! But my public data is still invisible to other users, kindly see competition https://www.codabench.org/competitions/1741. There is only **input data** present in the **"Files"** tab.

**Comment by Didayolo** [comment]
When I try to edit the phase of your competition using the editor, I see no public data linked to it:

<img width="1064" alt="Capture d’écran 2023-11-24 à 14 26 56" src="https://github.com/codalab/codabench/assets/11784999/b79cab73-78dc-4f5e-9423-76e6a76d71a3">

**Comment by Aktsvigun** [comment]
This looks strange because I included it in the `competition.yaml` file - have I done this wrong?

<img width="820" alt="Screenshot 2023-11-24 at 15 41 30" src="https://github.com/codalab/codabench/assets/36672861/9bcc14cc-8304-4259-adc8-97a09026b4d1">

**Comment by Didayolo** [comment]
Hi @Aktsvigun, expect some delay in the fix of this problem. However, in the meantime, you can easily work-around it by supplementing your tasks with a dummy ingestion program. Is there any remaining issue that you are not able to avoid?

**Comment by ihsaan-ullah** [comment]
> This looks strange because I included it in the `competition.yaml` file - have I done this wrong?
> 
> <img alt="Screenshot 2023-11-24 at 15 41 30" width="820" src="https://private-user-images.githubusercontent.com/36672861/285484637-9bcc14cc-8304-4259-adc8-97a09026b4d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODU1MTMsIm5iZiI6MTcwMTE4NTIxMywicGF0aCI6Ii8zNjY3Mjg2MS8yODU0ODQ2MzctOWJjYzE0Y2MtODMwNC00MjU5LWFkYzgtOTdhMDkwMjZiNGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE1MjY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NWQ2OWJkMzczOWFiYzFkMDdkMDQwY2NlYTZhOTdlZGY5YzViMjljMmU2MWE5OTc1MWFlOTZhZjVlOTM3OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PDtYr582VL8tnjhZa0umBpEFCcGEw60NKoOoeZgfQnI">

You can still link a public data after your competition is uploaded.

**Comment by Didayolo** [comment]
@bbearce Another interesting issue for you if you want / have time for it.
