### ISSUE TITLE
Multitask support

### ISSUE THREAD

**Issue by Aktsvigun** [codalab/codabench#1237]
Hi, I also want to add several different tracks (phases) for my competition similar to how it is here: [https://codalab.lisn.upsaclay.fr/competitions/15715#phases](https://codalab.lisn.upsaclay.fr/competitions/15715#phases).

Each track (phase) should be independent of each other and can be taken part in independently. While I can see this feature in Codalab (the link I've shared above), I cannot do the same this with Codabench. What I get is the following error:

<img width="884" alt="Screenshot 2023-11-20 at 19 44 34" src="https://github.com/codalab/codabench/assets/36672861/8b0bcfdc-69c4-4b4e-bb48-aa8e750ebd3b">

However, as these are independent phases, I want to start them all at the same time, which seems impossible to make.

Would you please tell me whether I'm doing something wrong or this feature is not supported in the current version of Codabench?
Thanks!

**Comment by Didayolo** [comment]
In Codabench however, the UI could be improved to navigate with ease between the results of different tasks.

Right now, all tasks are just fused together horizontally on the same leaderboard table, which can quickly becomes hard to read.

<img width="738" alt="Capture d’écran 2023-11-20 à 22 41 14" src="https://github.com/codalab/codabench/assets/11784999/17ab96b9-892a-49a1-92ec-e4cf736d4f73">



For instance, on CodaLab, which had these buttons:

<img width="1175" alt="Capture d’écran 2023-11-20 à 22 38 55" src="https://github.com/codalab/codabench/assets/11784999/1b320b75-68ee-4391-a509-96ca6d33f3db">

**Comment by Aktsvigun** [comment]
Dear @Didayolo , is it possible to report different metrics for different tasks? E.g. return Accuracy & F1-score **for task 1 and task 2**, and MAE **for task 3.**

**Comment by Didayolo** [comment]
Hello,

1. You can have a different scoring program for each task, so you can easily compute different metrics for different tasks. However, I think you cannot have different column names for the different tasks. A work-around is to name the score with a generic name, such as "Score", and to explain in the documentation what score you have for what phase. Another way is to compute all scores for all tasks.

2. Maybe this is linked to this issue:

- https://github.com/codalab/codabench/issues/1055

You can try a different submission rule than "Force last" in the edition of the leaderboard to see if it solves the problem.

**Comment by ihsaan-ullah** [comment]
shifted to discussion #1334
