### ISSUE TITLE
Role of organization

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1240]
The organization, or team system, feels a bit incomplete right now.

A possible idea:
- Count the submissions limit per team
- Add a "Only allow teams to submit" setting

**Comment by Didayolo** [comment]
Related:

- #1217

**Comment by dtuantran** [comment]
![image](https://github.com/codalab/codabench/assets/7440668/fe9075a3-4fc6-4a62-9ad2-2d02b65f7b43)

Maybe user needs register to a Benchmark as a team.

**Comment by Didayolo** [comment]
It is because of the roles and permissions within the organization:

<img width="739" alt="Capture d’écran 2023-11-21 à 17 46 35" src="https://github.com/codalab/codabench/assets/11784999/f6e828f9-3d90-417d-b7c0-4404e307aa41">

**Comment by Didayolo** [comment]
We could add the "Date joined" and "Role" columns to the user table in the main organization page. This would be less confusing.

**Comment by ihsaan-ullah** [comment]
> A possible idea:
> 
> * Count the submissions limit per team


Do you mean to combine the limits of people as an organization and e.g. 2 people can submit 100 submissions together per day so the organization with these 2 people will have 100 submissions per day and any person can use it?
This seems ok but should be discussed in details how this will be handled properly and if this is useful

> * Add a "Only allow teams to submit" setting

Are there any use-cases where this is helpful?


I think organizations are too limited. Organizations and Teams should be two different things. 
- Team could be used just for submissions I.e. people make a team and submit through it
- Organization is like github organization, which can have competitions, datasets, and other resources.
- People can be invited to the organization via email and then with the assigned role they can do stuff e.g. organize competitions or just view stuff 
- To make things simpler organization could be used as a profile like facebook. e.g. i can login with my account with normal credentials and then switch to the organization so I can use codabench either with my personal profile or with my organization profile. 
- later on organization can have their own signing procedure e.g. single sign on feature for one organization. This is a bit complicated but I think it is doable. E.g. to setup single sign on for an organization we ask them to provide some details and configure some settings and then if everything works people can see that sign-in in the login page. The login page right now has username/email and password. Later on we can have sign in with username/email, Google, Github etc and a separate option with sign in using organization account which is linked to the single sign on

**Comment by ihsaan-ullah** [comment]
shifted to discussion #1334
