### ISSUE TITLE
Submission status issue

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1241]
A submission was running and the statuses went from Submitted -> preparing -> Running, and then went back to Preparing

<img width="1228" alt="Screenshot 2023-11-23 at 2 12 00 PM" src="https://github.com/codalab/codabench/assets/13259262/e9a54b47-e8ff-4e81-8507-e53ba7b92593">

The logs in the black screen in submission panel are also mixed up
<img width="540" alt="Screenshot 2023-11-23 at 2 13 13 PM" src="https://github.com/codalab/codabench/assets/13259262/0440015e-9ef5-4f2f-b589-f1e8d5970d16">

**Comment by ihsaan-ullah** [comment]
Note: this is happening on outside compute worker

**Comment by Didayolo** [comment]
Can you reproduce it or it was just once?

**Comment by ihsaan-ullah** [comment]
Closing this as this happened on NERSC only.
