### ISSUE TITLE
Latex rendering

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1243]
`<` and `>` symbols are not rendered correctly

<img width="611" alt="Screenshot 2023-11-23 at 7 18 11 PM" src="https://github.com/codalab/codabench/assets/13259262/940790af-3495-41be-b3e6-941431044afd">

**Comment by Didayolo** [comment]
This is happening on the raw text? Not the LaTeX rendering?

**Comment by ihsaan-ullah** [comment]
this is happening when latex is rendered. I think < and > are escaped as HTML tag start and end so. because of this you cannot use these signs in a latex formula

**Comment by bbearce** [comment]
How exactly should I test? I tried this:

![image](https://github.com/codalab/codabench/assets/7649007/ecab2cfc-e753-4584-90af-ce3c5e72f577)

but I still see the &amp;lt and &amp;gt symbols.

**Comment by ihsaan-ullah** [comment]
the problem was with < and > in latex something like

```$x < 3$```
