### ISSUE TITLE
Ranking on leaderboard

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1245]
It seems the ranking is not working properly.

Lowest score = best 

<img width="1185" alt="Screenshot 2023-11-28 at 8 17 26 PM" src="https://github.com/codalab/codabench/assets/13259262/82ece412-f5f9-4699-9c78-3dad1ab945f6">

**Comment by ihsaan-ullah** [comment]
The problem is a bit complicated. Submissions, tasks, scores are coming from backend and are independent. Then on frontend scores are shown based on tasks. I propose to change this and prepare the rows on backend and then send to front-end

**Comment by Didayolo** [comment]
I close this issue to keep track of it only in #1171.
