### ISSUE TITLE
Replace "Date of last entry" by "Date" in the leaderboard

### ISSUE THREAD

**Issue by dtuantran** [codalab/codabench#1246]
For example: for this participant, all submissions on leaderboard have "Entries" **11** and the same date

![image](https://github.com/codalab/codabench/assets/7440668/d74272c2-5a5e-44c4-bc24-cf84416d58c9)

![Screenshot from 2023-11-28 17-48-07](https://github.com/codalab/codabench/assets/7440668/6300ee3f-fdab-41d8-8b0d-cb82f4c98420)

**Comment by Didayolo** [comment]
I don't think it is a bug:

- Entries is the number of entries made by the participant
- Date of last entry is the date of the last entry of the given participant

Maybe we could replace date of last entry by simply the date of the entry for more clarity and a more informative column.

**Comment by Didayolo** [comment]
Same discussion here:

- #1231

**Comment by Didayolo** [comment]
Done: 

- #1292
