### ISSUE TITLE
Task removal affects old submissions to

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1250]
I had task 1 connected to competition and the scores were showing in the leaderboard:

<img width="413" alt="Screenshot 2023-11-29 at 8 54 28 PM" src="https://github.com/codalab/codabench/assets/13259262/7ad83da0-c6db-4073-9013-e74563cbd909">

Then I removed this task from the competition and added a new one and now I see `n/a` for old submissions.
<img width="401" alt="Screenshot 2023-11-29 at 8 54 36 PM" src="https://github.com/codalab/codabench/assets/13259262/23d1b5c5-e24a-4736-a8b9-4506815a5e69">

It makes sense why this is happening but should this happen?

**Comment by ihsaan-ullah** [comment]
> I think it makes sense. What behavior would you expect / prefer ?

maybe a warning or something because we were thinking that the old scores will stay there on leaderboard

**Comment by Didayolo** [comment]
Adding a warning with confirmation is a good idea. However, keeping the old score is not advised as it would be misleading: new submissions would be then compared with old submissions made on a different task.
