### ISSUE TITLE
Submission issue

### ISSUE THREAD

**Issue by yumingfan-0219** [codalab/codabench#1252]
Hi!

The results I submitted have been in a 【submitted】 state for a long time. Can you help me confirm the reason? The submission ID is 31754

Thank you for your time！

**Comment by ihsaan-ullah** [comment]
Hi @yumingfan-0219,

Can you please share some more details:
- Which queue are you using?
- From how long is the submission stuck at `Submitted`

**Comment by yumingfan-0219** [comment]
actually, i didnt choise queue,maybe its the default setting?

Stuck at least ten hours 

the link of competition is https://www.codabench.org/competitions/1455/

**Comment by dtuantran** [comment]
We got an unknown bug:
`django_1          | [2023-12-12 10:54:12 +0000] [13] [ERROR] Exception in ASGI application
django_1          | Traceback (most recent call last):
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 157, in run_asgi
django_1          |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
django_1          |     return await self.app(scope, receive, send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
django_1          |     await instance(receive, send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/sessions.py", line 183, in __call__
django_1          |     return await self.inner(receive, self.send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/middleware.py", line 41, in coroutine_call
django_1          |     await inner_instance(receive, send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 58, in __call__
django_1          |     await await_many_dispatch(
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch
django_1          |     await dispatch(result)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 73, in dispatch
django_1          |     await handler(message)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
django_1          |     await self.disconnect(message["code"])
django_1          |   File "/app/src/apps/competitions/consumers.py", line 65, in disconnect
django_1          |     await self.close()
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/generic/websocket.py", line 226, in close
django_1          |     await super().send({"type": "websocket.close"})
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 81, in send
django_1          |     await self.base_send(message)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/sessions.py", line 236, in send
django_1          |     return await self.real_send(message)
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 234, in asgi_send
django_1          |     raise RuntimeError(msg % message_type)
django_1          | RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'`

After restarting our services, it seems the submission processing working again. You can try to re-run your submission. We are continuing the investigation.

**Comment by Didayolo** [comment]
New submissions are being processed, however, I think that the old submissions remain stuck.

**Comment by dtuantran** [comment]
For your information, the old submission stuck in the database, not in RabbitMQ. You need to cancel first then re-run your submission.

**Comment by yumingfan-0219** [comment]
Restart solve the question I meet, thanks

**Comment by yumingfan-0219** [comment]
*Resubmit

**Comment by yumingfan-0219** [comment]
the link of competition is https://www.codabench.org/competitions/1455/
submission ID is 31754

I got another issue, my submission stuck in the status [Scoring] for about 0.5 hours

**Comment by yumingfan-0219** [comment]
The link of competition is https://www.codabench.org/competitions/1455/, and submission id is 32862

this time, my submission stuck in the status[Scoring] :)

Thank you for your time for this issue

**Comment by ihsaan-ullah** [comment]
Your submission is showing `cacelled` status. 

The issue was because of docker pull failure
```
Pull for image: codalab/codalab-legacy:py39 returned a non-zero exit code! Check if the docker image exists on docker hub.
```

We will look into it after the vacations. In the meantime if you get this issue again, please rerun/resubmit your submission and it will work. 

You can see the logs here:
<img width="1158" alt="Screenshot 2023-12-23 at 12 22 05 PM" src="https://github.com/codalab/codabench/assets/13259262/0cd35d58-2a61-471b-a07b-28ed33890713">

**Comment by ihsaan-ullah** [comment]
Connected: 
- #1263
- #1256
