### ISSUE TITLE
Unable to verify my account

### ISSUE THREAD

**Issue by sadat1971** [codalab/codabench#1255]
I am trying to verify my account (via the link sent to my email). However, I keep getting the error *404 Site codabench.org is not served on this interface* with the secure connection and *404 page not found* with the nonsecure connection. 

- What browser and version are you using?

I am using google chrome (Version 120.0.6099.109 (Official Build) (64-bit)) with Windows 11.

However, I also tried with Edge, and the problem persists.

**Comment by ClaudiuCreanga** [comment]
I also have this issue. I also can't login into my account now, chose a different password or recover password as none of the options work until you clicked the activation link.

**Comment by BorisGuo6** [comment]
I have the same issue. I used Safari in MacOS and it also shows "404 Site codabench.org is not served on this interface"

**Comment by UrwahJawaid** [comment]
Same issue for me too. Any solution will be welcome.

**Comment by ihsaan-ullah** [comment]
@ClaudiuCreanga @sadat1971 @BorisGuo6 

@DimitrisAndreadis 

There is a small problem which we are fixing. 

In order to activate your account, please copy the link you have received which looks like:
```
http://codabench.org/profiles/activate/ACTIVATION_CODE
```
and add `www.` just before codabench.org, example below:
```
http://www.codabench.org/profiles/activate/ACTIVATION_CODE
```

This will solve your problem

**Comment by sadat1971** [comment]
> @ClaudiuCreanga @sadat1971 @BorisGuo6 @UrwahJawaid @DimitrisAndreadis
> 
> There is a small problem which we are fixing.
> 
> In order to activate your account, please copy the link you have received which looks like:
> 
> ```
> http://codabench.org/profiles/activate/ACTIVATION_CODE
> ```
> 
> and add `www.` just before codabench.org, example below:
> 
> ```
> http://www.codabench.org/profiles/activate/ACTIVATION_CODE
> ```
> 
> This will solve your problem

Thank you, that worked for me :)

**Comment by dtuantran** [comment]
I've fix the domain name to `www.codabench.org` in django. It should resolve this issue.
