### ISSUE TITLE
Codabench Email Activation Error

### ISSUE THREAD

**Issue by DimitrisAndreadis** [codalab/codabench#1258]
When clicking the activation email I get this error

404 Site codabench.org is not served on this interface

**Comment by ClaudiuCreanga** [comment]
There is already issue 1255 about this

**Comment by ihsaan-ullah** [comment]
@DimitrisAndreadis 

There is a small problem which we are fixing. 

In order to activate your account, please copy the link you have received which looks like:
```
http://codabench.org/profiles/activate/ACTIVATION_CODE
```
and add `www.` just before codabench.org, example below:
```
http://www.codabench.org/profiles/activate/ACTIVATION_CODE
```

This will solve your problem
