### ISSUE TITLE
Submission stuck on scoring status (Twice)

### ISSUE THREAD

**Issue by wengjincheng** [codalab/codabench#1263]
***This is a template, please remove any non-relevant details to your issue***

If you are competition participant: yes
-----------------------------------

- This Github repository is about the **platform** itself.
- If you problem is specific to a competition, **please contact directly its organizers**.

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

- Please post a link to your competition.

If you are having trouble using the site:
-----------------------------------------

- What browser and version are you using?
Chrome 120.0.6099.129
- What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

https://www.codabench.org/competitions/1601/#/participate-tab

**Comment by ihsaan-ullah** [comment]
This happened because of a known issue which is under investigation. You can see the error here:
<img width="1107" alt="Screenshot 2024-01-10 at 8 18 15 PM" src="https://github.com/codalab/codabench/assets/13259262/a22ff9d6-58b2-4d82-9316-2705b51636f4">


Closing this to keep track in #1252
