### ISSUE TITLE
Home page left columns text 

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1268]
Make the text expandable only showing few lines first
<img width="536" alt="Screenshot 2024-01-09 at 10 01 22 PM" src="https://github.com/codalab/codabench/assets/13259262/33604cfc-6ffc-4d7a-a49a-61b878a26499">

**Comment by Didayolo** [comment]
We could use the new "Show more" button:

<img width="405" alt="Capture d’écran 2024-01-21 à 02 42 12" src="https://github.com/codalab/codabench/assets/11784999/5e8abdeb-e16c-478c-a092-0da7bb26d640">

Or maybe a fading text

**Comment by Didayolo** [comment]
Move to discussion
