### ISSUE TITLE
All the submission stuck in "submitted" phase

### ISSUE THREAD

**Issue by starsholic** [codalab/codabench#1270]
Hi, @ihsaan-ullah 

We have organized a competition at https://www.codabench.org/competitions/1772. However, we've encountered an issue today where all submissions remain in the "submitted" phase for several hours without progressing. This issue persists currently. We have attempted to resubmit multiple times, but the problem continues. Could you help us check it?

Thanks

**Comment by starsholic** [comment]
tried build my own compute worker, but still receive errors in below.
`[2024-01-11 07:53:25,956: INFO/ForkPoolWorker-1] Submission patch failed with status = 500, and response = 
b'<h1>Server Error (500)</h1>'
[2024-01-11 07:53:25,956: INFO/ForkPoolWorker-1] Destroying submission temp dir: /codabench/tmpi_1r5vcn
[2024-01-11 07:53:25,956: ERROR/ForkPoolWorker-1] Task compute_worker_run[7196f2db-0ac3-4595-9b6a-74cd3be5d83c] raised unexpected: SubmissionException('Failure updating submission data.')
Traceback (most recent call last):
  File "/compute_worker.py", line 115, in run_wrapper
    run.prepare()
  File "/compute_worker.py", line 750, in prepare
    self._update_status(STATUS_PREPARING)
  File "/compute_worker.py", line 359, in _update_status
    self._update_submission(data)
  File "/compute_worker.py", line 342, in _update_submission
    raise SubmissionException("Failure updating submission data.")
compute_worker.SubmissionException: Failure updating submission data.`

**Comment by Didayolo** [comment]
Thank you for reporting this issue. We are looking into it and trying to resolve the service as soon as possible.

**Comment by starsholic** [comment]
Thanks! Really appreciate your assistance.

Adrien Pavão ***@***.***> 于2024年1月11日周四 21:05写道：

**Comment by Didayolo** [comment]
The problem should be solved now. Feel free to re-open the issue if you face it again.

**Comment by starsholic** [comment]
Hi @Didayolo,

The evaluation system (https://www.codabench.org/competitions/1772) faces the same issue again.
Could you help us check it?

Thanks!

**Comment by starsholic** [comment]
Hi Adrien,

We face the same issue again. Could you help us check that?
Thanks!

Best Regards,
David

Adrien Pavão ***@***.***> 于2024年1月12日周五 22:21写道：
