### ISSUE TITLE
No administrator features button

### ISSUE THREAD

**Issue by Aktsvigun** [codalab/codabench#1271]
Dear team,

I have an urgent matter with the competition. I need to resubmit the phase, but I do not have an administrator features button, [mentioned here](https://github.com/codalab/codabench/wiki/Competition-Detail-Page): `(Cog/Gears icon)`.

[My competition link (click me)](https://www.codabench.org/competitions/1752).

Would very appreciate your help here!

**Comment by ihsaan-ullah** [comment]
Hi @Aktsvigun, 

The interface has changed and is a bit different than what is mentioned [here](https://github.com/codalab/codabench/wiki/Competition-Detail-Page). We will update the documentation soon.

To solve your problem,  please click the edit button, select Phases tab and make the required changes. Please check the screenshots below:

Edit button
<img width="560" alt="Screenshot 2024-01-13 at 9 01 52 PM" src="https://github.com/codalab/codabench/assets/13259262/997c00b6-9d3b-481d-90a5-2ccc5ebacd78">

Phases tab
<img width="881" alt="Screenshot 2024-01-13 at 9 02 17 PM" src="https://github.com/codalab/codabench/assets/13259262/4d2cd809-4b8e-480e-b54f-2be682956cb8">

**Comment by Aktsvigun** [comment]
Many thanks, Ihsan! 

Btw it would be great if there was a button to download all submissions (the submission files, not the scores) - for example, if one wants to make a recalculation of the scores at the end of the competition. I could only do it by manually clicking on each submission and then downloading it.
