### ISSUE TITLE
How can force paricipants' submission to the leaderboard

### ISSUE THREAD

**Issue by starsholic** [codalab/codabench#1274]
Hi,

As a competition organizer, how can we force participants' submissions to the leaderboard?

Thanks

**Comment by ihsaan-ullah** [comment]
Click Edit 
<img width="567" alt="Screenshot 2024-01-14 at 1 02 53 PM" src="https://github.com/codalab/codabench/assets/13259262/45e5dbcd-b600-4d18-8c96-730292ed9310">

Select Leaderboard tab, click edit button In front of the leaderboard
<img width="874" alt="Screenshot 2024-01-14 at 1 03 14 PM" src="https://github.com/codalab/codabench/assets/13259262/9693c99d-d48c-460d-99ca-dbc936c70b80">

Select one the last 3 options in the dropdown
<img width="527" alt="Screenshot 2024-01-14 at 1 03 57 PM" src="https://github.com/codalab/codabench/assets/13259262/8279385e-85cb-4e3c-b9b6-9fd9be08469f">

**Comment by starsholic** [comment]
Thanks!
