### ISSUE TITLE
Show multiple organizers in a competition banner

### ISSUE THREAD

**Issue by ff98li** [codalab/codabench#1276]
Hi,
currently Codabench is only able to display the page creator's ID as the competition organizer, as shown below:
![Screenshot 2024-01-15 at 5 33 17 PM](https://github.com/codalab/codabench/assets/55061801/a75a8f1f-f5c7-478c-837d-341fbd5efd5e)

I wonder whether it would be possible to display multiple users who are added as admins in the banner as organizers as well.

Thanks!

**Comment by ihsaan-ullah** [comment]
Hi, You can only see the user who has created this competition. To give credits to other organizers, you can use the competition pages
