### ISSUE TITLE
Solution is always running

### ISSUE THREAD

**Issue by Aktsvigun** [codalab/codabench#1278]
Dear team,

Participants in my competition (https://www.codabench.org/competitions/1752/) are experiencing the following bug. Some solutions are always shown "running" and never stop.

I tried to reproduce the bug in my account, and sometimes solutions that successfully finished for other participants, are also shown as always running (do not stop after 1 day). I also noticed that in such solutions for one or more tasks, there arises the following error on the "prediction" step (see the attachment): 
`Pull for image: codalab/codalab-legacy:py39 returned a non-zero exit code! Check if the docker image exists on docker hub.`
<img width="1078" alt="Screenshot 2024-01-16 at 10 20 59" src="https://github.com/codalab/codabench/assets/36672861/e2e8993c-6e36-4ead-a569-91b4c035edeb">

Could you please help with solving this bug? Thanks!

P.s. I understand the general purpose of the "prediction" step, but in my competition the participants are already submitting the predictions. Thus, I also wonder whether it is possible to skip this step as it always produces some errors (which, however, generally do not hinder the successful submissions).

**Comment by Didayolo** [comment]
Thank you for reporting this issue. We are working on it. I close this issue to track everything here: #1257

**Comment by Didayolo** [comment]
The problem should be solved one. One compute worker in the queue was ill.
