### ISSUE TITLE
Error Bad Gateway

### ISSUE THREAD

**Issue by saharzeltzer** [codalab/codabench#1279]
Hey,
I am trying to connect to the website but i get an error of : "Bad Gateway".
Are you familiar with it ?

Thanks,
Sahar

**Comment by bbearce** [comment]
Sahar,

We had a momentary issue this morning pulling fresh code changes into production. If you could bear with us we would greatly appreciate it.

**Comment by ihsaan-ullah** [comment]
Codabench is up now: https://www.codabench.org/
