### ISSUE TITLE
Improve the error messages for full user storage (quota)

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1280]
- [x] When trying to upload a submission with no user storage left, we simply get the following message:

<img width="351" alt="Capture d’écran 2024-01-18 à 06 42 38" src="https://github.com/codalab/codabench/assets/11784999/8fecb9a0-577c-4623-b752-95b6a30d8d8b">

We need a message similar to the one we get when trying to upload a bundle (see below) (#1293).

- [x] Add a link to "Resources" in the error message when uploading a bundle with full quota (#1293):

<img width="597" alt="Capture d’écran 2024-01-17 à 16 11 46" src="https://github.com/codalab/codabench/assets/11784999/255df6df-6172-40b6-863d-bcca9a8ccf1e">

**Comment by Didayolo** [comment]
The storage quota can be seen in the "Resources" page (https://www.codabench.org/tasks/):

<img width="1203" alt="Capture d’écran 2024-01-18 à 06 47 10" src="https://github.com/codalab/codabench/assets/11784999/e6305a49-c0e5-42a8-ac4a-f7d611ebf7e7">

**Comment by bbearce** [comment]
Added the response message as we have it readily available. Also after 5 second delay added a warning colored message (yellow) to link participants to the resources tab "/tasks".

![image](https://github.com/codalab/codabench/assets/7649007/a8e83c6c-a4d3-40ac-9438-acfb46c6bf3c)

![image](https://github.com/codalab/codabench/assets/7649007/e2136c53-5748-4e3f-b0bf-99bfc77b6dc4)

**Comment by Didayolo** [comment]
Nice.

I tried to add a clickable link in the main message, it worked for the "notification" message when uploading a submission, but not for the bundle upload error:

<img width="632" alt="Capture d’écran 2024-01-23 à 15 01 44" src="https://github.com/codalab/codabench/assets/11784999/68835f37-3d3e-4563-915d-063853d87a79">

I simply updated the error messages to solve the other point of this issue.
