### ISSUE TITLE
[New Feature] Toggle Auto-run submissions

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1281]
Provide a toggle option to organizers in competition settings, to enable/disable auto-run submissions.

- By default auto-run submissions will be enabled
- When this is disabled, all submissions submitted will have run submission button infront of them and by clicking this button, organizers can run the submission.

**Comment by Didayolo** [comment]
I do not understand. When the auto-rerun going to be triggered?

**Comment by ihsaan-ullah** [comment]
by default now we have auto-run which means that when you submit a submission it is added to the queue. When you turn this off (in this feature) then organizer can manually run it
