### ISSUE TITLE
Submission error

### ISSUE THREAD

**Issue by starsholic** [codalab/codabench#1282]
Dear Dr ihsaan, @ihsaan-ullah 

After the maintenance, the submission cannot be uploaded and shows“creation failed, error occured”.
<img width="459" alt="截屏2024-01-18 11 15 06" src="https://github.com/codalab/codabench/assets/52476332/1eb832fb-9f8b-4bd6-83dd-0b2e4ecf0841">

The competition submission portal is https://www.codabench.org/competitions/1772/#/participate-tab

Thanks!

**Comment by Didayolo** [comment]
Hi @starsholic,

I think it is because your quota storage is full. See:

- #1280

You can see your quota in the "Resources" page (https://www.codabench.org/tasks/):

<img width="1203" alt="Capture d’écran 2024-01-18 à 06 47 10" src="https://github.com/codalab/codabench/assets/11784999/e6305a49-c0e5-42a8-ac4a-f7d611ebf7e7">

I close this issue to track the bug on #1280. Feel free to add suggestions there.

**Comment by starsholic** [comment]
Hi @Didayolo ,

Thanks for your reply! The quota is not shown as below. And I think is not the bug reason since after I delete the unused submissions (pretty sure the quota is not full), still meet the same bug I have reported.

<img width="1167" alt="截屏2024-01-18 13 59 18" src="https://github.com/codalab/codabench/assets/52476332/986a3a44-b03b-4f30-9b8d-3a8c70669e15">

**Comment by ihsaan-ullah** [comment]
@starsholic I just submitted a submittions to your competition and it was successful. Maybe hard refresh your window (mac: command + shift + R) and try to resubmit
<img width="1183" alt="Screenshot 2024-01-18 at 11 33 09 AM" src="https://github.com/codalab/codabench/assets/13259262/9f1ccca7-961d-4ba0-a784-68aab5f3f1b6">

**Comment by ihsaan-ullah** [comment]
> BTW, it is weird that simply re-open the browser or website cannot work.

Can you please explain this point

**Comment by Didayolo** [comment]
@starsholic, yes, I think the browser tries to use cache as much as possible. By hard refreshing, you force it to not use the cache.

**Comment by starsholic** [comment]
Got it, thanks! :)
