### ISSUE TITLE
Add thumbnail logo to competitions to increase loading speed of the list

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1290]
Following #1173. The competitions list page is slow to load:

https://www.codabench.org/competitions/public/?page=1

This is because the logos of the competitions can be big images. We load all images just to display small thumbnail (e.g. 200 x 200 pixels).

A possible solution is to save a new attribute `competition.logo_small`, during unpacking of bundle, with a resized version of the logo. This thumbnail logo would be used in the competition list page.

**Comment by bbearce** [comment]
[https://github.com/codalab/codabench/pull/1306](https://github.com/codalab/codabench/pull/1306)
