### ISSUE TITLE
Repo social image

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1296]
Prepare and upload a repo social image in the repo settings

<img width="511" alt="Screenshot 2024-01-24 at 8 28 06 PM" src="https://github.com/codalab/codabench/assets/13259262/dbcf263e-0375-435a-8fbc-5d890362c0de">

**Comment by ihsaan-ullah** [comment]
Uploaded
![repository-open-graph-template (1)](https://github.com/codalab/codabench/assets/13259262/f21d70f1-6d40-497f-8079-bd3f1734e1ea)

**Comment by Didayolo** [comment]
@ihsaan-ullah 

Nice job. I think it would be interesting to add this image to the code of the platform, so it is also displayed when sharing the URL of the platform.

<img width="344" alt="Capture d’écran 2024-01-26 à 19 12 23" src="https://github.com/codalab/codabench/assets/11784999/597a0a85-85da-4572-b24f-c37ce221c604">

Also, this is a version with more explicit information:

![codabench_preview](https://github.com/codalab/codabench/assets/11784999/236fefcd-e041-4084-b03b-913c38f4eaad)

**Comment by ihsaan-ullah** [comment]
yes, this is mentioned in this issue #1050

**Comment by ihsaan-ullah** [comment]
Image updated

<img width="526" alt="Screenshot 2024-01-28 at 8 42 46 PM" src="https://github.com/codalab/codabench/assets/13259262/a9085fec-f0ec-4160-a4e6-2b9f272e45e3">
