### ISSUE TITLE
Delete submission problem

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1300]
### Delete Orginal

Submission 37 is a rerun of submission 36

When I delete 36(original), 37(rerun) is automatically deleted.
<img width="1051" alt="Screenshot 2024-01-28 at 2 42 51 PM" src="https://github.com/codalab/codabench/assets/13259262/50ccad19-a711-4f0e-835f-66c2d15d00e8">

### Delete Rerun

Submission 39 is a rerun of submissions 38

When I delete 39(rerun), 38(original) is also deleted
<img width="1044" alt="Screenshot 2024-01-28 at 2 57 51 PM" src="https://github.com/codalab/codabench/assets/13259262/c7d44bdd-009e-49d3-9bfe-7acd452c3662">

Is this supposed to happen?

**Comment by Didayolo** [comment]
Nice catch.
