### ISSUE TITLE
Number of submissions per day (apparently) is not reseting

### ISSUE THREAD

**Issue by juliojj** [codalab/codabench#1303]
Hi,
our group is organising a challenge https://www.codabench.org/competitions/1822 and apparently the number of submissions per day is not being reset for some users. I didn't find a way of checking this variable with respect to other participants. I am opening this issue as we receive the following message through the forum of our challenge:

"It seems that the submission count per day is not resetting in my case. Despite not having made any submissions thus far, I noticed that I began with a count of 5 submissions delivered."

For the moment, I will increase the number of submissions per day, as we are at the development phase. But would be great if you could check the issue. Thanks

**Comment by Didayolo** [comment]
Hi @juliojj 

Could you provide more information about the user who experienced the bug? What is their username? Do other people reported a problem?

**Comment by juliojj** [comment]
Hi @Didayolo 
the user is "dfreire". I have just asked him/her to check if the problem persists. I increased the submissions per day to 99 and any participant achieved such limit yet (this is why any other participant complained, in case the problem persist). I will let you know when I get a reply from this participant so that you can check, if needed/possible, why the submission counter was not reseting.
Thanks and best

**Comment by ihsaan-ullah** [comment]
I have checked this and it works fine. If you have daily limit of 5 submissions, it resets the next day.

**Comment by juliojj** [comment]
Thanks @ihsaan-ullah.
