### ISSUE TITLE
migrate from codalab to codabench

### ISSUE THREAD

**Issue by carandraug** [codalab/codabench#1312]
My impression is that, despite the name change, codabench is effectively codalab v2.

We've been running our own public instance of codalab version 1.5. How can we upgrade to version 2? I couldn't find any documentation about it.

**Comment by ihsaan-ullah** [comment]
Hi @carandraug 

You can find the documentation here: https://github.com/codalab/codabench/wiki/Codabench-Installation

**Comment by carandraug** [comment]
Hi @ihsaan-ullah . Thank you for the answer but I still have doubts.  Apologies if I was not clear on the initial question. I have a codalab v1.5 installation and I want to migrate to v2/codabench, .i.e., migrate previous competitions, leaderboards, etc.

The documentation says how to make a new installation but I want to upgrade (without losing previous competition data).

**Comment by ihsaan-ullah** [comment]
> Hi @ihsaan-ullah . Thank you for the answer but I still have doubts. Apologies if I was not clear on the initial question. I have a codalab v1.5 installation and I want to migrate to v2/codabench, .i.e., migrate previous competitions, leaderboards, etc.
> 
> The documentation says how to make a new installation but I want to upgrade (without losing previous competition data).

@acletournel @Didayolo any comments about this?

**Comment by carandraug** [comment]
> However, there are significant differences. I don't see how the database, the competitions with scores and submissions, etc. could be transfered from a CodaLab instance into a Codabench instance.
> 
> In my opinion, the only way to go is to create a new server. You can re-upload the important competitions and submissions from scratch. Regarding user accounts, it may be possible to transfer them. Maybe you could recreate the accounts automatically using a script or something. Still a bit tricky.

Typically, projects provide psql upgrade sql scripts to migrate from one version to another (one way only). Realistically, this can only be provided by the people developing said software as they are the only ones aware of the differences between the database schemas.

On that topic, can you clarify the state of codalab and codabench. If codabench is v2 of codalab, what will happen to development of codalab? Is there a reason to use codalab or is codabench missing some features of it?

**Comment by ihsaan-ullah** [comment]
> Typically, projects provide psql upgrade sql scripts to migrate from one version to another (one way only). Realistically, this can only be provided by the people developing said software as they are the only ones aware of the differences between the database schemas.
> 
> On that topic, can you clarify the state of codalab and codabench. If codabench is v2 of codalab, what will happen to development of codalab? Is there a reason to use codalab or is codabench missing some features of it?

Dear @carandraug Codabench is an independent platform from CodaLab and has more advanced features. We are not planning to shutdown CodaLab and it will stay active in parallel with Codabench. We recommend users to move to Codabench for new features but you can stay on CodaLab and use it for your future competitions. If we decide to merge CodaLab with Codabench in the future, we will surely migrate all the competitions to Codabench.

**Comment by carandraug** [comment]
To clarify, when you say Codalab and codabench, do you mean the software or do you mean the services running at codalab.org and codabench.org? Because I'm only asking about the software (as I mentioned before, we are running our own codalab instance at https://zeus.robots.ox.ac.uk/competitions/competitions/ )

> Dear @carandraug Codabench is an independent platform from CodaLab and has more advanced features. We are not planning to shutdown CodaLab and it will stay active in parallel with Codabench. We recommend users to move to Codabench for new features but you can stay on CodaLab and use it for your future competitions. If we decide to merge CodaLab with Codabench in the future, we will surely migrate all the competitions to Codabench.

You say that but from the outside, what one sees is:

1) codabench announced as [next-generation codalab](https://groups.google.com/g/codalab-competitions/c/YDNMWYd-RME?pli=1)
2) codabench being developed by roughly the same developers as codalab
3) codalab getting very little updates - I'm not talking about new features, I'm talking about not upgrading its increasingly out of date dependencies (e.g., django 1.11 is unsupported by upstream since April 2020 - that's almost 4 years ago)

The choice of developing codabench instead of improving codalab looks, again from the outside, that you decided that codalab was too hard to work with and so started fresh with codabench. That path is typically followed by abandoning the old version. Honestly, the appearance of abandonment of codalab (the software in github) already looks like that.

The fact that you don't, and apparently can't, provide a path for codalab to codabench migration is very worrying. Anyone installing codalab now will be stuck on it for years.

**Comment by Didayolo** [comment]
@carandraug CodaLab is mostly a community open-source project. If you can, or know anyone that can develop such upgrading process, we'll be happy to work together.

However, there are many differences between the two platforms in their internal functionning, which makes such upgrading particularily tricky in my opinion.

A solution could be to develop at least a way to transfer the user account, without data, competitions and submissions. This way you (and other platform providers) could start a fresh Codabench install with your previous users. CodaLab server could still remain running the older competitions, and Codabench would be used for newer competitions.

In the meantime, note that we continue to maintain CodaLab in parallel to Codabench, but indeed the efforts are lowered as it is very time consuming. Please also note that we have no more than 3 developers, none of them full-time, working on the project. Once again, we're happy to welcome any contributors to the project!
