### ISSUE TITLE
Codabench down?

### ISSUE THREAD

**Issue by sgsellan** [codalab/codabench#1318]
Trying to open www.codabench.org as of right now returns errors on both safari and Chrome, on different connections and machines. Is this a planned outage?

<img width="946" alt="Screenshot 2024-02-09 at 9 28 00 AM" src="https://github.com/codalab/codabench/assets/30415788/3600ff7e-770e-4549-86b1-babcfe63fbe4">
<img width="838" alt="Screenshot 2024-02-09 at 9 28 06 AM" src="https://github.com/codalab/codabench/assets/30415788/36827b84-30e9-43ca-9bd6-6d9e55e9e7a5">

**Comment by ihsaan-ullah** [comment]
Hi @sgsellan there is some maintenance going on. It will be available soon.

**Comment by sgsellan** [comment]
Thank you for responding so quickly!

**Comment by acletournel** [comment]
Codabench is back. Sorry for inconvenience.
