### ISSUE TITLE
Delete files 

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1319]
# Resources page
When we use the buttons in the cleanup section, the following are not deleted from minio
- submissions
- datasets/programs

# Competition deletion
When you delete a competition, the following files are not deleted:
- **logo**
- public_data
- input_data
- reference_data
- starting_kit
- ingestion_program
- scoring_program
- **competition dump**
- **competition bundle**
- **submissions**

and the following records are not deleted:
- tasks
- datasets/programs

# To discuss:
What should be done which items do we want to delete and which we don't *(in which conditions)

**Comment by Didayolo** [comment]
Related: #713

**Comment by Didayolo** [comment]
Any file that is removed from DB but kept in the MinIO, becoming an orphan file, should be erased.

**Comment by Didayolo** [comment]
I close this issue to keep track only in #713
