### ISSUE TITLE
Number of entries includes failed submissions

### ISSUE THREAD

**Issue by curious-broccoli** [codalab/codabench#1326]
In the leaderboard the number of entries counts all submissions by a participant, even the failed ones. I think it should only show the ones that finished because only those matter on the leaderboard.
The current behavior means that you could have a total limit of submissions for a phase while the leaderboard shows that more submissions than the limit allows were submitted.

**Comment by ihsaan-ullah** [comment]
@curious-broccoli can you please share a screenshot of your submissions page with this problem.

@Didayolo do we want to exclude failed submissions?

**Comment by curious-broccoli** [comment]
showing 5 successful submissions exist
![image](https://github.com/codalab/codabench/assets/77789413/e3c45612-e79d-4ff4-a887-251cdbaa2585)

showing that 8 submissions were submitted by test1
![image](https://github.com/codalab/codabench/assets/77789413/0508430d-7993-4fbd-8621-06a481c9c757)

**Comment by ihsaan-ullah** [comment]
Thank you reporting and sharing details. We will look into it soon

**Comment by Didayolo** [comment]
Hi @curious-broccoli, thank you for the suggestion. I think it is a good idea indeed.
