### ISSUE TITLE
Wrong privacy policy link in email

### ISSUE THREAD

**Issue by curious-broccoli** [codalab/codabench#1338]
The link https://codalab.org/codalab/notices.html at the end of the email templates leads to a 404.

**Comment by ihsaan-ullah** [comment]
Hi @curious-broccoli, you can report this to the codalab repository here: https://github.com/codalab/codalab-competitions/issues

**Comment by curious-broccoli** [comment]
but it is the codabench email...

**Comment by ihsaan-ullah** [comment]
Sorry for the confusion, we will correct it
