### ISSUE TITLE
View Profile and Edit Profile button returns 404 erros

### ISSUE THREAD

**Issue by magrichard** [codalab/codabench#1346]
I have an 'old' codabench account (id DT1, email magali.richard [at] univ-...) that is related to my main email address. 
When I try to edit this profile, it returns a 404 error. 
The account is still active though, I can login and create competition. 
Would it be possible to switch on profile edition access for my account ?

Thank you very much

**Comment by ihsaan-ullah** [comment]
I cannot see this user profile but others are accessible

NOT Accessible
https://www.codabench.org/profiles/user/DT1/

Accessible
https://www.codabench.org/profiles/user/ihsaan-ullah/

**Comment by magrichard** [comment]
Thank you ihsaan for your quick answer.
Yes I know that the issue is related to my profile. I have 2 accounts, one is accessible (https://www.codabench.org/profiles/user/magrichardtest/), the other (DT1) is not. 
However DT1 is a valid login, I can access to codabench with it and make submissions. What is weird is that I am identified as a bot (see below). I created this account in 2020, during the first steps of development of codabench. I could eventually abandon it, however it would block my email for further use, which annoys me.
![Capture d’écran 2024-02-28 à 15 52 00](https://github.com/codalab/codabench/assets/18577578/a87f4190-e14e-4d86-9c95-f316941fa30a)

**Comment by ihsaan-ullah** [comment]
Hi @magrichard, I think we can solve your problem.

I just checked locally and I cannot create a user with username `DT1`. Now we have a restriction that username should be lowercase. But if a user is bot, the profile is still accessible.

To verify if this is caused by capitalized username, @Didayolo the following will get us users with problematic usernames

```
docker-compose exec django bash
python manage.py shell_plus
users_not_lowercase = User.objects.exclude(username__regex=r'^[a-z]+$')
for user in users_not_lowercase:
    print(user.username)
```

Possible fix : convert username to lowercased letters e.g. `dt1`

**Comment by Didayolo** [comment]
Only old usernames can have capital letters and symbols because we updated the rules for sign up.

We have just sanitized the old usernames to make them lowercase and without symbols. The "view profile" page should be working fine now for all users.

@magrichard Your username is now "dt1".
