### ISSUE TITLE
TLS certificates don't persist

### ISSUE THREAD

**Issue by curious-broccoli** [codalab/codabench#1349]
### "Problem" with hosting own instance

As stated [in the wiki](https://github.com/codalab/codabench/wiki/Administrator-procedures#warning-restart-codabench-stack-warning) caddy requests a new certificate because the caddy data isn't persisted through restarts. Is this behavior intended? Because it shouldn't be much work to make the data persist. I think the issue is that the target location of the bind mount at https://github.com/codalab/codabench/blob/ee8cdbcfb166d43ed5137c0c2b8897426091d836/docker-compose.yml#L14 points to the wrong location and an environment variable should be set so that it works, as stated in the [caddy container's instructions](https://github.com/abiosoft/caddy-docker?tab=readme-ov-file#saving-certificates).

On my fork I also upgraded to Caddy 2 but the change to make it persist was to simply fix the bind mount location (https://github.com/curious-broccoli/codabench/commit/d8114bfe3a009827384f3182ded91e365e80d7a5) and it seems to work.

**Comment by Didayolo** [comment]
Thank you for reporting this. I think we had issues with this in the past, especially when we were restarting the server multiple times we encountered issue obtaining a Let's Encrypt certificate.

I thought this was resolved. At least, I think we changed the server configuration to avoid this problem on our setups.

We'll have a look at it. Thank you for the proposed fix.

**Comment by ihsaan-ullah** [comment]
@curious-broccoli why have you replaced `./certs/caddy:/etc/caddycerts` by `./certs:/data`

In the caddy [documentation](https://github.com/abiosoft/caddy-docker?tab=readme-ov-file#saving-certificates) they are using `/etc/caddycerts`

**Comment by curious-broccoli** [comment]
Uh, the commit I linked is for the [official caddy 2 image](https://hub.docker.com/_/caddy) that I use on the fork.

The `/etc/caddycerts` is fine to use, but that example requires setting the environment variable to work.
```
CADDYPATH=/etc/caddycerts
```
as stated in the part of the docs you linked. So I think you just gotta set that.
Sorry for any confusion.

**Comment by Didayolo** [comment]
@ihsaan-ullah In conclusion, do we merge or close #1360 ?
