### ISSUE TITLE
Admins can bypass submission limit

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1354]
Admins can rerun submissions which are counted for the original user who submitted. This way submissions can go over the allowed submissions

<img width="646" alt="Screenshot 2024-03-06 at 4 42 40 PM" src="https://github.com/codalab/codabench/assets/13259262/9e41a2d0-3262-4ea9-85a8-e6067e79e96b">

Not sure if this should be allowed

**Comment by Didayolo** [comment]
Are you refering to **competition organizers** or to **platform admins**?

In any case, I am not sure that this is a problem.

**Comment by bbearce** [comment]
My codabench is out of date so I'm not 100% sure if this is a problem in the main branch or dev branch but as a guest (non admin) I can submit past daily and total limits:
![image](https://github.com/codalab/codabench/assets/7649007/7edd9854-65f0-4983-bb6f-b7c923024f3f)

We plan to update our platform soon and can let you know how that goes and if the problem persists.
