### ISSUE TITLE
Rerun submission goes to default queue

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1357]
Our compeittion is using a custom queue but when anyone reruns a submission, it goes to default queue (or it is displayed as default queue)

I submitted the original submission then 3 admins tried to rerun (ihsan, ragansu, fair) but the queue shown is default

<img width="1135" alt="Screenshot 2024-03-06 at 5 54 05 PM" src="https://github.com/codalab/codabench/assets/13259262/f23ff774-331a-4b29-80fa-39dcf2606cc4">

**Comment by Didayolo** [comment]
Can you confirm that it is actually sent to the default queue and not just shown this way in the server status page?

**Comment by ihsaan-ullah** [comment]
I am not sure how to confirm that. Is there a way to visualize the queue?

**Comment by Didayolo** [comment]
Not that simple indeed. I think the simplest way is, once the submission has run, to check the hostname and connect to the worker to see trace of the submission. I have access to the worker so we can do this together.

**Comment by ihsaan-ullah** [comment]
Closing this as there is another duplicate issue
