### ISSUE TITLE
Submission time shown in UTC

### ISSUE THREAD

**Issue by curious-broccoli** [codalab/codabench#1359]
Enhancement idea:

I think it would be better if the submission date showed the time in local time and not in UTC, primarily on "My submissions" and "Results" tab.

**Comment by ihsaan-ullah** [comment]
Indeed all times should be in local timezone of the users seeing them

**Comment by curious-broccoli** [comment]
You mean that is the current expected behavior?

**Comment by ihsaan-ullah** [comment]
no, right now we only use UTC time, but changing it will be useful
