### ISSUE TITLE
Hide output files 

### ISSUE THREAD

**Issue by Exion35** [codalab/codabench#1361]
Hello everyone,

Is it possible to hide the files when clicking on the submissions (especially "Output from prediction step" and "Output from scoring step" because I do not want the file `scores.txt` to be accessible to the participants) ?

**Comment by curious-broccoli** [comment]
![image](https://github.com/codalab/codabench/assets/77789413/3b5f4b2f-9671-4190-95ba-71f307cadd2f)
this option when you edit a phase seems to do that

**Comment by Exion35** [comment]
I have tried this option already but it does not do what I want because it only hides the stdout/stderr, and not the files.

**Comment by curious-broccoli** [comment]
![image](https://github.com/codalab/codabench/assets/77789413/f43cf51b-7b57-4475-b5f6-d0ac9861b518)
have you tested it as a non admin (or organizer?) user?

**Comment by Exion35** [comment]
Ok that was it. Thanks a lot :)

**Comment by ihsaan-ullah** [comment]
Thaks a lot @curious-broccoli for the help

**Comment by Exion35** [comment]
I still have a small problem: I am trying to force this box to be checked in the `competition.yaml` file like this (with the `hide_output` argument):
![image](https://github.com/codalab/codabench/assets/78951592/ccd97400-8fa9-4225-881a-715b1c6e8c9c)

However, when going to Edit, I still don't see the box as checked. Do you have any clue on why it's not working as expected?

**Comment by ihsaan-ullah** [comment]
@Exion35 are you using `version: 2` in your yaml file?

**Comment by Exion35** [comment]
@ihsaan-ullah I was not. I added it and it fixed my problem. Thanks a lot :)
