### ISSUE TITLE
Quota filled 

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1364]
A user reported that his quota is filled but the submissions submitted are not 15 GB in total

more details in the email sent to info@...

**Comment by Didayolo** [comment]
@ihsaan-ullah Can you please add the details here? I can't find it.

If I recall correctly, the problem was simply that users can't remove submissions so they can get stuck with full storage quota (this problem is reported in #713).

**Comment by karimrochd** [comment]
![Screenshot from 2024-03-19 16-23-31](https://github.com/codalab/codabench/assets/122694748/795b3f33-4e58-4451-be9d-e380e14d4285)
![Screenshot from 2024-03-19 16-23-16](https://github.com/codalab/codabench/assets/122694748/7a6bce01-a107-4d78-a9c7-880d95da218d)
![Screenshot from 2024-03-19 16-23-54](https://github.com/codalab/codabench/assets/122694748/409929cd-f946-4111-b2eb-b80772011d76)
![Screenshot from 2024-03-19 16-23-58](https://github.com/codalab/codabench/assets/122694748/2262bfd9-fafb-4a38-a546-f47fd61e557f)
@Didayolo It's showing that i am using 14.7GB of my quota while the total of my submissions size is 8.2168GB

**Comment by Didayolo** [comment]
Indeed I can see the problem in your account.

**Comment by ff98li** [comment]
Hi @Didayolo ,

I'm also having the same issue. Not only is the quota filled, but the file sizes are also showing NaN...
<img width="1457" alt="Screenshot 2024-04-03 at 9 10 16 PM" src="https://github.com/codalab/codabench/assets/55061801/39677f4e-aa3f-44a4-ba56-134cb9174635">

<img width="1138" alt="Screenshot 2024-04-03 at 9 11 39 PM" src="https://github.com/codalab/codabench/assets/55061801/3ca99315-5c31-4f12-b400-8761e02c9fe6">

And when I try uploading new files, the "attachment" buttom doesn't respond:
<img width="909" alt="Screenshot 2024-04-03 at 9 14 46 PM" src="https://github.com/codalab/codabench/assets/55061801/bb558b98-c770-4efe-aa77-88edde3a08cb">

Any insights from the Codabench devs/admins will be very much appreciated.

**Comment by ihsaan-ullah** [comment]
@karimrochd do you remember if the quota was wrong from the start or it appeared this way after you deleted some of your submissions?

**Comment by karimrochd** [comment]
@ihsaan-ullah it was wrong before deleting any submission.

**Comment by Didayolo** [comment]
Related:

- #1388

**Comment by Didayolo** [comment]
@OhMaley 
What is remaining before closing this issue?

**Comment by OhMaley** [comment]
I think everything has be done ! We can close this issue
