### ISSUE TITLE
Hide some results in the 'scoring_result' or the file itself

### ISSUE THREAD

**Issue by johanneskruse** [codalab/codabench#1369]
Dear Codabench,

Thank you for providing this great platform.

I'm the organizer of this competition: https://www.codabench.org/competitions/2100/?secret_key=9e22f28e-e95a-42be-9de9-6884e6f0eca7 (this is just a dummy).

During the competition, I want to compute the metric scores based on 50% and 100% of the testset. However, I only want to show the results from the 50% testset during the competition. I can hide columns in the leaderboard, but the issue is that I cannot hide the output **scoring_result** file, hence, all results are visible to the users if they check it.

Is there a way to hide some of the output results from the user?

Best,
Johannes

**Comment by ihsaan-ullah** [comment]
Hi @johanneskruse 

In your competition settings, if you check `Hide Submission Output`, that would hide the output from participants

<img width="1054" alt="Screenshot 2024-03-21 at 2 02 36 PM" src="https://github.com/codalab/codabench/assets/13259262/b1ada4dc-57b7-47b4-9b3a-b3e0cfb7bd48">

**Comment by johanneskruse** [comment]
**Update**

As an admin of the competition, I'm still able to get the output files; however, as a participant, it seems to be hidden.
