### ISSUE TITLE
Problems after installation

### ISSUE THREAD

**Issue by johann-petrak** [codalab/codabench#1380]
Followed the instructions for quick setup under Linux (different machine from the attempt described in #1379) and this time the docker compose steps seemed to work fine. I used the current development branch (the default when cloning the repo).
However after completing all the steps, the web site does not work properly: the login screen does not show some of the graphic elements and the menu does not react at all.

On the log the following is shown:

```
jango-1          | Not Found: /static/css/calendar.min.css
django-1          | Not Found: /static/css/calendar.min.css
django-1          | Not Found: /static/js/calendar.min.js
django-1          | Not Found: /static/js/calendar.min.js
django-1          | Not Found: /static/js/ours/client.js
django-1          | Not Found: /static/js/ours/client.js
django-1          | Not Found: /static/js/ours/init.js
django-1          | Not Found: /static/js/ours/init.js
django-1          | Not Found: /static/js/ours/riotjs_mixins.js
django-1          | Not Found: /static/js/ours/riotjs_mixins.js
django-1          | Not Found: /static/js/ours/utils.js
django-1          | Not Found: /static/js/ours/utils.js
django-1          | Not Found: /static/js/jquery.form.serializer.js
django-1          | Not Found: /static/js/jquery.form.serializer.js
django-1          | Not Found: /static/js/Chart.bundle.js
django-1          | Not Found: /static/js/Chart.bundle.js
django-1          | Not Found: /static/js/reconnecting-websocket.min.js
django-1          | Not Found: /static/js/reconnecting-websocket.min.js
django-1          | Not Found: /static/generated/riot.js
django-1          | Not Found: /static/generated/riot.js
django-1          | Not Found: /static/js/ours/latex_markdown_html.js
django-1          | Not Found: /static/js/ours/latex_markdown_html.js
django-1          | Not Found: /static/generated/output.css
django-1          | Not Found: /static/generated/output.css
django-1          | Not Found: /static/img/Cha_Logo.png
django-1          | Not Found: /static/img/Cha_Logo.png
django-1          | Not Found: /static/js/calendar.min.js
django-1          | Not Found: /static/js/calendar.min.js
django-1          | Not Found: /static/js/ours/client.js
django-1          | Not Found: /static/js/ours/client.js
django-1          | Not Found: /static/js/ours/init.js
django-1          | Not Found: /static/js/ours/init.js
django-1          | Not Found: /static/js/ours/riotjs_mixins.js
django-1          | Not Found: /static/js/ours/riotjs_mixins.js
django-1          | Not Found: /static/js/ours/utils.js
django-1          | Not Found: /static/js/ours/utils.js
django-1          | Not Found: /static/js/jquery.form.serializer.js
django-1          | Not Found: /static/js/jquery.form.serializer.js
django-1          | Not Found: /static/js/Chart.bundle.js
django-1          | Not Found: /static/js/Chart.bundle.js
django-1          | Not Found: /static/js/reconnecting-websocket.min.js
django-1          | Not Found: /static/js/reconnecting-websocket.min.js
django-1          | Not Found: /static/generated/riot.js
django-1          | Not Found: /static/generated/riot.js
django-1          | Not Found: /static/js/ours/latex_markdown_html.js
django-1          | Not Found: /static/js/ours/latex_markdown_html.js
django-1          | Not Found: /static/img/favicon.ico
django-1          | Not Found: /static/img/favicon.ico
```

Is there a recommended way to set this up locally that works?

**Comment by ihsaan-ullah** [comment]
When you start the docker stack  
```docker-compose up -d```

you need to collect static files 
```docker-compose exec django ./manage.py collectstatic --noinput```

**Comment by johann-petrak** [comment]
BTW, I always got the following error on the `docker compose up` log:

```
caddy-1           | 2024/04/04 08:12:52 [ERROR] Sending telemetry: Post https://telemetry.caddyserver.com/v1/update/f035fec7-a3a1-42c5-9b62-16b83c26dab9: dial tcp: lookup telemetry.caddyserver.com on 127.0.0.11:53: no such host
rabbit-1          | 2024-04-04 08:14:21.033435+00:00 [error] <0.736.0> closing AMQP connection <0.736.0> (172.20.0.8:45074 -> 172.20.0.5:5672):
rabbit-1          | 2024-04-04 08:14:21.033435+00:00 [error] <0.736.0> missed heartbeats from client, timeout: 60s
rabbit-1          | 2024-04-04 08:14:22.703408+00:00 [error] <0.782.0> closing AMQP connection <0.782.0> (172.20.0.8:45084 -> 172.20.0.5:5672):
rabbit-1          | 2024-04-04 08:14:22.703408+00:00 [error] <0.782.0> missed heartbeats from client, timeout: 60s
```

**Comment by ihsaan-ullah** [comment]
Can you check if your localhost is `http://localhost/` (not https)

**Comment by ihsaan-ullah** [comment]
I think these two links will help

1. Opening ports: https://github.com/codalab/codabench/wiki/How-to-deploy-Codabench-on-your-server#open-access-permissions-for-following-port-number
2. Django configuration: https://github.com/codalab/codabench/wiki/How-to-deploy-Codabench-on-your-server#modify-django-related-configuration

**Comment by curious-broccoli** [comment]
simply localhost should work. localhost:8000 and http://127.0.0.1:8000/ also loads the page but without the static files I believe. I suppose it shouldn't load on port 8000 at all

**Comment by bbearce** [comment]
How is this going? Is this resolved?

**Comment by johann-petrak** [comment]
Thank you. I used http://localhost:8000 because I followed the instructions in the README.md file for quick Linux setup which state: "You can now login as username "admin" with password "admin" at http://localhost:8000"

When I instead use http://localhost (default port 80), it seems to work.  The only thing I notice is that the images/logos in front of each listed competition on the main page are not shown. The link to the image is shown as http://minio:9000/public/logos/2024-04-04-1712217063/c61c3a3610ee/example_icon.jpg which looks wrong to me. That logo is also not shown in the competition page as the same incorrect link is used. 

Ports 5672, 8000 and 9000 are open and unused on my server. 

I am actually a bit surprised that it works to have it run on port 80 by default because I would have thought that 80 is a protected port. This is also why I did expect the local web site to run on a higher port number in order to avoid any issues with protected ports? 

I guess the main issue here might be to figure out if what is statet in the README is incorrect or if accessing the web server on port 8000 should actually work or not?

**Comment by Didayolo** [comment]
The quick setup instructions have been updated after this: https://github.com/codalab/codabench/commit/992bd86c661b157fde9ef1ed94ab35276694eddc

I mark this issue as resolved.
