### ISSUE TITLE
Uploading a bundle to locally running server fails

### ISSUE THREAD

**Issue by johann-petrak** [codalab/codabench#1384]
After installing from the latest development branch following the quick setup instructions for Linux  in the README file and navigating to localhost (not localhost:8000) and logging in as adming, I tried to upload a bundle zip file that works on codabench.org without any errors. 

When I upload this to the local server I get a small popup window saying 
"Creation failed, error occurred" but no additional information what the error may be is shown. 

There is nothing shown on the log output I see in my console where I am running `docker compose up` either. 

I then tried with one of the published bundles: https://github.com/codalab/competition-examples/blob/master/codabench/wheat_seeds/code_submission_bundle.zip which gave the same error message

**Comment by ihsaan-ullah** [comment]
Can you check your django logs to see if something is there
```
docker compose logs -f django
```

**Comment by johann-petrak** [comment]
I ran `docker compose logs -f django` then tried the upload but nothing new was shown on that log.

**Comment by ihsaan-ullah** [comment]
maybe try without django to see all logs

```
docker compose logs -f
```

**Comment by johann-petrak** [comment]
I also did that, and only these messages get shown:
```
caddy-1           | 172.20.0.1 - - [05/Apr/2024:11:58:32 +0000] "GET /competitions/ HTTP/1.1" 200 3675
caddy-1           | 172.20.0.1 - - [05/Apr/2024:11:58:32 +0000] "GET /static/particles/header.json HTTP/1.1" 200 526
caddy-1           | 172.20.0.1 - - [05/Apr/2024:11:58:32 +0000] "GET /static/img/favicon.ico HTTP/1.1" 200 16958
caddy-1           | 172.20.0.1 - - [05/Apr/2024:11:58:32 +0000] "GET /api/competitions/?participating_in=true HTTP/1.1" 200 1168
caddy-1           | 172.20.0.1 - - [05/Apr/2024:11:58:32 +0000] "GET /api/competitions/?mine=true&type=any HTTP/1.1" 200 527
caddy-1           | 172.20.0.1 - - [05/Apr/2024:11:58:33 +0000] "GET /competitions/upload/ HTTP/1.1" 200 3674
caddy-1           | 172.20.0.1 - - [05/Apr/2024:11:58:34 +0000] "GET /static/particles/header.json HTTP/1.1" 200 526
caddy-1           | 172.20.0.1 - - [05/Apr/2024:11:58:34 +0000] "GET /static/img/favicon.ico HTTP/1.1" 200 16958
caddy-1           | 172.20.0.1 - - [05/Apr/2024:11:58:37 +0000] "POST /api/datasets/ HTTP/1.1" 201 255
```

After a longer while, these additional messages appeared, but they seem unrelated and happening rather frequently:
```
rabbit-1          | 2024-04-05 11:59:35.844648+00:00 [error] <0.6245.0> closing AMQP connection <0.6245.0> (172.20.0.8:55630 -> 172.20.0.5:5672):
rabbit-1          | 2024-04-05 11:59:35.844648+00:00 [error] <0.6245.0> missed heartbeats from client, timeout: 60s
```

**Comment by ihsaan-ullah** [comment]
lets try two more things:

1. check javascript errors. right click on the screen -> inspect -> click console -> upload the bundle and see any errors
2. hard refresh your browser window -> On mac: command + shift + R -> upload the new bundle

**Comment by curious-broccoli** [comment]
yeah I suspect this likely is a error with the minio connection, like wrong url or port

**Comment by johann-petrak** [comment]
If I check the Javscript console when trying to upload a code bundle zip file I see the following message appear:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://minio:9000/private/dataset/2024-04-09-1712663691/502353d0624c/code_submission_bundle.zip?AWSAccessKeyId=testkey&Signature=ixW7Wk7%2BgVRIncn4ZZpRD8kym%2F4%3D&content-type=application%2Fzip&Expires=1712750091. (Reason: CORS request did not succeed). Status code: (null).
```

This was done with the latest version of Firefox on Ubuntu Linux.

**Comment by ihsaan-ullah** [comment]
This is something related to your browser that blocks the request. There are some ways to enable cross-origin requests. Chrome has some extensions to allow this (not sure about Firefox)

**Comment by johann-petrak** [comment]
Why is it necessary to enable something that is apparently generally not needed? Is there no way to solve this so it works with standard browsers out of the box  without people having to use extensions or switch browsers? 
My feeling is also that increasingly browsers will make it hard to enable this because it is considered a security vulnerability, isn't it?

**Comment by curious-broccoli** [comment]
The request probably fails because your browser doesn't know what the domain minio is supposed to be. Did you edit the /etc/hosts as written in https://github.com/codalab/codabench/wiki/Codabench-Installation#3-edit-the-settings-env ? (this only works for testing locally)

**Comment by Didayolo** [comment]
Nice catch. I changed "http://localhost:8000" to "http://localhost/" and added links to the more detailed installation guides.

https://github.com/codalab/codabench/blob/develop/README.md
