### ISSUE TITLE
Rank is not sorted based on **Primary Column**

### ISSUE THREAD

**Issue by johanneskruse** [codalab/codabench#1389]
Hi, 

I'm hosting a competition, and for some reason the ranking are not sorted based on **Primary Column** (AUC*): 

![image](https://github.com/codalab/codabench/assets/43001334/987b03c5-b804-4948-af37-fc86800284ff)

Here's a link to the competition: 
- https://www.codabench.org/competitions/2469/?secret_key=98314b2c-9237-471e-905c-2a88bf6a1d8a

**Comment by Didayolo** [comment]
Thank you for reporting this problem.

Related issue:
- #1171
