### ISSUE TITLE
Small logo update when updating logo from editor

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1390]
when you update competition logo from the editor, the small logo is not updated. With this issue you always see the old logo in the competitions list page (public competitions)

**Comment by Didayolo** [comment]
Nice catch! 

@bbearce this is a fix needed on you feature, so I guess you would be the best candidate to implement it.

**Comment by ihsaan-ullah** [comment]
This is misreported. I don't see this problem
