### ISSUE TITLE
Number of participants not displayed in "Public benchmarks" list

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1415]
In https://codabench-test.lri.fr/competitions/public/?page=1 :

<img width="364" alt="Capture d’écran 2024-04-17 à 14 05 52" src="https://github.com/codalab/codabench/assets/11784999/c238ed1d-5fe9-4032-b028-53056bb23eed">

Related code:

https://github.com/codalab/codabench/blob/bade1eba4a49b4a6aea7bc39dc141e329d43081a/src/static/riot/competitions/public-list.tag#L38

**Comment by ryukaizen** [comment]
May I work on this?

**Comment by Didayolo** [comment]
@ryukaizen Yes, please go ahead 😊

**Comment by ihsaan-ullah** [comment]
@ryukaizen any update on this?
