### ISSUE TITLE
Submissions remaining in Running status

### ISSUE THREAD

**Issue by kmin940** [codalab/codabench#1418]
Hello, we would like to inquire about the submitted jobs remaining in Running Status.
Our challenge website [here](https://www.codabench.org/competitions/1847/).
We observed that for some participants the submission remains in the Running Status without any errors for longer than a few hours.

![image](https://github.com/codalab/codabench/assets/43990006/68d81c08-0f7e-40d4-b330-672d6eefdb74)

We downloaded one of the participants' results and tried running it using one of the organizers' accounts and it is not stuck and completes without any problem.
We would like to inquire what could be the reason and how we can resolve the problem, thank you.

**Comment by Didayolo** [comment]
Hi,

When this problem started? We just fixed a problem with the production environment.

Please inform us if the problem happens again on future submissions.

**Comment by Didayolo** [comment]
Someone else reported that this is indeed fixed. Feel free to report the problem if it happens again on your side.
