### ISSUE TITLE
Cannot create queue

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1419]
<img width="1239" alt="Screenshot 2024-04-19 at 11 53 19 AM" src="https://github.com/codalab/codabench/assets/13259262/89db7d4c-e9e1-48df-8787-34d0e642f41f">

**Comment by ihsaan-ullah** [comment]
Works on codabench test

**Comment by Didayolo** [comment]
I close the issue but that would be interesting to investigate it. Some submissions were stuck in "Running" too.
