### ISSUE TITLE
Submission upload not successful

### ISSUE THREAD

**Issue by kmin940** [codalab/codabench#1421]
Hello, we would like to inquire about job submitting process being suspended.

Our challenge website is [here](https://www.codabench.org/competitions/1847/).
For some participants, the upload process in the job submission is not successful and the progress bar is suspended and not proceed to the next step. 
![image](https://github.com/codalab/codabench/assets/43990006/86a8d48c-49ba-4dcd-8836-272ca9b39a85)

Could you please look into the problem?

Thank you for your support.

**Comment by ihsaan-ullah** [comment]
This may happen due to a recent update of Chrome. Can you ask the participants to use a different browser or update the current browser
