### ISSUE TITLE
Getting issue in evaluating submission in worker

### ISSUE THREAD

**Issue by surupendu** [codalab/codabench#1423]
Hi,

I am setting up the competition Machine Translation for Indian Languages @https://www.codabench.org/competitions/2889/

Since the default queue has a 600 second time limit, I switched to custom queue with remote worker.
The competition is result submission only.

So as per my understanding an ingestion program is not required.
However, the submission is not getting processed and throwing error given below:
![image](https://github.com/codalab/codabench/assets/8011126/d0db4b23-ef9b-49dc-a2d3-8da37f51d3da)

Please can you help with the issue as I am not able to solve it using the documentation

**Comment by ihsaan-ullah** [comment]
Can you please attach your yaml file here

**Comment by ihsaan-ullah** [comment]
Can you change your command to

```
command: python3 metrics.py
```
assuming metrics.py is your scoring program

**Comment by surupendu** [comment]
It is now not able to find the program
![image](https://github.com/codalab/codabench/assets/8011126/02ca6b09-cd4f-464f-bd7a-17e65ea6e906)

**Comment by surupendu** [comment]
Hi,

On further investigation of logs it seems that the codabench server interacts with the remote worker machine and tries to run the scoring code locally.

![image](https://github.com/codalab/codabench/assets/8011126/df8275e3-9785-4615-9726-ca92e1bc213e)

And may be due to security restrictions in the network the code does not get copied to the worker. Is my understanding correct?

**Comment by ihsaan-ullah** [comment]
I am not sure what is wrong there but you can check [this bundle](https://github.com/ihsaan-ullah/create_a_codabench_challenge/blob/master/result_submission_bundle.zip) which is results only competition and you can modify it to meet your needs and then submit a submission to see what happens

**Comment by Didayolo** [comment]
Hi @surupendu 

- Was the submissions working before on the default queue?
- Is there an actual problem with the scoring of submissions?

The `ingestion program not found` is a warning, not an error message. It is normal to receive it in case of result submission competitions.

**Comment by surupendu** [comment]
Hi @Didayolo 

Earlier due to the issue with the zipping of the scoring program at folder level, the evaluation was not working as the submission was getting timed out.

As I could not access the logs in the default queue, I switched to using remote worker queue where in the logs showed that it was searching for the ingestion program. Turns out I needed to zip the scoring program at a file level instead of folder level (based on solution provided by @ihsaan-ullah)
However now the remote worker started giving the issue that "metrics.py" not found in directory.

I switched to using the default queue and my submissions started working correctly.
The submissions are now using the default queue.

My only concern now is that if I switch to using a remote worker out of need for heavy computation then I will face the issue of scoring program not found, the error that I was getting earlier.

**Comment by Didayolo** [comment]
@surupendu @ihsaan-ullah 

It is absolutely not normal, and quite concerning, that the submissions works on the default queue but not on a custom queue.

This could indicate that recent changes made to the compute worker's code (#1408) are breaking something.

Indeed, the workers of the default queue are not up-to-date, while @surupendu is using the latest version of the code when creating the workers.

**Comment by ihsaan-ullah** [comment]
I have recently setup new workers on Google Cloud. I haven't any problem like this

**Comment by Didayolo** [comment]
Indeed. @surupendu Are you still experiencing problems?

**Comment by surupendu** [comment]
@Didayolo and @ihsaan-ullah thank you for the support.
I am now running the competition on default queue.
If I face any issue in custom queue I will share the logs with you.
We can close the issue for now.
