### ISSUE TITLE
Custom gpu-worker not able to detect GPU when scoring despite seeing gpu

### ISSUE THREAD

**Issue by justin13601** [codalab/codabench#1426]
I am trying to set up my own gpu worker to evaluate submissions. I have succesfully started a docker container and connected to my competition queue. It is able to receive submissions successfully, but when my scoring program tries to use cuda, I run into an error saying that "Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx".

I attached to the container and verified that drivers were installed and gpu is visible by verifying "nvidia-smi".

I can also set my torch device to be cuda inside the actual compute worker image. So, it seems like the evaluation script is being run inside the competition image, and is not able to communicate with the nvidia drivers on the compute image. Am I understanding this correctly?

Edit:
I'm thinking the issue is with this line of the docker run command for a gpu worker:
`    -v /var/lib/nvidia-docker/nvidia-docker.sock:/var/lib/nvidia-docker/nvidia-docker.sock \
`
As nvidia-docker is deprecated, I installed the nvidia-container-toolkit from their website instructions, and thus this volume would not be mounted corrected and probably why my competition image can't see my compute image drivers. How would I fix this?

**Comment by Didayolo** [comment]
Are you using the default competition docker image? You can check it and update it by manually editing your competition:

<img width="615" alt="Capture d’écran 2024-04-29 à 12 59 19" src="https://github.com/codalab/codabench/assets/11784999/96d3ea90-c838-4509-abab-96cf6efc9198">

You need to use a docker image which includes CUDA and other GPU libraries, such as `codalab/codalab-legacy:gpu`.

I added a note about this in the documentation.

**Comment by justin13601** [comment]
Thanks for the reply! Yes, I am indeed using the default image so will need to install CUDA and GPU libraries.

Just to check, do you mean to install the cuda toolkit, something like `conda install nvidia/label/cuda-12.1.0::cuda-toolkit`?

**Comment by justin13601** [comment]
It looks like I do have GPU libraries installed already... if I run the competition docker image using `sudo docker run -it --runtime=nvidia --gpus all <IMAGE> bash` . I am able to run nvidia-smi, and torch is able to see cuda. 

However, I'm guessing the issue is that while drivers are installed in the compute worker vm, the compute worker image, and competition image, there is a disconnect, possibly due to nvidia-docker not working? `/var/lib/nvidia-docker/nvidia-docker.sock` does not exist on my vm machine if that has to do with it - does that make any sense?

**Comment by ihsaan-ullah** [comment]
You can build your own image using a dockerfile similar to this one. This image will have cuda pre-installed

Dockefile: [Dockerfile.txt](https://github.com/codalab/codabench/files/15152885/Dockerfile.txt)

Rename `Dockerfile.text` to `Dockerfile`

**Comment by Didayolo** [comment]
Any update? I close this issue as it is competition specific and staling, but feel free to pursue the discussion if needed.
