### ISSUE TITLE
Number of Submissions not updated

### ISSUE THREAD

**Issue by kmin940** [codalab/codabench#1427]
Hello, we would like to inquire about the number of submissions not being updated.

Our challenge website is [here](https://www.codabench.org/competitions/1847/).
For some participants, the number of submissions used for the day is not reset even after the previous submission day has passed.

![image](https://github.com/codalab/codabench/assets/43990006/fa9a173b-7cf7-4080-83eb-a20b0dc4ecb4)

Could you please look into the problem?

Thank you for your support.

**Comment by ihsaan-ullah** [comment]
Please provide more details:
- Which participants are experiencing the issue
- When have they submitted their last submission

**Comment by ihsaan-ullah** [comment]
The allowed number of submissions cannot be increased for a single participant. If you change it, it affects all the participants. By the way Cancelled/Failed submissions are not counted in the limit

**Comment by kmin940** [comment]
I see, thank you for your reply! Could the problem of jobs being getting stuck be resolved? Thank you.

**Comment by ihsaan-ullah** [comment]
Please share the IDs ofsubmission which are stuck. We will check them. Please also mention the queue name from your competition settings

**Comment by kmin940** [comment]
Thank you for your reply! The job IDs still in running status are as follows:
57960
57957
57947
57830
57795
57764
57761
57742
For the queue name, could you please let me know how to view the queue name? Currently in the Queue Management, there is no Queues.
![image](https://github.com/codalab/codabench/assets/43990006/f3ebf8a6-21a7-4069-b5ed-1cf83407b68d)
![image](https://github.com/codalab/codabench/assets/43990006/fbc1a859-86db-44a1-bf2f-61786134c02f)
![image](https://github.com/codalab/codabench/assets/43990006/ec3638ee-8c73-4e5a-ae0b-604ed910424e)
![image](https://github.com/codalab/codabench/assets/43990006/b8636891-8829-427d-afa9-ac12f76dfe37)
![image](https://github.com/codalab/codabench/assets/43990006/894158c6-2d86-4cf8-a153-ae8c942d3557)

**Comment by kmin940** [comment]
Hello, 

Below are the details for the issue of the number of submissions not being reset.

Codabench Username of the participant: dknguyen176
On April 29th, the number of submissions was reset from 6 to 3 and the participant submitted three times to get to "6 out of 6".
Today at 0:00 UTC, it's reset to "3 out of 6" again.

The job ID of the submissions are 57998, 57955, and 57860.
![image](https://github.com/codalab/codabench/assets/43990006/c575844f-6e8f-424b-9903-3ff942bada5d)

Thank you for your consideration!

**Comment by ihsaan-ullah** [comment]
I think there is a confusion in understanding this feature. I think you expect that at 00:00:00 submissions should reset but I think it resets individually for each participant i.e. for this participant it will reset on 2024-04-30 04:15.

**Comment by kmin940** [comment]
Thank you very much for your swift reply! I see, thank you for your answer!
May I ask one last question? I think most of the jobs are in finished status, but for the following participant with job ID 57960, the status is still in running status. 
![image](https://github.com/codalab/codabench/assets/43990006/35f45cd8-b4aa-4fe4-8ff4-6bbec8502e9c)

I appreciate your continued support.

**Comment by ihsaan-ullah** [comment]
I think this submisison has some problem. @Didayolo can check problems with these stuck submissions in Running state.

- 57960
- 57957
- 57947
- 57830
- 57795
- 57764
- 57761
- 57742

**Comment by kmin940** [comment]
I see, understood! Thank you very much for your time and support.

**Comment by ff98li** [comment]
> I think there is a confusion in understanding this feature. I think you expect that at 00:00:00 submissions should reset but I think it resets individually for each participant i.e. for this participant it will reset on 2024-04-30 04:15.
> 
> In summary: if you submit a submission on January 01 at 10 AM, your submissions limit will reset on January 02 at 10 AM. If you think this is not happening, please let us know

Hi Ihsan, thanks a ton for the detailed explanation! On top of this example, I have an additional question. Let's say if the participant had made separate submissions at 10:00 AM, 10:15 AM and 10:30 AM on January 1st (out of 6 daily quota), then would the daily submission quota reset to 2 at 10:00 AM on January 2nd, and then 0 at 10:30 AM, i.e. the daily limit is reset individually for each submission of that participant?

**Comment by hieplpvip** [comment]
Hi! I'm the user in the original post. The submission limit is still not reset for me.

The last submission I made was more than a day ago:

![image](https://github.com/codalab/codabench/assets/17219541/be5c2426-f77b-4792-b81d-e057bdb14e2b)

Yet the limit is now "4 out of 6":

![image](https://github.com/codalab/codabench/assets/17219541/53f012c1-44e9-46ea-b96f-be883acca9cc)

My username is dknguyen176

**Comment by Didayolo** [comment]
I merge this issue with #1469 to keep track of it in one place.
