### ISSUE TITLE
Typo in dropdown ("organizaiton")

### ISSUE THREAD

**Issue by tmills** [codalab/codabench#1431]
https://github.com/codalab/codabench/blob/992bd86c661b157fde9ef1ed94ab35276694eddc/src/static/riot/competitions/detail/submission_upload.tag#L64

Should be "organization"

**Comment by Didayolo** [comment]
Nice catch, fixed by https://github.com/codalab/codabench/commit/30faa9e13c9d8973e8b8d7cf7f058c041c0af765
