### ISSUE TITLE
Files tab is always there

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1439]
We want to hide the files tab when there are no files

<img width="267" alt="Screenshot 2024-05-10 at 10 21 35 PM" src="https://github.com/codalab/codabench/assets/13259262/9a866ad2-df06-4231-b1e6-71a3a9df3d2e">
<img width="1254" alt="Screenshot 2024-05-10 at 10 21 39 PM" src="https://github.com/codalab/codabench/assets/13259262/301870c4-0cc9-441d-84b4-e01d1d4d09af">

**Comment by Didayolo** [comment]
Is this really useful? Maybe it is more confusing if it is hidden

**Comment by johann-petrak** [comment]
I would find that VERY useful. Our participation rules show a download location which is much easier to mainting via git, so the Files tab is empty and I think having the empty tab is then actually more confusing as it could make some people believe there are no files yet, when actually the download location is explained in the participation text.

**Comment by Didayolo** [comment]
@bbearce I assign you to this enhancement if that works for you. It should be quite straightforward to develop.
