### ISSUE TITLE
NAN size 

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1440]
In submissions tab, I see some submissions with NAN size

<img width="821" alt="Screenshot 2024-05-12 at 10 42 21 AM" src="https://github.com/codalab/codabench/assets/13259262/55ab7c2e-8589-46a7-a263-c25fa398daf8">

**Comment by ihsaan-ullah** [comment]
Another user reported this

![image](https://github.com/codalab/codabench/assets/13259262/9abfcaba-d46e-4436-b437-3674a95a9168)

**Comment by OhMaley** [comment]
Ihsaan and I are not able to reproduce the bug.
Shall we close this issue?

**Comment by ihsaan-ullah** [comment]
Closing this for now. We can handle this if this happens again
