### ISSUE TITLE
Submission upload fails if filename is too long

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1444]
A participant reported this

<img width="760" alt="Screenshot 2024-05-17 at 2 09 10 PM" src="https://github.com/codalab/codabench/assets/13259262/23884062-7c7d-4c68-b6f9-e6bfb546d9f0">

**Comment by Didayolo** [comment]
I tried uploading a submission with a filename starting with `_` and it worked without problem.
