### ISSUE TITLE
Codabench login

### ISSUE THREAD

**Issue by MLDeS** [codalab/codabench#1450]
Could not find a support link, hence raising an issue here, please pardon if I have missed relevant information. I signed up for Codabench a couple of days back but have not activated the account.

Now, when I try to log in, it says to activate account with given link. I tried doing, but the activation link has expired. If I try to sign up again, it says the account already exists with the email ID. I tried a forgot password, but since my account is not activated, the resent link is not sent to my email ID.

How should I resolve it?

Thanks!

**Comment by ihsaan-ullah** [comment]
Please send an email to info@codalab.org. Send from the email you have used to create account on Codabench.

**Comment by Didayolo** [comment]
I close this issue as its resolution will continue by email.
