### ISSUE TITLE
Email problems

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1460]
In the new email templates 

- we don't see the logo
- we see unsubscribe link/button BUT we don't have this functionality

<img width="606" alt="Screenshot 2024-05-29 at 9 49 35 PM" src="https://github.com/codalab/codabench/assets/13259262/c27718c8-545f-4e4b-abef-ecd1f2c79b22">

**Comment by Didayolo** [comment]
Indeed

**Comment by Didayolo** [comment]
https://github.com/codalab/codabench/pull/1453
