### ISSUE TITLE
Changing file_size value in Django admin interface is not working.

### ISSUE THREAD

**Issue by ObadaS** [codalab/codabench#1468]
Hello,

Changing the file_size value in the Django admin interface is not working when the value is 0 or less. While the page says that the value has been updated, going back into the objects page shows the original value instead of the updated one.

I checked the value in the database to make sure it's not just a graphical bug, but the value is unchanged there too.

It seems to only be a problem when the value is 0 or lower (it gets changed back to the original value).

Changing the value to something else higher than 0 works well, but putting 0 or less will change it back to the original value instead of the previous positive value.

**Comment by Didayolo** [comment]
What is the goal of manually changing the `file_size` using Django admin interface?

Shouldn't the file size always reflect the size of the file? I may be missing something here.

**Comment by ObadaS** [comment]
The goal is limited, I found this problem after trying to apply the Simple Test of #1465 

This is definitely not an important problem to fix, but I thought it would be interesting to at least have it documented, in case we might need to change the `file_size` manually in the future for some other reason.

**Comment by ihsaan-ullah** [comment]
Maybe we can close this issue.

I found that I can set values < 0 
<img width="401" alt="Screenshot 2024-07-14 at 10 32 09 AM" src="https://github.com/user-attachments/assets/8c39b622-4574-4dfb-b6eb-2edfd38590a5">


But for some reason when you set value to 0, it goes back to these values
<img width="424" alt="Screenshot 2024-07-14 at 10 31 43 AM" src="https://github.com/user-attachments/assets/3fd01e47-c741-4abc-ac77-5746b04f63cb">

**Comment by Didayolo** [comment]
I close this issue. @ObadaS feel free to re-open it if you think it is relevant.
