### ISSUE TITLE
Detailed results are visible in leaderboard for participants who are in pending for approval

### ISSUE THREAD

**Issue by liviust** [codalab/codabench#1475]
If you enable `Detailed Results` and enable it in the leaderboard as well, the users who did not register for the respective competition cannot see the `Detailed Results` tab. You'd get `You do not have permission to see the detailed result. Participate in this competition to view result`. 

However, if you just apply and stay in the `pending` status, you do not get the warning, and the results are visible.

**Comment by Didayolo** [comment]
Thank you for reporting the problem.

It seems also that, we revoking the access to the competition, the participant is still able to see the leaderboard and detailed results.
