### ISSUE TITLE
Competition dump doesn't include leaderboard's submission_rule

### ISSUE THREAD

**Issue by curious-broccoli** [codalab/codabench#1479]
(Running our own instance, which is a few commits behind.)

Dumping a competition doesn't seem to include the leaderboard's submission_rule.
This seems to be intended (for now), see https://github.com/codalab/codabench/blob/6ff1c4532679c59b1fdb20168ee728b9a7f42ae0/src/apps/competitions/tasks.py#L82-L91

**Comment by Didayolo** [comment]
Nice catch

**Comment by Didayolo** [comment]
I merge this with #1481
