### ISSUE TITLE
Competition dump missing settings

### ISSUE THREAD

**Issue by curious-broccoli** [codalab/codabench#1481]
(Running our own instance, which is a few commits behind.)

Competition dump does not include leaderboard's columns' precision and submission rule.

# No columns' precision

Dumping a competition doesn't seem to include the leaderboard's columns' precision.

https://github.com/codalab/codabench/blob/6ff1c4532679c59b1fdb20168ee728b9a7f42ae0/src/apps/competitions/tasks.py#L93-L101

# No submission rule

Dumping a competition doesn't seem to include the leaderboard's submission_rule.
This seems to be intended (for now), see https://github.com/codalab/codabench/blob/6ff1c4532679c59b1fdb20168ee728b9a7f42ae0/src/apps/competitions/tasks.py#L82-L91

**Comment by Didayolo** [comment]
Solved by #1525, should be deployed on production soon.
