### ISSUE TITLE
Solution Stuck on "Scoring" #1507

### ISSUE THREAD

**Issue by JasonMendoza2008** [codalab/codabench#1509]
Submission stuck on Scoring. It happens randomly. **I had to cancel last time after several hours but it counted towards my quota**. What can I do:
<img width="867" alt="image" src="https://github.com/codalab/codabench/assets/56092290/d86fddac-7fd7-4bb0-9030-311ba36e3425">

My username is jmendoza2008 on Codabench. I believe this issue might be related to https://github.com/codalab/codabench/issues/1507.

**Comment by Didayolo** [comment]
Closing this for now.
