### ISSUE TITLE
Remove Dockerfile.celery

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1511]
In #1416, the configuration was changed to use Poetry.

The file `Dockerfile.celery` was not updated. However, it seems that it is never used in the project.

@bbearce Any comment on this?

**Comment by ObadaS** [comment]
Looking through both `Dockerfile` and `Dockerfile.celery`as well as `docker-compose.yml`, I am pretty sure that `Dockerfile` is the new `Dockerfile.celery`. I am guessing that `Dockerfile.celery` is simply a vestige that was never deleted.

**Comment by Didayolo** [comment]
@ObadaS And what about `Dockerfile.builder` ?

https://github.com/codalab/codabench/blob/develop/Dockerfile.builder

Useless too?
