### ISSUE TITLE
How to set a column in the leaderboard as hidden in the YAML?

### ISSUE THREAD

**Issue by aprbw** [codalab/codabench#1515]
# How to set a column in the leaderboard as hidden in the YAML?

Using the GUI, I can choose which column to hide/unhide through the check boxes shown below:

![Screenshot 2024-07-08 at 12 21 20](https://github.com/codalab/codabench/assets/42436117/6d0b0125-ebc1-4cdd-b86d-f2bc88255261)

However, I cannot find instruction on how to do this via the bundle / YAML. In particular, I have checked the following links:
* https://github.com/codalab/codabench/wiki/Competition-Creation:-Bundle
* https://github.com/codalab/codabench/wiki/Yaml-Structure
* https://github.com/codalab/codabench/wiki/Leaderboard-Functionality

Please advise if
(1) this can only be done via GUI as of now, or
(2) that the wiki/docs for the YAML-structure needs updating.

Thank you.

**Comment by ihsaan-ullah** [comment]
You can hide a column using your yaml file. Documentation is updated
https://github.com/codalab/codabench/wiki/Yaml-Structure#optional-5
