### ISSUE TITLE
Scoring Program not appearing under the Files page.

### ISSUE THREAD

**Issue by aprbw** [codalab/codabench#1516]
This is a dummy competition: https://www.codabench.org/competitions/3368/

I have checked the `Make Programs Available` checkbox.

![image](https://github.com/codalab/codabench/assets/42436117/7f032ddf-eacb-4f94-bebb-10b73ba8f959)

However, the scoring program is not appearing in the `Files` page.

![image](https://github.com/codalab/codabench/assets/42436117/05e68c99-ff44-4b3b-abd5-6da838d36943)

As shown the the above image, the only file shown is the starting kit, the `scoring.py` files are not on the list. The expectation is that the `scoring.py` file should be available here.

Thanks in advance.

**Comment by Didayolo** [comment]
Indeed, I can see the scoring program in the task but not in the Files tab.

@bbearce Any input on this?

**Comment by ihsaan-ullah** [comment]
I have checked and on my side I don't have this problem.

### Programs only
<img width="235" alt="Screenshot 2024-07-13 at 10 32 30 AM" src="https://github.com/user-attachments/assets/8cfb19ac-b423-4fce-ae2d-78de614dabd6">
<img width="905" alt="Screenshot 2024-07-13 at 10 31 31 AM" src="https://github.com/user-attachments/assets/2f9a8c00-1a1c-4e0c-957e-81271887dacb">



### Input only
<img width="237" alt="Screenshot 2024-07-13 at 10 32 34 AM" src="https://github.com/user-attachments/assets/9a29beba-2132-4d07-a283-0e4c1d371364">
<img width="911" alt="Screenshot 2024-07-13 at 10 32 01 AM" src="https://github.com/user-attachments/assets/5f232994-3b19-407e-a667-9f6e963e9bf8">


### Programs and Input
<img width="253" alt="Screenshot 2024-07-13 at 10 32 38 AM" src="https://github.com/user-attachments/assets/0e81f3d8-5ceb-4e4a-bf57-736e7cb83a5e">
<img width="910" alt="Screenshot 2024-07-13 at 10 32 19 AM" src="https://github.com/user-attachments/assets/a25d0cdc-c0cc-4c59-98ee-224a4b3a1ce2">

**Comment by ihsaan-ullah** [comment]
@aprbw when you check a checkbox, do you save the changes using the `save` button?
<img width="731" alt="Screenshot 2024-07-13 at 10 44 12 AM" src="https://github.com/user-attachments/assets/05e872c7-2d54-44d6-9df7-dfb9057e281a">

**Comment by aprbw** [comment]
![ezgif-4-6447940a28](https://github.com/user-attachments/assets/2f45a5b1-2d3b-4476-95ac-26519d8b65c6)

I clicked the `save` button.

**Comment by ihsaan-ullah** [comment]
I think this is happening because of no ingestion program in your task. I will check this again

**Comment by Didayolo** [comment]
> I think this is happening because of no ingestion program in your task. I will check this again

That is a good start indeed, I remember seeing something similar in the past.

**Comment by aprbw** [comment]
<img width="1129" alt="Screenshot 2024-07-18 at 04 57 20" src="https://github.com/user-attachments/assets/538fb5f8-21c1-4c58-a333-e58ea23c7fe2">

I have added an ingestion program, to the task in the phase in the competition, and made the ingestion program public, but it is still not appearing under `Files` either.

**Comment by Didayolo** [comment]
@aprbw I think the issue should be fixed by #1528. It still needs to be merged and deployed on production.
