### ISSUE TITLE
Mutiple leaderboard

### ISSUE THREAD

**Issue by hpc100** [codalab/codabench#1534]
Hello thank's for your work.

I want to create a competition for a dataset with 3 variant named A, B, C. I'm wondering if it's possible to have 3 leaderboard. Someting like that :

Results for A
Participants -  ID   - Acc
Results for B
Participants ID  Acc
Results for C
Participants -  ID  - Acc

The goal is to distinguish results for the 3 variants.

How I can write competition.yaml file to do this ?

Thank's in advance.

**Comment by ihsaan-ullah** [comment]
Hi @hpc100 

At the moment we don't have multiple leaderboards feature in Codabench. We are planning to add this feature soon. For now you can use the same leaderboard with different column names e.g. `Acc A`, `Acc B`, `Acc C`.

**Comment by Didayolo** [comment]
That would indeed be useful.

I close this issue as this is reported here:
- #1392
- #873
- #1334
