### ISSUE TITLE
Server status: remove the 2 days limit

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1549]
I get that we limit the table to 250 submissions, but do we really need to limit it to 2 days?

<img width="1180" alt="Capture d’écran 2024-07-24 à 16 09 19" src="https://github.com/user-attachments/assets/d26d549b-1605-48dc-84d3-135b0a403556">

**Comment by ihsaan-ullah** [comment]
We can remove the limit and add pagination (50 records per page)
