### ISSUE TITLE
Fetching leaderboards using javascript

### ISSUE THREAD

**Issue by katyagovorkova** [codalab/codabench#1557]
Hello, I would like to display the results of three different competitions on my own website and sum the scores of the challenges to provide the total score, something like this: 

<img width="552" alt="Screenshot 2024-08-04 at 15 47 05" src="https://github.com/user-attachments/assets/a8729665-0646-4ea0-84e1-d8a0df78969c">

where the separate scores are from 3 different leaderboards of Codabench challenges (I can't link them since they are not published yet). 

To fetch the scores, I am using javascript as follows: 

```
async function getData() {
 \\ Here in the end we will have 3 URLs to 3 different challenges, once they are published
  const url = "https://www.codabench.org/api/competitions/2626/results.json";
  try {
     const response = await fetch(url);
     if (!response.ok) {
       throw new Error(`Response status: ${response.status}`);
     }

     const json = await response.json();
     console.log(json);

    \\ Results in the table are achieved by hardcoding the json to show an example of the desired output
    \\ json = {"User":"a3d3","Score A3D3":"0.8","Score imageomics":"0.6","Score iHARP":"0.7"};
    json["Total score"] = calculateTotalScore(json);
    displayTable(json);

     // Check if the response contains an error message
     if (json.detail) {
       displayError(json.detail);
     } else {
     // Assuming json contains valid data, display it as a table
       displayTable(json);
     }
   } catch (error) {
     console.error(error.message);
     displayError('Failed to load data.');
   }
}
```
If I put the URL https://www.codabench.org/api/competitions/2626/results.json directly in the browser, I can view the results of my unpublished competition. However, using `fetch(url)` in js throws an error: 
<img width="563" alt="Screenshot 2024-08-04 at 15 53 09" src="https://github.com/user-attachments/assets/54302c7c-1fea-4dba-acc6-3c824028267d">
Is there a way to fetch the leaderboard results from Codabench via javascript `fetch(url)`? Or maybe there is an alternative way that I could use to fetch the results of challenges to be displayed on my website? many thanks!

**Comment by ihsaan-ullah** [comment]
This is expected problem when cross-origin requests are not allowed. You can use different tools to get the required result e.g. using Postman app.

I am closing this because it is not an issue. This article may help you
https://medium.com/@dtkatz/3-ways-to-fix-the-cors-error-and-how-access-control-allow-origin-works-d97d55946d9
