### ISSUE TITLE
Email notification/send not working (CodaLab and Codabench)

### ISSUE THREAD

**Issue by Punchwes** [codalab/codabench#1579]
Hi,

We are organising a competition, and now experiencing some technical issues with email notification. From several days ago, I cannot receive the notification of participant's registration. Besides, when I email participants via the email icon in the web, there is a green "sent", but nothing actually happen....  

I am using Chrome 128.0.6613.115 (arm64). I have tried other browsers (e.g., firefox, safari), they are all the same.

May I ask what might be the problem of this?

**Comment by ihsaan-ullah** [comment]
@ObadaS could this be a problem from the mailing server?

I have checked and I don't receive emails.

**Comment by ObadaS** [comment]
It seems like I can't receive any emails too. I will investigate.

**Comment by ihsaan-ullah** [comment]
On google group Sushovit shared that codalab emails are also not working

**Comment by ObadaS** [comment]
@Punchwes @acletournel @ihsaan-ullah The problem has been fixed. It will take some time for the server to clear its Queue. Everything should be back to normal within a few hours at most.

**Comment by ihsaan-ullah** [comment]
This is resolved
