### ISSUE TITLE
CRUD posts in the forum as administrator

### ISSUE THREAD

**Issue by seroy123** [codalab/codabench#1596]
Hi
I am having trouble deleting users posts as administrator. Is the issue resolved or is it open? 
[Forums #570](https://github.com/codalab/codabench/pull/570)
Thanks!

**Comment by ihsaan-ullah** [comment]
Hi, we don't have a delete feature for administrators in the forum. Do you have a use-case where this is important and required?

**Comment by seroy123** [comment]
> Hi, we don't have a delete feature for administrators in the forum. Do you have a use-case where this is important and required?

Hi!
Yes i have a use-case. I am hosting a competition and I need to make sure there is no hate speech, racism and foul language in the forum. It is very important to us.
Thanks!
