### ISSUE TITLE
Activation link is invalid. Please double check your link.

### ISSUE THREAD

**Issue by vtphatt2** [codalab/codabench#1601]
I registered my account on Codabench a month ago. However, I realized that the competition my school organized was in Codalab, so I did not activate my account through the link sent via gmail. Now I need to take another competition organized on Codabench and I found the activation link in the email and clicked it, but received the message "Activation link is invalid. Please double check your link."

Can you please send me another activation link.

Email: thinhphat544@gmail.com

**Comment by vtphatt2** [comment]
@ihsaan-ullah @Didayolo 
I need to register an account urgently because the competition registration deadline is tonight. Could you re-send me another activation link? 

My username: vtphatt2

**Comment by Didayolo** [comment]
Hi @vtphatt2, I manually activated your account. Feel free to re-open the issue if it's not working.

Linked to:

- #1018
