### ISSUE TITLE
Current phase ends: never

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1617]
<img width="819" alt="Screenshot 2024-10-07 at 10 19 39 AM" src="https://github.com/user-attachments/assets/da2e824d-6d46-47c5-9ed4-dac89e762ccb">

Current Phase Ends = Never 

This is misleading because sometimes you don't have an active phase. Is that ok or do we want to make some changes?

**Comment by Didayolo** [comment]
Hi @ihsaan-ullah, I don't get it. How we have no active phase if the last phase is set to never ending?

**Comment by ihsaan-ullah** [comment]
> Hi @ihsaan-ullah, I don't get it. How we have no active phase if the last phase is set to never ending?

In the screenshot I have shared, no phase is currently active and last phase is not never ending but we still see "Current Phase: Never Ends"

**Comment by Didayolo** [comment]
OK it is indeed confusing. In a way, it's true that the current "unactive phase" is set to never end. But it would be clearer to state that no phase is active.
