### ISSUE TITLE
Email notification/send not working (Codabench)

### ISSUE THREAD

**Issue by zzx0001** [codalab/codabench#1618]
I registered to join a competition (NTU coursework), but I couldn't receive the activation email.

I am using Edge 129.0.2792.65.

**Comment by Didayolo** [comment]
Please send an email to info@codalab.org with your registered email, and tell your Codabench username in the request.

This way, we can see if there is any problem with your email domain, and on any case manually activate your account.
Soon there will be a "resend activation email" button on the platform (#1615).

I close this issue to continue resolving this on the support email.
