### ISSUE TITLE
Score is not displayed in the Public Leaderboard

### ISSUE THREAD

**Issue by vtphatt2** [codalab/codabench#1619]
Hi there, 
I'm attending a competition with the following link : https://www.codabench.org/competitions/3909

I submitted my results last night and the score is displayed in "My Submissions" tab as follows : 
<img width="1201" alt="Ảnh màn hình 2024-10-08 lúc 08 51 37" src="https://github.com/user-attachments/assets/074023cf-60d1-44d2-999e-74f0003403fe">

But in the Public Leaderboard of "Results" tab, my score is not displayed. I have reloaded many times until now, but my score is still not displayed.
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/3350d7cd-e15d-4432-abf0-73544768682f">

Is this a bug or I forgot any important step? 
Thank you so much for your help!

**Comment by ihsaan-ullah** [comment]
Please click this button in for your submission to add it to the leaderboard
<img width="90" alt="Screenshot 2024-10-08 at 10 38 27 AM" src="https://github.com/user-attachments/assets/3eccfd50-3f86-43ec-b0f5-1a8c46b4e46a">

**Comment by vtphatt2** [comment]
> Please click this button in for your submission to add it to the leaderboard
> <img alt="Screenshot 2024-10-08 at 10 38 27 AM" width="90" src="https://private-user-images.githubusercontent.com/13259262/374421784-3eccfd50-3f86-43ec-b0f5-1a8c46b4e46a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzY1NTcsIm5iZiI6MTcyODM3NjI1NywicGF0aCI6Ii8xMzI1OTI2Mi8zNzQ0MjE3ODQtM2VjY2ZkNTAtM2Y4Ni00M2VjLWIwZjUtMWE4YzQ2YjRlNDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA4MzA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNGJkNjIzOTc4NDE3MGI4ZGM3NjdkZjJmOWIwZWE5NWM1ZGM2ZDc4MTczYTFlYjRkYWRhYjI2ZmU5MDdlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g7vWXcHDQ5WiEvQm83TVnx7k3Rd6mCSbUSmHvXWhu18">

Ok, It works. Thank you so much for my ignorant question :(
