### ISSUE TITLE
Task upload

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1621]
- Upload new tasks using zip files (zip datasets and programs with a yaml file that is uploaded and becomes a task)
- During the upload, allow users to use already uploaded datasets (e.g. if you want to create a new task by uploading ingestion and scoring but you want to use already uploaded input and reference data)

**Comment by Didayolo** [comment]
> During the upload, allow users to use already uploaded datasets (e.g. if you want to create a new task by uploading ingestion and scoring but you want to use already uploaded input and reference data)

How is this done when we dump a bundle using URI keys instead of files? Probably the logic is already implemented (include keys in `competition.yaml` instead of a file path.
