### ISSUE TITLE
All submissions stucked with "Submitted" status

### ISSUE THREAD

**Issue by FrozenBurning** [codalab/codabench#1632]
Hi @Didayolo, thanks for the awesome open-sourcing benchmark platform! 
I'm now hosting a challenge here: https://www.codabench.org/competitions/3759/ However, all submissions get stuck at `submitted` status no matter the queue I'm using. It would be great if you could help me restart the docker itself!

**Comment by piyushsinghpasi** [comment]
Hii @FrozenBurning  did you find a solution to this? I am experiencing something similar (no errors, no logs, just stuck at submitted)

**Comment by ObadaS** [comment]
@piyushsinghpasi Hello, it was a bug on our end. I have fixed the issue

**Comment by Hypatiaalegra** [comment]
Hi,@ObadaS. I have also encountered the issuse right now, the benchmark I'm hosting is https://www.codabench.org/competitions/4140/ and all submissions get stuck at **submitted** status similarly. When I upload another new benchmark, this issues happened again no matter what I submitted. Thanks for you help!

**Comment by ObadaS** [comment]
@Hypatiaalegra Hello, this is now fixed
