### ISSUE TITLE
No button to re-send account activation link?

### ISSUE THREAD

**Issue by RayWP** [codalab/codabench#1636]
- What browser and version are you using?
Firefox version 131.0.3 

- How to replicate?
1. Create an account
2. Successfully get into the platform
3. Did not realize there is an account activation email
4. Leave it for 7 days
5. Try to login using the same account, but get "Your account has not been activated, please check the link in your mail"
6. Find the 7 days old mail, click the link
7. Get an error "Activation link is invalid, please check your link"

I do not see any button to resend the activation link

**Comment by RayWP** [comment]
Redundant, see #1601

**Comment by RayWP** [comment]
my email is rwp1byte@gmail.com

I would appreciate any help, maybe similar to #1601

**Comment by Didayolo** [comment]
Dear @RayWP,

I manually activated your account. Hopefully you'll be able to receive future emails and notifications.

The resend button is part of this PR and will be added soon to the production server: #1615.

Feel free to re-open the issue if needed.
