### ISSUE TITLE
Optimization Discussion

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1648]
- Home page popular and featured competitions
- Global counters

**Comment by Didayolo** [comment]
Duplicate of #1327 ?

**Comment by ihsaan-ullah** [comment]
This is for the short time solutions we have discussed today. and want to implement this week. 1327 is more like long term and time consuming solution to the problem

**Comment by ihsaan-ullah** [comment]
Resolved by #1649
