### ISSUE TITLE
not receiving link to reset password

### ISSUE THREAD

**Issue by sofiaaabrunori** [codalab/codabench#1651]
***This is a template, please remove any non-relevant details to your issue***

If you are competition participant:
-----------------------------------

- This Github repository is about the **platform** itself.
- If you problem is specific to a competition, **please contact directly its organizers**.

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

- Please post a link to your competition.

If you are having trouble using the site:
-----------------------------------------

- What browser and version are you using?
- What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

**Comment by Didayolo** [comment]
Fix soon to be merged #1615
