### ISSUE TITLE
not receiving link to reset password

### ISSUE THREAD

**Issue by sofiaaabrunori** [codalab/codabench#1652]
I am having trouble resetting my password for my Code Bench account. Here’s what I’ve tried:
I clicked the "Forgot my password" link on the login page and entered my email address.
I checked my inbox and spam/junk folders, but I have not received any password reset email.
I waited several minutes and tried requesting the password reset email again.
Could you please assist me with this? Is there anything else I should check, or could someone from the support team help manually reset my password?
Thank you for your help!

**Comment by ObadaS** [comment]
Hello, 
I just tried to reset my account password and successfully received the email with a working link.

- Did you check the email address that you entered ? Maybe you have misspelled it on the password reset form.
- Are you sure the email you are using is the one associated to the account ?

If you give me your account name, I can check the email address associated to it. If you want to keep it private, you can email us at info@codalab.org
