### ISSUE TITLE
Stuck after account confirmation link timed out

### ISSUE THREAD

**Issue by ArmaFio** [codalab/codabench#1653]
Good Morning, 
I'm experimenting this issue with my account since i had not noticed i had to use the link to confirm it, and when i finally noticed and i clicked on it it says that it's timed out.
I can't activate my account, i can't receive other links, but the account still exists so the site won't let me create it again, it keeps telling me that the e-mail is already registered.
I'm totally stuck on this, and i really need to access THAT account.
Thank you in advance for the help

**Comment by ObadaS** [comment]
Hello, can you post your account name ? I will manually activate your account so that you can log in

**Comment by ArmaFio** [comment]
armaf, the e-mail is armando.fiorini@mail.polimi.it

**Comment by ObadaS** [comment]
I have activated it, you can now log in
