### ISSUE TITLE
Website is very very slow.

### ISSUE THREAD

**Issue by mahmoudrahat** [codalab/codabench#1668]
Hello,

We planned to start our competition today, but the portal is very very slow. Even the home page takes a long time to open. Is it going to be fixed any time soon?

Best,

**Comment by daniel-dona** [comment]
Same here 
![imagen](https://github.com/user-attachments/assets/3a6e108b-21af-4163-8afb-34319eeff8fa)

**Comment by Didayolo** [comment]
Dear users,

Indeed, Codabench is slow right now. We are working on it to resolve the issue as soon as possible.
Thank you for your comprehension.

**Comment by ndido98** [comment]
The site, at least for me, is back to decent response times. However, many submissions in my competition are stuck in "Running" state. Is it a consequence of the slowdown or is it a separate issue?

**Comment by archettialberto** [comment]
Hi @ndido98, same for our competition. The website is loading but all workers are returning HTTP 500 errors when contacting the server, resulting in submissions remaining in a "Running" state.

**Comment by ndido98** [comment]
We tried to run our own worker, and this is the stack trace we get when we run a submission on it:

```
Traceback (most recent call last):
 File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
   return self.run(*args, **kwargs)
 File "/compute_worker.py", line 113, in run_wrapper
   run.start()
 File "/compute_worker.py", line 827, in start
   loop.run_until_complete(gathered_tasks)
 File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
   return future.result()
 File "/compute_worker.py", line 696, in _run_program_directory
   return await self._run_container_engine_cmd(engine_cmd, kind=kind)
 File "/compute_worker.py", line 504, in _run_container_engine_cmd
   websocket = await websockets.connect(self.websocket_url)
 File "/usr/local/lib/python3.9/site-packages/websockets/client.py", line 542, in __await_impl__
   await protocol.handshake(
 File "/usr/local/lib/python3.9/site-packages/websockets/client.py", line 296, in handshake
   raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 500
```

**Comment by daniel-dona** [comment]
Facing this same situation, running since yesterday night...
![imagen](https://github.com/user-attachments/assets/94af2a84-7d1f-4c5d-ac65-921da72f6878)

**Comment by lrzpellegrini** [comment]
The AMQP broker seems to be down (which means submissions are completely stuck).

**Comment by Didayolo** [comment]
I close this issue to keep track of the problem on this issue only:
- #1327

If you are facing a different problem (queue congestion, problem with worker setup, etc.), please open a separate issue.
Thank you for your comprehension.
