### ISSUE TITLE
404

### ISSUE THREAD

**Issue by olemthorrud** [codalab/codabench#1680]
If you are having trouble using the site:
-----------------------------------------

- What browser and version are you using? Safari. 
- What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
   - The official link which leads to our competition, which I believe is specific to the participants so I do not want to share it here. 
   
I get a 404, with the following error message: 

"Could not find the page you requested.

If you are the challenge organizer and this URL previously pointed to a valid competition and it is now missing please contact us at info@codabench.org for more information.

If this is an error, please file a [bug report](https://github.com/codalab/codabench/issues/new). For more information about Codabench, check out the [wiki](https://github.com/codalab/codabench/wiki)."

Comp: 4430. 

I still have a try left, and would like to be able to use it!

**Comment by ObadaS** [comment]
Hello, are you logged into the site ? This error can show if you are not logged in.

**Comment by Didayolo** [comment]
This competition is private, login to be able to see it

https://www.codabench.org/competitions/4430/
