### ISSUE TITLE
Only some submissions stuck in "Preparing" phase

### ISSUE THREAD

**Issue by archettialberto** [codalab/codabench#1681]
Dear Codabench team,

We are the organizers of competition https://www.codabench.org/competitions/4430/. During the Final phase, we noticed some submissions stuck in "Preparing" state and never proceeding to "Running" and "Scoring". We tried

* Canceling and rerunning the submission.
* Upload the zip again as a new submission.
* Checking the worker logs but these specific submissions never show in the logs.

Specifically, the submission IDs currently in this situation for our competition are 166682, 166683, 166684, 166685, 166686, 166713, and 166963. Please note that some of these have been cancelled by the participants after waiting many hours without obtaining results. Is there a way for us to intervene and complete the scores for those submissions? What could be the root cause of this issue?

Thanks for the support!

**Comment by Didayolo** [comment]
Hi @archettialberto,

The state "Preparing" is when the compute worker is setting up the submission container. Typically, the worker is pulling the docker image during this phase.

As you are using your own queue, and that the problem randomly happens, it looks like some of your workers are not healthy.

Try to connect to each worker and check their status, typically running:
```sh
docker ps  # you should see a container "compute_worker" and maybe a second container if a submission is running
docker images  # check if your image "aarchetti/codabench:1.1" is there
docker pull aarchetti/codabench:1.1  # check if you are able to pull the image
docker logs -f compute_worker  # the most important, here you may have error logs on some workers
```

You can also re-setup the workers, following the documentation.

I hope this helps!

**Comment by archettialberto** [comment]
@Didayolo thanks for the support and the prompt response. Looking more closely to the worker output this may be related to the compression algorithm used to prepare the submission files. Here the logs:
```
an2dl-worker3  | [2024-11-22 19:07:48,114: ERROR/ForkPoolWorker-3] Task compute_worker_run[256fd862-b5e2-4f8e-8084-d69be95687cb] raised unexpected: NotImplementedError('That compression method is not supported')
an2dl-worker3  | Traceback (most recent call last):
an2dl-worker3  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
an2dl-worker3  |     R = retval = fun(*args, **kwargs)
an2dl-worker3  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
an2dl-worker3  |     return self.run(*args, **kwargs)
an2dl-worker3  |   File "/compute_worker.py", line 112, in run_wrapper
an2dl-worker3  |     run.prepare()
an2dl-worker3  |   File "/compute_worker.py", line 787, in prepare
an2dl-worker3  |     zip_file = self._get_bundle(url, path, cache=cache_this_bundle)
an2dl-worker3  |   File "/compute_worker.py", line 457, in _get_bundle
an2dl-worker3  |     z.extractall(os.path.join(self.root_dir, destination))
an2dl-worker3  |   File "/usr/local/lib/python3.9/zipfile.py", line 1654, in extractall
an2dl-worker3  |     self._extract_member(zipinfo, path, pwd)
an2dl-worker3  |   File "/usr/local/lib/python3.9/zipfile.py", line 1707, in _extract_member
an2dl-worker3  |     with self.open(member, pwd=pwd) as source, \
an2dl-worker3  |   File "/usr/local/lib/python3.9/zipfile.py", line 1580, in open
an2dl-worker3  |     return ZipExtFile(zef_file, mode, zinfo, pwd, True)
an2dl-worker3  |   File "/usr/local/lib/python3.9/zipfile.py", line 801, in __init__
an2dl-worker3  |     self._decompressor = _get_decompressor(self._compress_type)
an2dl-worker3  |   File "/usr/local/lib/python3.9/zipfile.py", line 700, in _get_decompressor
an2dl-worker3  |     _check_compression(compress_type)
an2dl-worker3  |   File "/usr/local/lib/python3.9/zipfile.py", line 680, in _check_compression
an2dl-worker3  |     raise NotImplementedError("That compression method is not supported")
an2dl-worker3  | NotImplementedError: That compression method is not supported
```
