### ISSUE TITLE
Bug Report: Downloaded submissions contain an empty folder instead of the expected file

### ISSUE THREAD

**Issue by magrichard** [codalab/codabench#1692]
Hello @Didayolo ,

We’ve encountered an issue on the Codabench platform, likely related to a recent deployment (merge performed two days ago). 

**Here are the details:**

When downloading a submission that has been processed on the platform (either from the admin side or the participant side), the program.R file is replaced by an empty folder named program.R. 

Submissions still run correctly on the platform, so the issue seems to occur during the process where Codabench rebuilds the ZIP archive provided for download.

**Context**

- The issue was first noticed yesterday (Monday, December 2nd), but it was working correctly earlier in the day.
- We suspect it may be linked to a deployment or changes made on the platform yesterday.
- The competition we are running is ongoing (December 2–5), so this issue is time-sensitive as we planned to re-run top submissions on new data today.

**If you want to reproduce the bug :**

- Download a submission from [this competition](https://www.codabench.org/competitions/4714/#/participate-tab), I just added you admin of the competition
- Inspect the contents of the ZIP file.
- Note that the program.R file is replaced by an empty folder.

This issue is critical as we planned to re-run all the best methods today for the final phase of our challenge. A fix by this afternoon would be greatly appreciated. If not, we will explore alternative solutions.

Thank you for your help,
Magali, @nicomy, and Florent

**Comment by Didayolo** [comment]
This is a surprising bug, that we will investigate. A fix working and deployed on production by this afternoon does not seems realistic to be honest.

I know it is a silly question, but can you confirm that `program.R` is a file and not a folder in the original submissions?

**Comment by Didayolo** [comment]
Apparently the problem is not related to Codabench, as it happens without uploading and downloading on the platform.

It is related to the way the submission are zipped / unzipped in this project, using the zip R package.
