### ISSUE TITLE
Always "Submitted" Never "Running"

### ISSUE THREAD

**Issue by maskoffs** [codalab/codabench#1696]
We tested codalab's competition bundle and submission code on codabench, and we found that our commits were always in the SUBMITTED state and not going into RUNNING. But on the codalab platform, we were able to get results properly. We then went to the server page and checked the status of the submission as shown below. We didn't select queue but used the default one, but the submission didn't have a hostname assigned.
![1](https://github.com/user-attachments/assets/677e083a-1971-42ad-a368-0f8c8eabeb86)

We want to know what exactly is causing the problem. And how to fix it.

**Comment by ObadaS** [comment]
Hello, this was a problem on our end, which has been fixed. 
Your submissions should be working now.

**Comment by maskoffs** [comment]
Thanks for your reply !
