### ISSUE TITLE
Missing "metadata.yaml/metadata"

### ISSUE THREAD

**Issue by maskoffs** [codalab/codabench#1697]
We are trying to migrate our codalab competition to codabench with an error. The zip file we submitted contains “metadata”, “model.py”, “model.pth”, which works perfectly on codalab, but on codabench we get an error as shown in the picture.

![image](https://github.com/user-attachments/assets/48917cf0-b7c9-44c3-84ef-ca6ad3da8462)

We want to know what to do about it.

**Comment by ihsaan-ullah** [comment]
Your ingestion and scoring programs are not zipped correctly. Make sure to zip only the files (without the directory). This will fix your problem

**Comment by maskoffs** [comment]
Should input_data and reference_data also be zipped without the directory?

**Comment by ihsaan-ullah** [comment]
> Should input_data and reference_data also be zipped without the directory?

yes

**Comment by maskoffs** [comment]
Thanks for your reply !

**Comment by maskoffs** [comment]
Another Question: when running ingestion.py, we meet an error. In ingestion.py, we want to import model, so we use "from model import model" , but it failed.

![image](https://github.com/user-attachments/assets/a6a337f1-baea-403d-9d19-117466cccf77)

**Comment by ihsaan-ullah** [comment]
To fix this, please check our example competition
https://github.com/codalab/competition-examples/tree/master/codabench/mini-automl

**Comment by ihsaan-ullah** [comment]
Feel free to reopen the issue if needed.
