### ISSUE TITLE
Write test confirming someone can't fetch all leaderboards

### ISSUE THREAD

**Issue by ckcollab** [codalab/codabench#332]
https://github.com/codalab/competitions-v2/blob/749fb95be29964088b8c71c398e78b0a83c13404/src/apps/api/tests/test_leaderboards.py#L26

When hitting `/api/leaderboards/` (or whatever the endpoint is) confirm that nothing is returned. We should only return leaderboards filtered by competition.

**Comment by sahil1610** [comment]
@ckcollab I would like to contribute
