### ISSUE TITLE
Add "Accept Cookies?" nag 

### ISSUE THREAD

**Issue by ckcollab** [codalab/codabench#343]

**Comment by brendon-lind** [comment]
Working on this one today. Thanks

**Comment by ckcollab** [comment]
To add more context:
https://www.privacypolicies.com/blog/eu-cookies-directive/#What_Does_The_Eu_Cookies_Directive_Require

https://ico.org.uk/for-organisations/guide-to-pecr/cookies-and-similar-technologies

Will have to read into this a bit..

**Comment by brendon-lind** [comment]
Does this need to be different from the version that already works on v1.5? I have transfered that code and have it working on v2.  Thanks
