### ISSUE TITLE
Make submission modal show tasks, should update while running

### ISSUE THREAD

**Issue by ckcollab** [codalab/codabench#358]
re: https://github.com/codalab/competitions-v2/pull/356#issuecomment-591652222

I had to refresh the page to see these tasks when i clicked the submission in the submission table:

![image](https://user-images.githubusercontent.com/2185159/75389483-6a9bec00-589b-11ea-9552-0d8fb36f8775.png)

While it's running it always shows:
![image](https://user-images.githubusercontent.com/2185159/75389534-8606f700-589b-11ea-9c5c-1ab3149f7c3c.png)

**Comment by Didayolo** [comment]
Merged to a more general issue.
