### ISSUE TITLE
Leaderboard GUI missing features

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#375]
Please have a look at the screenshots and the YAML file from this issue: #368

The leaderboard in V2:
* [x] doesn't show the column names (`label` field in YAML), if uploading a v1 bundle. It uses the `key` instead.
* [x] doesn't have the `Date of last entry` column
* [x] doesn't have the `entries` column

Related issues: #610, #611

**Comment by Didayolo** [comment]
In addition to the column names replaced by the "key" instead of title:

After a dump, the `competition.yaml` lose the column names information:

![dump_issue](https://user-images.githubusercontent.com/11784999/76946750-cc80cc00-6904-11ea-9e76-c6729d253e3e.png)

**Comment by ihsaan-ullah** [comment]
@Didayolo 
Just fixed this issue from the 3 mentioned in https://github.com/codalab/codabench/pull/853. Others don't seem too urgent.
<img width="836" alt="Screenshot 2023-05-09 at 7 11 39 PM" src="https://github.com/codalab/codabench/assets/13259262/3bbf0f24-18d6-4bb7-9b06-9eb077c6e4cd">

**Comment by Didayolo** [comment]
I close this issue as it is tackled by #871
