### ISSUE TITLE
Do not return hidden columns from the server

### ISSUE THREAD

**Issue by jimmykodes** [codalab/codabench#380]
Scores on leaderboards with hidden columns are still returned form the server in full and the hidden scores are filtered on the frontend, meaning the columns are not hidden to the API. They should be.

A hidden column should still be used in consideration of ranking submissions (or at least that is my opinion) but the values of those scores should _not_ be visible to the API.

# Todos:

- [x] unpack `hidden` column  in V1 unpacker
- [x] do not show `hidden` column in leaderboard

**Comment by ihsaan-ullah** [comment]
https://github.com/codalab/codabench/blob/00f638d55c03732136ba8d4ce273fea22e59f72c/src/static/riot/competitions/detail/leaderboards.tag#L109

**Comment by ihsaan-ullah** [comment]
# Issues:

1. While unpacking, `hidden` attribute for column is not used
2. Hidden columns are returned and are shown on leaderboard

https://github.com/codalab/codabench/blob/00f638d55c03732136ba8d4ce273fea22e59f72c/src/static/riot/competitions/detail/leaderboards.tag#L109
