### ISSUE TITLE
[Feature] support for forming teams

### ISSUE THREAD

**Issue by msubglb** [codalab/codabench#407]
Do you support forming teams with more than one user?

Thanks!

**Comment by ckcollab** [comment]
We plan to add "Organizations" actually! Hopefully coming in the next ~4 months -- do you have any particular deadlines or anything? Do you have a design in mind for this feature already, if you don't mind sharing it? We could take maybe the best pieces of all approaches :)

**Comment by msubglb** [comment]
Sorry, we are trying to host the challenges next week. But, in the next cycle, we would love to have this feature.  I can share some of our thoughts in couple of weeks.

**Comment by Didayolo** [comment]
The organization feature is now implemented.
