### ISSUE TITLE
Add linux install instructions

### ISSUE THREAD

**Issue by ckcollab** [codalab/codabench#408]
- [ ] note you have to change `docker.for.mac.localhost` in `.env`!!!
- [ ] Edit `SUBMISSIONS_API_URL` in `.env_sample`

**Comment by bbearce** [comment]
Hi,
I'm writing to report my installation and findings while deploying using linux. I've noted this change for minio in the .env file:

# AWS_S3_ENDPOINT_URL=http://docker.for.mac.localhost:9000/
AWS_S3_ENDPOINT_URL=http://172.17.0.1:9000/

I can see minio loaded and buckets created:
![image](https://user-images.githubusercontent.com/7649007/111091322-ed283580-8508-11eb-9fec-047ec8b76069.png)
---

Next I ran the initial setup scripts (migrations were already run before showing this and same for collectstatic):
```
bbearce@pop-os:~/Documents/competitions-v2$ docker-compose exec django ./manage.py migrate
WARNING: Some services (site_worker) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Operations to perform:
  Apply all migrations: admin, auth, authtoken, competitions, contenttypes, corsheaders, datasets, forums, leaderboards, oauth2_provider, profiles, queues, sessions, sites, social_django, tasks
Running migrations:
  No migrations to apply.
bbearce@pop-os:~/Documents/competitions-v2$ docker-compose exec django ./manage.py generate_data
WARNING: Some services (site_worker) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Creating data of size 3 with an admin account.
bbearce@pop-os:~/Documents/competitions-v2$ docker-compose exec django ./manage.py collectstatic --noinput
WARNING: Some services (site_worker) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.

0 static files copied to '/app/src/staticfiles', 273 unmodified.

```
---

Next, I'm not sure what we should change SUBMISSIONS_API_URL to in the .env file. Any suggestions?
---

Finally everything deploys but I'm getting a gunicorn error in the django logs:
```
django_1          |   File "/app/src/asgi.py", line 11, in <module>
django_1          |     django.setup()
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
django_1          |     apps.populate(settings.INSTALLED_APPS)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
django_1          |     app_config = AppConfig.create(entry)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 116, in create
django_1          |     mod = import_module(mod_path)
django_1          |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
django_1          |     return _bootstrap._gcd_import(name[level:], package, level)
django_1          |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
django_1          |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
django_1          |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
django_1          |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
django_1          |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
django_1          |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/apps.py", line 6, in <module>
django_1          |     import daphne.server
django_1          |   File "/usr/local/lib/python3.8/site-packages/daphne/server.py", line 20, in <module>
django_1          |     asyncioreactor.install(twisted_loop)
django_1          |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py", line 307, in install
django_1          |     reactor = AsyncioSelectorReactor(eventloop)
django_1          |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py", line 60, in __init__
django_1          |     raise TypeError(
django_1          | TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>
django_1          | [2021-03-15 01:05:50 +0000] [13] [INFO] Worker exiting (pid: 13)
django_1          | [2021-03-15 01:05:50 +0000] [7] [INFO] Shutting down: Master
django_1          | [2021-03-15 01:05:50 +0000] [7] [INFO] Reason: Worker failed to boot.
```
Any idea what could be causing this?

At 0.0.0.0:80 I get:
404 Site 0.0.0.0 is not served on this interface

and at localhost:80 I get:
502 Bad Gateway

I can't seem to get this to launch. This is the master branch and I did deploy the codabench/leaderboard_bundle branch and at least got the site to load but it had other issues like showing html tags while rendering content in challenge UI cards and boxes. Anyways another reason I'm writing is which branch should I consider stable enough to attempt a production install? Develop and master seem iffy (however I'm sure there is lots of user error), and I'm trying to start doing simple challenges for my institution on the new system rather than v1.5.

**Comment by bbearce** [comment]
Update:

In the docker-compose.yaml under django, this [stackoverflow](https://github.com/benoitc/gunicorn/issues/2103) article suggests adding --preload to the gunicorn statement:

What used to be:
```command: bash -c "cd /app/src && watchmedo auto-restart -p '*.py' --recursive -- gunicorn asgi:application -w 2 -k uvicorn.workers.UvicornWorker -b :8000 -b :80 --capture-output --log-level debug"```
is now 
```command: bash -c "cd /app/src && watchmedo auto-restart -p '*.py' --recursive -- gunicorn asgi:application -w 2 -k uvicorn.workers.UvicornWorker -b :8000 -b :80 --capture-output --log-level debug --preload"```

The site loads but static files, while copied, are not being found.
![image](https://user-images.githubusercontent.com/7649007/111096102-2e264700-8515-11eb-88dd-ec76c8fb99b7.png)

again staticfiles are already created:
```0 static files copied to '/app/src/staticfiles', 273 unmodified.```
Has anyone seen this before?

**Comment by bbearce** [comment]
So I deleted everything and started over and I think it works. Main things:

The ```--preload``` flag with gunicorn is essential (under django in docker-compose.yaml). Also I think running with DEBUG=True does something special and loads static differently. With it set to True things work better. Finally the mino url needs to be AWS_S3_ENDPOINT_URL=http://172.17.0.1:9000/.

docker-compose.yaml:
```
...
command: bash -c "cd /app/src && watchmedo auto-restart -p '*.py' --recursive -- gunicorn asgi:application -w 2 -k uvicorn.workers.UvicornWorker -b :8000 -b :80 --capture-output --log-level debug --preload"
...
```

.env
```
...
DEBUG=True
...
# Minio local storage Django settings (mocks an S3 endpoint)
...
AWS_S3_ENDPOINT_URL=http://172.17.0.1:9000/
...
```

**Comment by xunfeng1980** [comment]
@bbearce DEBUG=True ,it's ok...

**Comment by Didayolo** [comment]
@bbearce Is this issue still relevant?

**Comment by Didayolo** [comment]
> So I deleted everything and started over and I think it works. Main things:
> 
> The `--preload` flag with gunicorn is essential (under django in docker-compose.yaml). Also I think running with DEBUG=True does something special and loads static differently. With it set to True things work better. Finally the mino url needs to be AWS_S3_ENDPOINT_URL=http://172.17.0.1:9000/. Still not sure what we should change SUBMISSIONS_API_URL to...
> 
> I think SUBMISSIONS_API_URL should be: http://localhost:8000/api
> 
> docker-compose.yaml:
> 
> ```
> ...
>   django:
>     build: .
>     # NOTE: We use watchmedo to reload gunicorn nicely, Uvicorn + Gunicorn reloads don't work well
>     command: bash -c "cd /app/src && watchmedo auto-restart -p '*.py' --recursive -- gunicorn asgi:application -w 2 -k uvicorn.workers.UvicornWorker -b :8000 -b :80 --capture-output --log-level debug --preload"
> 
> ...
> ```
> 
> .env
> 
> ```
> ...
> DEBUG=True
> ...
> SUBMISSIONS_API_URL=http://localhost/api
> ...
> # Minio local storage Django settings (mocks an S3 endpoint)
> ...
> AWS_S3_ENDPOINT_URL=http://172.17.0.1:9000/
> ...
> ```
> 
> ![image](https://user-images.githubusercontent.com/7649007/111098766-89a70380-851a-11eb-9814-ad626530d6c3.png)

I just had the same problem, and using `DEBUG=True` solved it. Thank you! That is strange that my local instance broke out of nowhere however.
