### ISSUE TITLE
Dumps

### ISSUE THREAD

**Issue by madclam** [codalab/codabench#415]
We identified with Romain 2 bugs in dumps:

1) People that are admins but NOT competition owners cannot create dumps
2) Newly created dumps (e.g. today june 8, 2020) obtain the "wrong" date.

<img width="891" alt="Screen Shot 2020-06-08 at 9 17 05 AM" src="https://user-images.githubusercontent.com/7594063/84054853-d4cb2f00-a968-11ea-8b2a-8091cd94ba2a.png">
 in this example the date 2019-11-27 should be 2020-06-08

**Comment by madclam** [comment]
There is no possibility to create a dump of competition that includes the task as a zip inside the competition bundle.

**Comment by Didayolo** [comment]
Merged.
