### ISSUE TITLE
Feature Request: Hashtags in Descriptions of Competitions/Tasks/Datasets

### ISSUE THREAD

**Issue by Deathn0t** [codalab/codabench#420]
After meeting with @madclam, we thought it would be extremely useful to provide to the user the possibility of using Hashtags in descriptions of Competitions, Tasks, and Datasets.

This feature needs to include the following sub-features:
- [ ] When a user writes an hashtag (e.g. `My description #BestCompetition #Image #CNN`) it needs to be rendered as a hyperlink on the page.
- [ ] A user can use hashtags to search in the search bar on the upper-left corner of the page. The search has to look among Competitions/Tasks/Datasets descriptions.
- [ ] When the user click on a hashtag, the website should redirect to a search corresponding to this hashtag.

This functionality would replace the definition of keywords while defining Competitions/Tasks/Datasets.

**Comment by Didayolo** [comment]
Similarly, we discussed recently the possibility of having tags to characterize benchmarks (e.g. "learning" for student benchmark), or tags refering to the tasks in question (e.g. "computer vision").

I guess the hashtag feature contains this feature. But the use of hashtags should then be incentivized by the inferface.

**Comment by Didayolo** [comment]
More generally, the "public benchmarks" interface should be improved, to help going through benchmarks, filtering, etc.

<img width="1302" alt="Capture d’écran 2023-05-12 à 17 45 23" src="https://github.com/codalab/codabench/assets/11784999/ebe2ad87-2365-4bb6-b3f5-0049f2a6ac19">

**Comment by Didayolo** [comment]
Similar request: adding filters in the public competition page

**Comment by ihsaan-ullah** [comment]
Shifted to discussions: #1333 1334
