### ISSUE TITLE
Unsupported features

### ISSUE THREAD

**Issue by madclam** [codalab/codabench#423]
This issue summarizes all the useful v1 features not supported in v2:

- [ ] Assets: a directory in the competition bundle containing files to which the doc files can link to.
- [ ] Leaderboard: limit/specify significant digits from leaderboard's level, For exmaple in V1, https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard, numeric_format is used
- [ ]  Public data and starting kit (see also #277)

**Comment by NehzUx** [comment]
- [ ]  Leaderboard: limit/specify significant digits from leaderboard's level

**Comment by Didayolo** [comment]
Merged.
