### ISSUE TITLE
Algorithm creation page

### ISSUE THREAD

**Issue by ckcollab** [codalab/codabench#429]
Very similar to task creation page

----

- [ ] **Must follow a sample submission provided by organizers.** -- does this mean algorithm creation requires an existing solution to be attached to it?
- [ ] **Must be able to specify different templates for different algorithm.** -- we need more detail on this? What is a "template?"

**Comment by ckcollab** [comment]
### Part A) Adding an additional "task" (algorithm) to existing competition

1. do we allow normal users to add tasks? or should they need to be a collaborator? in this case, we can already add new tasks. we just need to handle evaluating submissions vs this new task (see part b)
1. use existing task creation page?

### Part B) What happens when we add new task?

1. Existing submissions must be ran against task
1. Mark leaderboard/scores as "N/A" // "in progress" // something?


### Part C) What if we _do_ want normal participants to be able to propose new datasets/algorithms for a competition?

![image](https://user-images.githubusercontent.com/2185159/92649304-a890b880-f29f-11ea-8378-5695910992c7.png)


1. If competition is benchmark style
1. We could maybe add a "Propose new dataset/algorithm for this benchmark competition" modal, which presents you with a dropdown search for tasks. And a link to "create a new task" page OR maybe we could potentially show the "task creation modal"
1. Once a new dataset/algorithm is proposed, there should be some screen of "proposed algorithms/datasets" for a competition creator/collaborator to "approve" or "deny" (very similar to participating in a competition)


This could even be a toggle-able option "allow algorithm/dataset proposals"

**Comment by Didayolo** [comment]
I think we simply need to be able to chose the type "solution" during a dataset upload, and to optionnaly add a solution when creating a task.

**Comment by Didayolo** [comment]
We have this:

<img width="1098" alt="Capture d’écran 2023-06-23 à 15 48 08" src="https://github.com/codalab/codabench/assets/11784999/8e840cd7-ef09-413e-b5e8-7de79c58bb7a">
