### ISSUE TITLE
All submissions failed with no logs  - "Health Data Challenge" [Challenge 67]

### ISSUE THREAD

**Issue by AlexisArnaud** [codalab/codabench#440]
Reproduce Step :
 1. Download the starting kit from the v1.5 of the challenge : https://codalab.lri.fr/competitions/333#participate-get_starting_kit
 2. Submit the submission file "sample_code_submission.zip" to the v2. of the challenge : https://codalabcomp-v2-prod.lri.fr/competitions/67/#/participate-tab

Error :
 1. From what I see inside the output during the submission upload, the submission goes to the scoring program (I get a score for the set 1), but then nothing happen and at the end the submission status is "Failed" with a time out as information.
![Screenshot_2020-06-23_submission_in_progress](https://user-images.githubusercontent.com/55231077/85397885-a21e5a80-b554-11ea-8a68-c1f1364aaa82.png)

 2. And the logs are empty for both the prediction and scoring parts.
![Screenshot_2020-06-23_no_logs_1](https://user-images.githubusercontent.com/55231077/85398033-e3af0580-b554-11ea-88c2-02f4d83eb333.png)
![Screenshot_2020-06-23_no_logs_2](https://user-images.githubusercontent.com/55231077/85398035-e4479c00-b554-11ea-91e2-4ce8153f9717.png)

**Comment by AlexisArnaud** [comment]
same thing in the competitions 75 (https://codalabcomp-v2-prod.lri.fr/competitions/75/?secret_key=da3e1d85-409e-4348-8e59-a0bc514514c2)

**Comment by Didayolo** [comment]
Staling, all links are gone now unfortunately.
