### ISSUE TITLE
Ranking submissions in leaderboard

### ISSUE THREAD

**Issue by ckcollab** [codalab/codabench#447]
Many columns can be related to ranking.

Some columns may not be related to ranking.

Show columns related to summaries of tasks, i.e. total duration for all datasets (SUM computed type across all columns with duration in the name)

**Comment by Logan-Ruf** [comment]
Currently, there is one column(primary column) that is used to decide ranking on the leaderboard. We should add ways to compute leaderboard ranking across all columns on the leaderboard, and have a way to exclude to certain columns from the ranking calculation.
Make computed columns.
- Could automatically be generated by columns with the same key
  - Pro: simple and programmatic
  - Cons: Would have less control
- Could require each column to have a unique key and then group the columns later to be calculated OR
  - Could instead select columns by key + task
   - Pro: More control in selection
   - Con: tasks more work by admins

**Comment by Didayolo** [comment]
Merged.
