### ISSUE TITLE
Uploaded resource with zero size

### ISSUE THREAD

**Issue by Luyaochen1** [codalab/codabench#532]
I did an installation with Minio as the storage service, while there is a problem that the resources uploaded always got zero file size. The folder was created successfully, and just file size is zero. At the front end, I can see a 403 error. Here is the error message
"
jquery.min.js:4 PUT http://192.168.0.100:9000/private/dataset/2020-10-22-1603380986/59629d39b3b9/input_data.zip?AWSAccessKeyId=competition_key&Signature=eyoOyFjNmzYKEGVrrQFqVTgaP6E%3D&content-type=application%2Fzip&Expires=1603467387 403 (Forbidden)

"
Did anyone get an idea? 

I also tested Azure storage. It seems the error is the same.

**Comment by Didayolo** [comment]
@Luyaochen1 

Did you manage to make it work in the end?
