### ISSUE TITLE
Only status for latest submission is updated on submissions page

### ISSUE THREAD

**Issue by ckcollab** [codalab/codabench#576]

**Comment by Didayolo** [comment]
Indeed, when making several submissions quickly, only the status of the last one is updated automatically.

Not a big problem as people are not assumed to make many submissions at once, and refreshing the page does refresh the status.

**Comment by Didayolo** [comment]
We are talking about this:

<img width="511" alt="Capture d’écran 2023-08-22 à 16 12 47" src="https://github.com/codalab/codabench/assets/11784999/a933c8f8-d11d-481c-a128-a7034eb24813">

After refresh:

<img width="421" alt="Capture d’écran 2023-08-22 à 16 12 54" src="https://github.com/codalab/codabench/assets/11784999/774388ed-fefd-4953-982e-9efc1b367a7e">

Note that even first the last submission, the green logo is not updated automatically in the case of "force last submission to leaderboard" behavior.
