### ISSUE TITLE
Upload a dump from v1, html pages haven't been interpreted by v2

### ISSUE THREAD

**Issue by michavcr** [codalab/codabench#589]
Hello,
Thanks for your work. I tried to upload on codabench a dump of a codalabv1 challenge, that was a success, except for the html pages which don't seem to be interpreted correctly (images below). I saw that we can edit them through what seems to be a (working) markdown editor, but all html shaping has been lost. Is it necessary to rewrite the html in markdown, or is it a bug ?
![capture-codalabv1](https://user-images.githubusercontent.com/41841868/101515120-4c146680-397e-11eb-8e78-f0f22d94c8d4.png)
![capture-codabench](https://user-images.githubusercontent.com/41841868/101515128-4fa7ed80-397e-11eb-8b8f-33acb7a5be8d.png)
![capture-editor](https://user-images.githubusercontent.com/41841868/101515470-aad9e000-397e-11eb-8242-9a38ef2b491e.png)

**Comment by Didayolo** [comment]
Linked issue: 
- #283

**Comment by Didayolo** [comment]
Merged.
