### ISSUE TITLE
Skip "logout confirmed" page -- go directly back to index

### ISSUE THREAD

**Issue by ckcollab** [codalab/codabench#600]

**Comment by Didayolo** [comment]
https://github.com/codalab/codabench/blob/46f68ee91511a79d10fab817ca1164e35cd32d58/src/templates/registration/logged_out.html

https://github.com/codalab/codabench/blob/46f68ee91511a79d10fab817ca1164e35cd32d58/src/apps/api/views/profiles.py

**Comment by Didayolo** [comment]
Solved by:
- #721
