### ISSUE TITLE
Improve forum UI

### ISSUE THREAD

**Issue by Logan-Ruf** [codalab/codabench#601]

**Comment by Didayolo** [comment]
Tiny profile pic next to the username in the forum could be a nice addition too.

**Comment by ihsaan-ullah** [comment]
Is it normal to see user email in forum threads?

<img width="867" alt="Screenshot 2023-06-19 at 1 29 38 AM" src="https://github.com/codalab/codabench/assets/13259262/11a48f8a-5738-433d-93e8-05629e52476d">


I think this view should be stylized and changed a bit for more clarity
<img width="842" alt="Screenshot 2023-06-19 at 1 31 51 AM" src="https://github.com/codalab/codabench/assets/13259262/d7d87bec-1b49-4321-ae5c-1f0cf2c54ba6">
I suggest poster info an date etc on top of the post and the post content after that.
Nice card for each post will make the posts more clear to see

**Comment by ihsaan-ullah** [comment]
@Didayolo 

This forum is dedicated to just a competiiton, Is there any plan for a platform forum where community can engage and help each other rather. This can also lead to a blog page which can be referenced in the forum to point to commonly asked questions

**Comment by Didayolo** [comment]
@ihsaan-ullah 

> Is it normal to see user email in forum threads?

I don't think so!

> I suggest poster info and date etc on top of the post and the post content after that.

I agree with your proposition.

> Is there any plan for a platform forum where community can engage

That is an interesting suggestion, maybe we want to keep this for later. Right now we just have the google group.

**Comment by ihsaan-ullah** [comment]
I think username and email is fixed in #929
