### ISSUE TITLE
Participant submission panel UI improvements

### ISSUE THREAD

**Issue by madclam** [codalab/codabench#610]
Add the following information to the participant submission table:
- [x] Score shown on leaderboard
- [ ] Execution time
- [x] Date and time submitted
<img width="948" alt="Screen Shot 2020-12-17 at 9 53 59 PM" src="https://user-images.githubusercontent.com/7594063/102579924-6226d300-40b2-11eb-8e29-c7da600ff1aa.png">

**Comment by Logan-Ruf** [comment]
Added Creation Date. See #611 
![image](https://user-images.githubusercontent.com/16579931/102923336-6f421a00-4444-11eb-986f-ff96d479531d.png)

**Comment by ihsaan-ullah** [comment]
@Didayolo 

>  Score shown on leaderboard

On leaderboard we could have multiple scores. Which one do we want to show hare?

**Comment by Didayolo** [comment]
@ihsaan-ullah I guess there is always a column marked as "primary column", the one used for the ranking of participants. I guess it is this one that should be shown.

**Comment by ihsaan-ullah** [comment]
>  Execution time

@Didayolo for this i need to make more changes as execution time is not stored with the submission. I want to check with you first before starting this one

**Comment by Didayolo** [comment]
It is not overly important. We can work on this later.
