### ISSUE TITLE
Organizer submission panel

### ISSUE THREAD

**Issue by madclam** [codalab/codabench#611]
Add columns in submission panel:

- [x] Date and time submitted
- [x] Score shown on leaderboard
- [ ] Execution time

<img width="673" alt="Screen Shot 2020-12-17 at 10 01 04 PM" src="https://user-images.githubusercontent.com/7594063/102580679-dd3cb900-40b3-11eb-8117-04a242ad82b3.png">

**Comment by madclam** [comment]
Move to the bottom of the pate "Rerun all submissions per phase": we hit it accidentally many times.

Ask a confirmation: "really rerun everything" before doing it!

**Comment by madclam** [comment]
There is no action to migrate a submission "by hand".

**Comment by Logan-Ruf** [comment]
Added date:
![image](https://user-images.githubusercontent.com/16579931/102923537-c5af5880-4444-11eb-91fc-bdefe1a15462.png)
Website will ask for confirmation before rerunning submissions:
![image](https://user-images.githubusercontent.com/16579931/102923653-f42d3380-4444-11eb-911f-53f0324e2402.png)
`Execution Time` and a `Submission`'s rank on a `Leaderboard` is handled implicitly. To show this other areas would require a refactor, and probably wouldn't get finished before the end of the year.

**Comment by Didayolo** [comment]
Related issue:
- #610
