### ISSUE TITLE
Re-using resources to save time and storage space

### ISSUE THREAD

**Issue by magrichard** [codalab/codabench#632]
Hi @ckcollab and @madclam,

Do you think it would be possible to re-use already uploaded resources during further submissions. 
This would make sense to optimize the storage.
What are your thoughts about this? 

![Diapositive1](https://user-images.githubusercontent.com/18577578/104433528-7e6f4000-558a-11eb-903a-0ddd5d97f61d.png)

**Comment by Didayolo** [comment]
Maybe linked to:
- #596

**Comment by Didayolo** [comment]
This is even more interesting with dataset submissions
