### ISSUE TITLE
Leaderboard: submission ranking while multitasking

### ISSUE THREAD

**Issue by magrichard** [codalab/codabench#639]
Dear @Logan-Ruf @Tthomas63 @NehzUx @ckcollab ,

I was wondering how the leaderboard deals with several tasks while rannking the participants.

It is unclear to me in the competition #218 how the submissions are sorted. For instance, the submission ranked [2] displays n/a everywhere...

Here is a screenshot of the leaderboard:
<img width="1067" alt="Capture d’écran 2021-01-20 à 09 08 16" src="https://user-images.githubusercontent.com/18577578/105147044-e977c400-5b00-11eb-8a2c-cd4952ec65f2.png">

And a screen shot of the corresponding leadreboard set up:
<img width="969" alt="Capture d’écran 2021-01-20 à 09 22 37" src="https://user-images.githubusercontent.com/18577578/105147421-73c02800-5b01-11eb-9d4f-00d7bc880c82.png">

I understand how the submissions are sorted using the 'primary' column, but I don't know how they are sorted in mutlitasks phases. 

In the wiki [page](https://github.com/codalab/competitions-v2/wiki/Leaderboard-Functionality), the multitask case is not described.

And in this wiki's [multitask example](https://github.com/codalab/competitions-v2/wiki/Advanced-Tutorial), all scores are the same :)

If possible, it would be nice for the user to have the option to select the task used to sort the submissions (for instance using a click button directly on the leaderboard table). Maybe this functionality already exists but I couldn't find it.

What are your thoughts about this?

**Comment by Didayolo** [comment]
The primary column is used to rank participants. I've updated the documentation to make it clearer.

Computation columns can be used to average scores over several columns. We plan to implement other ranking functions such as "average rank", etc.

- #406
