### ISSUE TITLE
Change user functionality

### ISSUE THREAD

**Issue by NehzUx** [codalab/codabench#647]
Hi, the "change user" doesn't seem to work for now.  Whatever I type in the text box, it always shows "This field is required". Thanks for having a check.
![image](https://user-images.githubusercontent.com/12370705/109476645-1a5cf880-7ab2-11eb-849a-dbba127517a5.png)

**Comment by Didayolo** [comment]
On my side it is working. I close the issue as I supposed it is now working well.
