### ISSUE TITLE
Edit profile issue

### ISSUE THREAD

**Issue by NehzUx** [codalab/codabench#648]
When editing profile, even though I didn't fill the github url as showned below, when I click into the edit, it is filled by default the same url of my linkedin (as shown in the second fig)
![image](https://user-images.githubusercontent.com/12370705/109477538-1b425a00-7ab3-11eb-96a3-966332d041d2.png)

![image](https://user-images.githubusercontent.com/12370705/109488209-35366980-7ac0-11eb-870d-a230cd67da4f.png)

**Comment by Didayolo** [comment]
Merged.
