### ISSUE TITLE
Analytics display and download csv

### ISSUE THREAD

**Issue by NehzUx** [codalab/codabench#649]
Hi, the "Analytics" functionality doesn't display nicely the csv (as below). Besides, the "Download as CSV" doesn't work.
![image](https://user-images.githubusercontent.com/12370705/109488713-dfae8c80-7ac0-11eb-8a92-7295132a8512.png)

**Comment by Didayolo** [comment]
> Besides, the "Download as CSV" doesn't work.

@NehzUx What is the problem exactly? It just does nothing?

**Comment by Didayolo** [comment]
On my side it is not even displayed:

![error-codbn](https://user-images.githubusercontent.com/11784999/195095170-9490ddc5-9e60-476a-ae38-27691c21878e.png)

**Comment by Didayolo** [comment]
I close this issue but we keep track of it in the storage issue.
