### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by bbearce** [codalab/codabench#651]
I realize this may be an annoying and or disrespectful question but I honestly don't mean it to be. I really respect all the effort that has gone into CodaLab and work with v1.5 daily. 

I'd really like to migrate to v2 (codabench) and I've deployed every branch and while some have the UI up and running and lots of functionality working, there is always some issue. This is to be expected. 

Is there currently a working, stable version that I can use even if it's behind the latest code? The develop branch works best for me, but my submissions are getting connection errors to <domain>/api. I know codabench.org seems to be purring along great so is there a chance you could let me now which branch that is?

If you think my issue is by mistake (on my part) and that the system is pretty stable, may I start a dialog about my specific issues and potentially get them resolved?

PS: Keep up the good work!!! :)

**Comment by Didayolo** [comment]
@bbearce 

Hello Benjamin! Is this still relevant? Maybe we should try to setup a local CodaBench instance from scratch.

I think `develop` should be the main branch.

**Comment by bbearce** [comment]
This is pretty old. I remember the issue but this was before I knew CodaBench was being maintained. I think I should try to deploy locally again and get that going and make a more descriptive post. Should we delete for now?
