### ISSUE TITLE
LRI Migration Basic Testing

### ISSUE THREAD

**Issue by Tthomas63** [codalab/codabench#666]
Sever: https://codalabcomp-v2.lri.fr/

### Competition Management:
- [ ] Competition Upload Works
- [ ] Competition publishing/unpublishing works
- [ ] Competition secret key works
- [ ] Cannot view un-published competitions without secret key
- [ ] Competition creation form/wizard works

### Edit page
- [ ] Can change title
- [ ] Can modify a phase
- [ ] Can switch a dataset
- [ ] Can change and use a private queue

### Participate Management Page
- [ ] Can approve participant
- [ ] Can revoke participant

### Submission Management Page
- [ ] Can re-run submission
- [ ] Can force migrate submission (When applicable)

### Participation:
- [ ] Can register new user
- [ ] Can login existing LRI user
- [ ] Can apply to competition
- [ ] Can be approved and compete in a competition
- [ ] Can make submissions
- [ ] Can make submissions to existing LRI competitions
- [ ] Submission limits/execution time limits are respected

### Dataset Management:
- [ ] Can upload all the various types of datasets and use them
- [ ] Deleting competitions with references to datasets, should not delete datasets

**Comment by Didayolo** [comment]
Staling.
