### ISSUE TITLE
exec:"./manage.py": permission denied: unknown

### ISSUE THREAD

**Issue by duanningyu** [codalab/codabench#668]
docker-compose exec django ./manage.py migrate

OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec:"./manage.py": permission denied: unknown

I don't know how to deal with this error

**Comment by jlwang1996** [comment]
> docker-compose exec django ./manage.py migrate
> 
> OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec:"./manage.py": permission denied: unknown
> 
> I don't know how to deal with this error
You can run this code 
`chmod -R 777 ./`

**Comment by Didayolo** [comment]
`permission denied: unknown`

It is just a permission denied error. I guess you can run as `sudo`, or change the permissions of some files, or add your used to the docker group using `sudo usermod -aG docker $user`.
