### ISSUE TITLE
Feature Request: add upload remaining time indicator

### ISSUE THREAD

**Issue by JRMeyer** [codalab/codabench#672]
Hello!

*This is the same issue I posted on competitions v1.5, but I see it's the same for the new server at `codalab.lisn.upsaclay.fr`*

It would be helpful to add a progress bar or spinning wheel for bundle uploads, so the user/organizer knows things are progressing.

Using the public instance, uploading both competition bundles and submission bundles take longer than expected, and it's not obvious when it's a connection issue.

**Comment by Didayolo** [comment]
The is a progress bar in Codabench (codabench.org).

codalab.lisn.fr is running CodaLab Competitions.
