### ISSUE TITLE
Results changes not reflected in Leaderboard

### ISSUE THREAD

**Issue by JRMeyer** [codalab/codabench#673]
If you make a competition with a set of result metrics, and then change the ranking (importance) of the metrics via the YAML editor, the changes show up in the "Public Submissions" page, but not in the "Leaderboard/Results" page

e.g. I made a competition with "Word Error Rate" being the first metric for ranking, and then switched "Character Error Rate" to be first importance. I **can** see the update in the public submissions _and in the graph_ of the leaderboard itself, but not the text of the leaderboard.

**Comment by Didayolo** [comment]
Hi,

Thank you for reporting the issue. Could you please provide the link to the competition?

**Comment by Didayolo** [comment]
I close this issue as it is staling. Please re-open it if needed.
