### ISSUE TITLE
Display bug of www.codabench.org with Firefox

### ISSUE THREAD

**Issue by picaultj** [codalab/codabench#698]
On www.codabench.org, when a submission is done, it is impossible with Firefox to see the status of submissions, this is not correctly refreshed. I have the screen below:
![image](https://user-images.githubusercontent.com/56821431/168830172-23a3a3d0-7907-473b-9ed3-e61cb4257db0.png)

(same behaviour on Linux/Windows)

With another browser, for example MS Edge, the status of submissions appears correctly:
![image](https://user-images.githubusercontent.com/56821431/168830836-8cde01e1-f1c9-4347-bf3c-eaf4419d8ad9.png)

This is very blocking. Is it possible to fix this ASAP?

**Comment by Didayolo** [comment]
Hello,

Thank you for reporting this issue. It is linked to #682.

As I use Firefox I didn't realized that submissions are shown using another browser. We are investigating it.

**Comment by Didayolo** [comment]
Solved by:
- #716
