### ISSUE TITLE
The search is listing private competitions

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#705]
It seems that the search feature lists private competitions:

![search_issue1](https://user-images.githubusercontent.com/11784999/186430480-b14ad231-1970-43ca-babb-dc2df7254d7a.png)

When I click:

![search_issue2](https://user-images.githubusercontent.com/11784999/186430484-f9e7dd6f-5f37-4fcc-a3ca-49e0b95b541a.png)

**Comment by ihsaan-ullah** [comment]
Solved in [search_private_competitions](https://github.com/codalab/codabench/tree/search_private_competitions)
