### ISSUE TITLE
[Bug] compute_worker does not handle GPUs correctly

### ISSUE THREAD

**Issue by picaultj** [codalab/codabench#730]
Hello,

I've deployed on my own server a Codabench worker which has several GPUs. I want to use these GPUs in my benchmark, but unfortunately I see that **GPUs are not used.**

The GPU version of the worker is deployed locally, using the following command:
```
sudo nvidia-docker run \
    -e NVIDIA_VISIBLE_DEVICES=3 \
    -v /home/ubuntu/codabench/storage:/codabench \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /var/lib/nvidia-docker/nvidia-docker.sock:/var/lib/nvidia-docker/nvidia-docker.sock \
    -d \
    --env-file .env_gpu \
    --name codabench_gpu \
    --restart unless-stopped \
    --log-opt max-size=50m \
    --log-opt max-file=3 \
    codalab/competitions-v2-compute-worker:nvidia
```
The worker is working fine. I can see the available GPUs when I connect to the docker.

However my benchmark which is executed from this container does not have access to the GPUs.
From the codabench worker logs, I can see that the command used to launch my benchmark is:
```
nvidia-docker run --rm --name=701d6c6f-86b7-43f2-9650-5819099e6925 --security-opt=no-new-privileges -v /home/ubuntu/codabench/storage/tmpkh4wmblg/program:/app/program -v /home/ubuntu/codabench/storage/tmpkh4wmblg/output:/app/output -w /app/program -e PYTHONUNBUFFERED=1 -v /home/ubuntu/codabench/storage/tmpkh4wmblg/shared:/app/shared -v /home/ubuntu/codabench/storage/tmpkh4wmblg/input:/app/input jeromepicault/lips:0.1 python3 score.py --benchmark_output_dir /app/input/res/benchmark_output --score_dir /app/output/ --benchmark_name=Benchmark1 --benchmark_config=./GridBenchmark_conf.ini
```

If I launch a similar command from the codabench worker (in a bash), for example the following command, no GPU is visible:
```
root@12491ec542cf:/# nvidia-docker run -it jeromepicault/lips:0.1 python3 -c "import torch; print(torch.cuda.is_available())"
False
```

I think that a proper parameter is missing in line 504 of the file https://github.com/codalab/codabench/blob/develop/docker/compute_worker/compute_worker.py (varriable `docker_cmd`)

Indeed, if I change the nvidia-docker command above by adding the option **--gpus all** or **-e NVIDIA_VISIBLE_DEVICES=all**, I can have access to my GPUs...

```
root@12491ec542cf:/# nvidia-docker run -it --gpus all jeromepicault/lips:0.1 python3 -c "import torch; print(torch.cuda.is_available())"
True

root@12491ec542cf:/# nvidia-docker run -it -e NVIDIA_VISIBLE_DEVICES=all jeromepicault/lips:0.1 python3 -c "import torch; print(torch.cuda.is_available())"
True
```

**Please would it be possible to fix this problem as quickly as possible?
 (a fix in docker_cmd in compute_worker.py should be enough)**

Thanks a lot 
Jérôme

**Comment by Didayolo** [comment]
Thank you for reporting this bug. Can you confirm that your worker is receiving the jobs sent to your benchmark?

**Comment by picaultj** [comment]
Yes, the worker is receiving the jobs correctly, my python scripts are executed (using the CPU instead of GPU) and the results are reported back.
So, the problem is not in the whole process, but the fact that the docker on which my scripts are executed cannot see the GPUs of the worker.

**Comment by Didayolo** [comment]
What is the "Competition Docker Image" used by your benchmark?

You can see it in the editor. It is different than the docker used to run the worker: it is the docker in which the submission run. Some images provided by CodaLab include `codalab/codalab-legacy:py39` and `codalab/codalab-legacy:gpu`. As the tag suggests, some images are adapted to use GPUs and some others don't.

**Comment by picaultj** [comment]
solved
