### ISSUE TITLE
Display only the number of public competitions in the highlights

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#731]
Here is how the statistics look like in the home page:

<img width="987" alt="Capture d’écran 2022-10-18 à 14 43 04" src="https://user-images.githubusercontent.com/11784999/196432704-74bb657f-012a-4623-96de-076cd42c0639.png">

I think we should display only the public competitions. Another possibility is to at least remove the redundant "private competitions" information. Or even keep only "total competitions" because other statistics are total too. That is just too many numbers for unrelevant information (especially since most private competitions are just there for testing purpose).

Same the goes with [CodaLab highlights page](https://codalab.lisn.upsaclay.fr/highlights):

<img width="1224" alt="Capture d’écran 2022-10-18 à 14 43 15" src="https://user-images.githubusercontent.com/11784999/196432657-7e18d7ae-9194-42b6-a79e-d3f928bbc994.png">

**Comment by ihsaan-ullah** [comment]
Changed in branch [private_competitions](https://github.com/codalab/codabench/tree/private_competitions)
<img width="1091" alt="Screenshot 2023-04-25 at 2 37 18 PM" src="https://user-images.githubusercontent.com/13259262/234241807-6e713205-1a62-4184-8836-e9e2e0308852.png">
