### ISSUE TITLE
Manual Competition Creation Issue: Leaderboard not saved

### ISSUE THREAD

**Issue by bbearce** [codalab/codabench#733]
# Creating a Hello World competition copy as shown in screen shots

## Details
![image](https://user-images.githubusercontent.com/7649007/197397794-044e186c-0f94-4a8c-a395-4500bed76973.png)

## Participation
![image](https://user-images.githubusercontent.com/7649007/197397805-a70498b9-6ff5-4631-b4cc-8a62cc5bd35e.png)

## Pages
![image](https://user-images.githubusercontent.com/7649007/197397818-94b69f77-5716-4527-aa1e-eb1eb687d958.png)
![image](https://user-images.githubusercontent.com/7649007/197397828-f401a787-f549-4ae8-98b6-d2a9de8720b3.png)

## Phases
![image](https://user-images.githubusercontent.com/7649007/197397849-83e5aeba-3566-4722-9f22-9795b9157c8a.png)
![image](https://user-images.githubusercontent.com/7649007/197397839-456fe719-0804-47f7-9a93-7a2fe315e4bd.png)

## Leaderboard
![image](https://user-images.githubusercontent.com/7649007/197397856-9b102922-547d-46e4-a39f-1687bd35d1d5.png)
![image](https://user-images.githubusercontent.com/7649007/197397868-2f234992-3b60-4d8d-be0b-ea419370d1b4.png)

## Administrators
![image](https://user-images.githubusercontent.com/7649007/197397881-40b1f41f-7de0-411f-9805-b8b0bdbe84ea.png)

# Discussion

## Competition creation works:
![image](https://user-images.githubusercontent.com/7649007/197397932-57325914-b821-4b8d-9849-8563a294177d.png)
 
### Issue: Leaderboard not saved
![image](https://user-images.githubusercontent.com/7649007/197397959-c18c90ba-2bf5-4084-a079-077fe58621fa.png)
![image](https://user-images.githubusercontent.com/7649007/197397970-76f17c17-47a3-422f-98c6-c5621f67d35e.png)

**Comment by bbearce** [comment]
I think I should split this in two, with 733 being the leaderboard and a new issue yet to be created to be the queue issue.

**Comment by Didayolo** [comment]
Related issue:
- #300

**Comment by madclam** [comment]
Adding a phase does not work:
<img width="1122" alt="Screenshot 2023-05-05 at 11 03 23 AM" src="https://user-images.githubusercontent.com/7594063/236418817-ab5743a8-1327-4c0d-9b22-1d43c534706f.png">
