### ISSUE TITLE
Deletion of someone else' datasets

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#758]
In Codabench > Resources > Datasets >

I can see delete option for datasets which I don't know about. I am not trying to attempt the deletion but it seems critical.

Here is a screenshot:

<img width="1179" alt="Screenshot 2023-01-20 at 5 05 21 PM" src="https://user-images.githubusercontent.com/13259262/213691488-685204da-1428-4272-a3ed-1e819a1267f1.png">

**Comment by Didayolo** [comment]
Good catch. Maybe it is submissions made on competition you manage?

I think it is a problem with the listing. The actual deletion seems impossible:

<img width="538" alt="Capture d’écran 2023-01-20 à 16 23 51" src="https://user-images.githubusercontent.com/11784999/213735254-8793565b-e248-4ea4-8675-88ff40447ae1.png">

**Comment by ihsaan-ullah** [comment]
I have checked and it looks like I am not the admin of this competition. Yes, looks like listing issue.

**Comment by Didayolo** [comment]
I think datasets of other people should **not** be listed (except maybe if you are organizer of a benchmark that use the dataset?)

**Comment by ihsaan-ullah** [comment]
This happens when a dataset is public. Otherwise everything is ok.

Just one small problem: if a dataset is public and I am not the owner, I can still make it private. Should this be changed?

**Comment by Didayolo** [comment]
OK, so it is not really a bug. The problem is that, once we have many users and many public datasets, this will clutter the resources interface for everybody. I guess there should be a tab "public datasets" or something like this.

> if a dataset is public and I am not the owner, I can still make it private. Should this be changed?

When you try to make it private, it works? If so, yes, this should be changed.
