### ISSUE TITLE
Edit-Competition Phases Error

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#760]
I have uploaded a competition with 2 phases:

Phase 1 :
<img width="1159" alt="Screenshot 2023-01-24 at 4 52 30 PM" src="https://user-images.githubusercontent.com/13259262/214285004-08b65764-53bd-4819-b8e0-ab0489863c21.png">

Phase 2 :
 
<img width="1157" alt="Screenshot 2023-01-24 at 4 52 39 PM" src="https://user-images.githubusercontent.com/13259262/214285028-c0189dc4-f294-4697-b234-dd9e9e05b9c2.png">

Now when I click Edit my competition and go to Phases tab and click the arrows to show details, it gives me this error:
<img width="881" alt="Screenshot 2023-01-24 at 4 54 37 PM" src="https://user-images.githubusercontent.com/13259262/214285521-fec4b34c-f17d-4545-a30e-acafd6986252.png">

Which is wrong because Phase 1 starts before Phase 2

**Comment by Didayolo** [comment]
The arrows are supposed to give details or to change the order of the phase?

In my experience, this warning is annoying but does work.

**Comment by ihsaan-ullah** [comment]
The arrows are supposed to show dertails.

The error should not be there because the phases are actually ok.

For example check this competition: https://www.codabench.org/competitions/518/?secret_key=606dc7aa-256f-4b07-91b3-f91116c3dae4

Phase 1 : 24-01-2023 to 10-02-2023
<img width="405" alt="Screenshot 2023-01-30 at 4 46 03 PM" src="https://user-images.githubusercontent.com/13259262/215468704-f9f03e1e-d671-4458-9ee9-6407cb3b6421.png">

Phase 2: 20-02-2023 to 31-03-2023
<img width="415" alt="Screenshot 2023-01-30 at 4 46 08 PM" src="https://user-images.githubusercontent.com/13259262/215468734-b3ce7bef-c1cb-4dda-a8e5-1d6adaf8248e.png">

But when you go to edit>phases and click an arrow then this error is shown:
<img width="979" alt="Screenshot 2023-01-30 at 4 47 59 PM" src="https://user-images.githubusercontent.com/13259262/215468940-e6bf7a21-5be5-4330-bd37-c6cb305d1ad5.png">

**Comment by Didayolo** [comment]
The phase are OK, but for some reason Codabench thinks that Phase 2 is prior to Phase 1

**Comment by Didayolo** [comment]
I just tried, and I confirm that the arrow change the order of the phases

**Comment by ihsaan-ullah** [comment]
You are right. It is confusing for me. Maybe it is ok for other people

**Comment by Didayolo** [comment]
I agree that it is a bit confusing
