### ISSUE TITLE
The output are not downloadable if you have more than 1 collaborator

### ISSUE THREAD

**Issue by ktgiahieu** [codalab/codabench#767]
This issue only happen if I add more than 1 collaborator, then the submission got duplicated:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/42331617/217208819-46b6b7ab-7501-4381-8a19-0a7f0b1dfc3e.png">

And the "Output from scoring step" and "Output from prediction step" are not available anymore:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/42331617/217209003-4dba721d-3778-407c-afef-67d3a2709cef.png">

Can you take a look? Thank you.

**Comment by Didayolo** [comment]
I cannot reproduce the bug. Is it still present for you?

**Comment by ihsaan-ullah** [comment]
This is a nice bug. Repeated rows = number of admins added

In my case I have 3 admins:
<img width="731" alt="Screenshot 2023-05-05 at 8 54 29 PM" src="https://user-images.githubusercontent.com/13259262/236507284-b909d6c2-3b96-43e7-9ee0-39a3624c0d59.png">


Number of repeated submission = 3
<img width="502" alt="Screenshot 2023-05-05 at 8 55 02 PM" src="https://user-images.githubusercontent.com/13259262/236507401-290635ca-1d65-4f12-ad19-2c03724f7e25.png">

**Comment by Didayolo** [comment]
@ihsaan-ullah Did #846 also solve this issue?
