### ISSUE TITLE
Improve installation

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#771]
Several issues are encountered when following this installation guide: https://github.com/codalab/codabench/wiki/Codabench-Installation

### 1. Email confirmation

- [x] Improve the documentation.

When deploying a local instance, as the email server is not configured by default, it is tricky to validate user accounts.

One work-around is to:
1. Find the confirmation link in the Django logs using `docker-compose logs -f django`
2. Replace `example.com` by `localhost` to open it on the browser.

_(Another work-around is to manage the account by hand in the Django container.)_

### 2. Problem with storage

- [x] We fixed MinIO buckets creation (#783)
- [x] We need to fix the policy setup to have directly the "read/write" policy on the public bucket (to fix the issue with logos not displayed). The fix: #786

https://github.com/codalab/codabench/blob/6bf601aa7f2bbc4d1ec6de8bf5c24414b3744af0/docker-compose.yml#L76

### 3. Step "run the following commands"

_Maybe we just let it as it is._
At the end of the guide, we manually create the database and collect the static resources.
Can't this be handled directly by the `docker-compose up -d` command?

### 4. Endpoint URL

- [x] Document this troubleshooting.

Some people (@bbearce) have to manually change the endpoint URL to have it working:

1. `docker-compose logs -f minio`
2. Grab first of these:
```
minio_1           | Browser Access:
minio_1           |    http://172.27.0.5:9000  http://127.0.0.1:9000
```
3. Set `AWS_S3_ENDPOINT_URL=http://172.27.0.5:9000`

**Comment by acletournel** [comment]
I have modified the wiki page with a few more hints for .env file, minio bucket policy configuration (the reason for logos not being dispayed) and the sequence of the different installation steps. @Didayolo @ihsaan-ullah : please, can you try again your local installation settings following these instructions ?

**Comment by Didayolo** [comment]
@acletournel 

I see you have edited the following page: https://github.com/codalab/codabench/wiki/How-to-deploy-Codabench-on-your-server

While I was working on improving the basic installation guide: https://github.com/codalab/codabench/wiki/Codabench-Installation

I guess some information should be merged in order to have a complete setup guide. I'll have a look at it.

**Comment by acletournel** [comment]
While working on local codabench instances, I found out that my flower docker container is unstable and continuously restarts:
I am using the current codabench/develop branch
```CONTAINER ID   IMAGE                     COMMAND  CREATED            STATUS                                        PORTS                  NAMES
f995e89fc0d7   codabench_flower    "flower"     31 minutes ago   Restarting (1) 40 seconds ago                                codabench_flower_1```

dockers logs show: ImportError: 
```cannot import name 'Command' from 'celery.bin.base' (/usr/local/lib/python3.11/site-packages/celery/bin/base.py)```
which seems to be incompatibility with a new celery 5 version: https://github.com/mher/flower/issues/1031

Flower is 0.9.3 according to Dockerfile.flower and celery is 4.2.1 according to requirements.txt ?

Codabench-test doesn't have the problem, but runs a flower dockerhub image mehr/flower and not a local built one.
Codabench-prod doesn't have the problem and run a local built image competitions-v2_flower.

**Comment by Didayolo** [comment]
@bbearce @acletournel 

Some news. I realized that I'm able to access MinIO from `http://localhost:9000` but not from `http://minio:9000`.

However, as you can see in the "create buckets" logs, Codabench tries to access it through `http://minio:9000`:

```python
codabench-createbuckets-1   | + /usr/bin/mc config host add minio_docker http://minio:9000 testkey testsecret
codabench-createbuckets-1   | mc: <ERROR> Unable to initialize new alias from the provided credentials. Server not initialized, please try again.
```

This is not related to the `AWS_S3_ENDPOINT_URL` defined in `.env` file. It is actually hard coded in `docker-compose.yml` file:

https://github.com/codalab/codabench/blob/46f68ee91511a79d10fab817ca1164e35cd32d58/docker-compose.yml#L73

I guess there are two solutions:
- Edit the `docker-compose.yml` config
- Map `minio` to `localhost` in my local config

**Comment by Didayolo** [comment]
I think I found a fix!

**Comment by Didayolo** [comment]
Update:

- We fixed MinIO buckets creation

- We need to fix the policy to have directly the "read/write" policy on the public bucket (to fix the issue with logos not displayed)

https://github.com/codalab/codabench/blob/6bf601aa7f2bbc4d1ec6de8bf5c24414b3744af0/docker-compose.yml#L76

**Comment by Didayolo** [comment]
I've added more information on the part "advanced configuration" of the guide:

https://github.com/codalab/codabench/wiki/Codabench-Installation
