### ISSUE TITLE
New user sign in after verification results in Server Error 500

### ISSUE THREAD

**Issue by saravanabalagi** [codalab/codabench#773]
I signed up, activated the account using the email link, then tried to sign in:

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/8567893/219049022-faf09c20-37de-472b-95a5-f2755ccc622e.png">

If I reload the page entirely (the 500 error goes away) and sign in again, it says wrong username/password combination (I autofill username and password using my password manager, so no mistakes there). What's more interesting is that it allows me to sign up again using the same username, even though the account should exist after activation.

NB: I was previously able to sign up without any trouble using my personal email address.

**Comment by saravanabalagi** [comment]
I can confirm that this does not happen when the username does not contain any special chars as mentioned in #756. I was able to successfully sign up with the same email but with a different username which does not have any special chars.

**Comment by saravanabalagi** [comment]
I was able to sign in and do stuff as usual. But as soon as I open a secret link to an unpublished competition, CodaBench logs me out and **deletes the account**. I was not able to sign in again using the same username/password, and the system allowed me to sign up as if the account never existed.

Possible connections with account deletion mentioned in #751?

**Comment by im-spiETH** [comment]
> I can confirm that this does not happen when the username does not contain any special chars as mentioned in #756. I was able to successfully sign up with the same email but with a different username which does not have any special chars.

**Comment by Didayolo** [comment]
This problem is solved now.
