### ISSUE TITLE
Submissions should be allowed only within start and end dates

### ISSUE THREAD

**Issue by saravanabalagi** [codalab/codabench#774]
I created a competition with 2 phases both of which are starting in the future.

What's happening: 
- CodaBench allows submitting to both phases
- Interestingly, Test phase (with later start date) is highlighted/selected by default when the page reloads.

Expected: 
- CodaBench does not allow the user to submit until the phase begins. 
- Submissions are allowed only between start and end dates.
- The phase with the earliest phase is highlighted/selected by default.

Screencast:

https://user-images.githubusercontent.com/8567893/219051411-63835b02-c93a-4dde-af70-02c1bdaaecd6.mov

**Comment by saravanabalagi** [comment]
@Didayolo Do you know why this happens, if yes, can you point me where I should look? I'm happy to contribute. 

Also, is there any estimate of effort/time required for the fix? I understand that it could take time to fix the issues, but is this production ready at the moment, or should I fallback to CodaLab?

**Comment by saravanabalagi** [comment]
@Didayolo no problem, thanks for the info. I will try to look into into it when I get time :)

**Comment by Didayolo** [comment]
I close this issue as it is solved by this PR: #835
