### ISSUE TITLE
Queue creation - Invalid time shown

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#795]
I have created a queue called "Test". The created time shown is -5 seconds

<img width="1140" alt="Screenshot 2023-04-04 at 3 00 19 PM" src="https://user-images.githubusercontent.com/13259262/229757985-2e76e298-6dc6-47e3-b93d-2b542a0b4d17.png">

**Comment by Didayolo** [comment]
That is crazy 🤪

**Comment by ihsaan-ullah** [comment]
Unable to reproduce this bug. Everything seems to be working fine

<img width="1157" alt="Screenshot 2023-04-25 at 2 18 49 PM" src="https://user-images.githubusercontent.com/13259262/234232476-d00af87a-b14c-4896-bda7-ceb1fa079ee4.png">

**Comment by Didayolo** [comment]
OK, I think we can consider this a non-issue. Re-open the issue if you disagree.
