### ISSUE TITLE
Organization (team) management

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#805]
# General thoughts

Organization is basically the team system of Codabench. The feature is a bit incomplete right now.

- We happens when we add someone to an organization?
- Do we have option to limit the submission per team? To view only teams in the leaderboard? 
- Do we identify teams clearly on the leaderboard?

Related idea: being able to differentiate tracks, e.g. "student tracks" (https://petlab.officialstatistics.org/), etc.

# Bugs

- [x]  1-- When submitting as a team, the display in the leaderboard is broken. It shows this:
Solved by: #1053 

<img width="1197" alt="Capture d’écran 2023-06-22 à 15 23 55" src="https://github.com/codalab/codabench/assets/11784999/24b93278-34cd-4fc5-8b0e-e03b23cae99a">
 
Instead of this (here the submission is made as a participant, not a team):

<img width="1179" alt="Capture d’écran 2023-06-22 à 15 24 07" src="https://github.com/codalab/codabench/assets/11784999/dfbb0057-6b2d-4095-8159-1de915fb60e7">

- [x] 2-- We only see organization we created in the "Submit as..." menu (when making a submission):
Solved by: #1056 

<img width="472" alt="Capture d’écran 2023-06-22 à 16 00 59" src="https://github.com/codalab/codabench/assets/11784999/66814add-bdef-480e-9600-dfcf0d934b52">

- [x] 3-- After inviting a user, the `Delete` button becomes not clickable:
Solved by: #1057

<img width="856" alt="Capture d’écran 2023-06-20 à 13 57 56" src="https://github.com/codalab/codabench/assets/11784999/79cf477b-5156-4d38-9291-a9e2b86571ad">

<img width="1197" alt="Capture d’écran 2023-06-20 à 13 58 07" src="https://github.com/codalab/codabench/assets/11784999/ada65e23-8b06-4118-9673-188c7baa5301">

# Features

- [x] Delete organization #938
Solved by #959

- [x] Submit as organizer made clear 
Solved by: #976

- [ ] Being able to remove submissions made as an organization. Apprently, tthis field should be updated: 
https://github.com/codalab/codabench/blob/e9f7ef41ab331c95027e2774a977eb951b3b45c9/src/apps/competitions/models.py#L426

- [x] Add other members of the team. They should receive an email and/or a notification on the platform.

**Comment by ihsaan-ullah** [comment]
> Being able to remove submissions made as an organization. Apprently, tthis field should be updated:

@Didayolo Can you please explain this point:

**Comment by Didayolo** [comment]
@ihsaan-ullah I don't really remember. I guess submissions made as an organization can't be removed? We should investigate this.
