### ISSUE TITLE
Task deletion

### ISSUE THREAD

**Issue by lbeziaud** [codalab/codabench#810]
Hi,

I am testing out the platform and creating/deleting benchmarks. This results in a lot of unassigned tasks which I have to delete one by one.  To avoid cluttering the platform an idea could be to allow users to automatically delete tasks when deleting a benchmark. Or adding a "delete unused tasks" button on the tasks tab. What do you think? I'll try to propose a PR for the latter.

**Comment by Didayolo** [comment]
Hi @lbeziaud, yes this is a great remark. It could take the form of a yes/no box when deleting a benchmark saying something like "Do you want to delete all tasks associated only to this benchmark?".

Having a button to delete all orphan tasks would be a great addition too.

**Comment by Didayolo** [comment]
I close this issue to keep track of this in the "Storage and clean up" issue.
