### ISSUE TITLE
shell_plus:  no module named 'blessings'

### ISSUE THREAD

**Issue by lbeziaud** [codalab/codabench#814]
Hi,

The wiki mention using shell_plus to [give superuser privileges to an user](https://github.com/codalab/codabench/wiki/Administrator-procedures#give-superuser-privileges-to-an-user) however calling `python manage.py shell_plus` fails with: `ModuleNotFoundError: No module named 'blessings'`.

Installing blessings with pip inside the container fixes the issue. A simpler option is calling shell_plus with `--plain`. A third option is to use the default shell:
```
python manage.py shell
>>> from profiles.models import User
>>> u = User.objects.get(username=<USERNAME>) # can also use email
```

These last two fixes only require modifying the wiki :)

**Comment by lbeziaud** [comment]
This might be related to https://github.com/codalab/codabench/issues/516

**Comment by Didayolo** [comment]
Good catch, thank you for the report. I have added the `--plain` flag in the Wiki.
