### ISSUE TITLE
Error 500 on competitions with keys

### ISSUE THREAD

**Issue by madclam** [codalab/codabench#842]
When trying to reach a competition with key e.g.
https://www.codabench.org/competitions/787/?secret_key=f21e43be-c0a4-4fa3-862e-f3ac58915257
we get an error 500 if we are not already logged in.
It should ask us for logging in and redirect to the right page.

**Comment by Didayolo** [comment]
On my side I get a 404 error using this URL

**Comment by Didayolo** [comment]
Fixed by #845 anyway
