### ISSUE TITLE
500 error when open a public competition while NOT loggedin

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#854]
I am not loggedin to https://www.codabench.org/ and when I click any of the public competitions:
<img width="1241" alt="Screenshot 2023-05-09 at 7 06 47 PM" src="https://github.com/codalab/codabench/assets/13259262/09fd6c0f-9173-4c06-be6e-0da5ab6fe67f">

I get 500 error
<img width="418" alt="Screenshot 2023-05-09 at 7 06 51 PM" src="https://github.com/codalab/codabench/assets/13259262/3f240bfd-ee7f-4245-a247-0647dd8cf453">

Unable to reproduce this locally (I think this is fixed in one of the PR but not sure)

**Comment by Didayolo** [comment]
Maybe it is due to a recent change.

**Comment by Didayolo** [comment]
Fixed by the deployment #849
