### ISSUE TITLE
Private benchmark not loading well for collaborators 

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#858]
When you are collaborator of a private benchmark, and access it through its public URL, it is not working:

<img width="1314" alt="Capture d’écran 2023-05-10 à 02 43 55" src="https://github.com/codalab/codabench/assets/11784999/c0b254a7-d0f4-46ea-99fb-ffb2344a0046">

**Comment by ihsaan-ullah** [comment]
Are you clicking `Edit` for the competition where you are collaborator?

**Comment by EngineeringCompetition** [comment]
I have the same problem. Everyone except for the creator of the competition cannot see the competition anymore.
Has anyone tried to resolve the problem by making the competition public?

**Comment by EngineeringCompetition** [comment]
> I have the same problem. Everyone except for the creator of the competition cannot see the competition anymore. Has anyone tried to resolve the problem by making the competition public?

It's working again. Whoever fixed it. Thank you so much.
