### ISSUE TITLE
Unlimited dumps creation

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#862]
I can create unlimited dumps. Should there be 

1. option to delete old dumps
2. restrict user to create certain amount of dumps

<img width="758" alt="Screenshot 2023-05-11 at 4 26 35 PM" src="https://github.com/codalab/codabench/assets/13259262/64ed9bd0-d568-47f5-8103-f9fa04f037e8">

**Comment by Didayolo** [comment]
Nice catch. I close the issue to keep track of it directly from #713
