### ISSUE TITLE
leak users

### ISSUE THREAD

**Issue by lbeziaud** [codalab/codabench#885]
Hi,

The Django REST framework leaks the list of users (with emails) through the "collaborators" selector of the HTML competition submission form (bottom of the page https://www.codabench.org/api/competitions/).

![Screenshot from 2023-05-22 14-52-30](https://github.com/codalab/codabench/assets/4895292/ce68cbb8-4640-46ff-a37b-97111cf75bc3)

Edit: Seems it only works when logged in 🙌. The extraction is possible through the GUI "Add collaborator" auto completion feature, but giving out the list like that might not be desired.

**Comment by Didayolo** [comment]
Good catch, thank you for reporting this problem.

When using the editor through the UI to add collaborators, the behavior is as excepted:

Not able to see the email when **not** logged in as an administrator of the platform:

<img width="419" alt="Capture d’écran 2023-05-22 à 17 05 59" src="https://github.com/codalab/codabench/assets/11784999/fed829c7-fb79-455f-b212-688e2e71421b">

Able to see the email when logged in as an administrator of the platform:

<img width="514" alt="Capture d’écran 2023-05-22 à 17 06 38" src="https://github.com/codalab/codabench/assets/11784999/46d0039f-c2c1-47d7-80f0-12e308f7bd2e">

It seems that, using the REST API, the emails are always given? That is an important leakage that we need to fix.

**Comment by lbeziaud** [comment]
Emails are indeed given although I'm no admin. I reported the issue while looking at `/competitions` but the email issue is more obvious by looking at https://www.codabench.org/api/participants/. Seems the API is not following the email access rights you describe for the UI (visible only when admin). I'm not familiar with Django REST framework but I guess 
the issue is with [CompetitionParticipantViewSet](https://github.com/codalab/codabench/blob/develop/src/apps/api/views/competitions.py#L558) or [CompetitionParticipantSerializer](https://github.com/codalab/codabench/blob/develop/src/apps/api/serializers/competitions.py#L258).

**Comment by Didayolo** [comment]
I close this issue to keep track of this directly in the PR.

**Comment by Didayolo** [comment]
I re-open this issue because #929 got reverted. Indeed, this change is breaking the organizer interface used to approve / revoke participants (the buttons simply stops working).

We therefore need to:

- [ ] Fix the change to merge it again
- [ ] Check that is does not break anything
- [ ] Add tests for the participants tab #996

**Comment by Didayolo** [comment]
Related:  #1008

**Comment by ihsaan-ullah** [comment]
@Didayolo this issue is done
