### ISSUE TITLE
No error logs when the compute worker crashes

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#902]
# TODOs:

- [ ] Show logs when compute worker crashes because of invalid docker image
- [ ] show logs when compute worker crashes because of time limit

# Reproduce error:

- execution time limit exceeds 
- wrong docker image (does not exist)

***
When the compute worker crashes, the submission is stuck in `Running` state and no logs are forwarded to the UI.

---

When the worker hit the ExecutionTimeLimitExceeded error (see below), the program simply stops and no logs are returned to the platform for the users.

<add screenshot>

To reproduce, edit a benchmark to put a very low execution time limit and make a submission.

```
Traceback (most recent call last):
  File "/compute_worker.py", line 687, in start
    loop.run_until_complete(gathered_tasks)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "/compute_worker.py", line 158, in alarm_handler
    raise ExecutionTimeLimitExceeded
compute_worker.ExecutionTimeLimitExceeded
```

**Comment by Didayolo** [comment]
A typical example of this: if you select a Docker image that does not exist, the submission will fail with no logs.

**Comment by ihsaan-ullah** [comment]
Do you know the reason for this error:

<img width="1130" alt="Screenshot 2023-09-03 at 5 39 30 PM" src="https://github.com/codalab/codabench/assets/13259262/36c230d8-a54a-4134-88cf-fff07c9ab227">


This is the exact link:
http://docker.for.mac.localhost:9000/private/submission_details/2023-09-03-1693744274/393db4c35cfe/prediction_ingestion_stderr.txt?AWSAccessKeyId=testkey&Signature=G8b5Oom2mb%2FFJMfF9sXstMPyCWc%3D&content-type=application%2Fzip&Expires=1693830674


I can see the file in minio
<img width="1173" alt="Screenshot 2023-09-03 at 5 40 26 PM" src="https://github.com/codalab/codabench/assets/13259262/90101d04-d24b-4290-84c9-170c68656fb6">

**Comment by Didayolo** [comment]
I don't know. It is linked to this issue?

**Comment by ihsaan-ullah** [comment]
> I don't know. It is linked to this issue?

Yes, I am trying to solve the issue but when I want to write to this file, I get this error
