### ISSUE TITLE
Competition html/markdown pages

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#923]
It seems the documentation pages in these 2 competitions are broken

https://www.codabench.org/competitions/476/

https://www.codabench.org/competitions/562/

**Comment by Didayolo** [comment]
I guess it is linked to this problem and recent changes:

- #879

For the Cross-Domain MetaDL challenge, I think I converted the pages to Markdown, but some special tags may break it. You can see that the tab "Data" is working well.

**Comment by ihsaan-ullah** [comment]
@Didayolo i think this is fixed by #1090
