### ISSUE TITLE
AutoML Cup phase 1 not visible

### ISSUE THREAD

**Issue by mekaneeky** [codalab/codabench#941]
Attempting to participate in the AutoML Cup. However, loading this URL: https://www.codabench.org/competitions/984/. Results in an empty page on 2 browsers.

**Comment by Didayolo** [comment]
When I click on the link from your issue, I am able to see the AutoML Cup. Can you provide a screenshot of how it looks on your side? What are the browsers you tried? Do other participants report the same problem?

**Comment by ihsaan-ullah** [comment]
competition link is working
<img width="1608" alt="Screenshot 2023-06-14 at 12 19 55 PM" src="https://github.com/codalab/codabench/assets/13259262/da53955d-75e4-4492-bcf5-f30a4fe4aa62">

**Comment by mekaneeky** [comment]
Thanks, I figured I could get it to work with a VPN only. Checked again today and automagically works without one, thanks !
