### ISSUE TITLE
Ideas to engage the community more

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#955]
Following #787:

- we could embed the last topics from the Google-groups on the home page near the news.
- we could link this page as a "hall of contributors": https://github.com/codalab/codabench/graphs/contributors
- we could have a "hall of papers" based on Google scholar papers citing CodaLab / Codabench
- [x] we could add the sponsors at the end of the front page (#1264)
- there is also a Github feature for sponsoring (#901)
- show that v1 bundle are compatible with Codabench, so no big entry barrier,  the platform is fast and smooth

**Comment by Didayolo** [comment]
Sponsors on the home page can be a good incentive for support (and make the platform looks serious)

<img width="1176" alt="Capture d’écran 2023-06-15 à 16 19 28" src="https://github.com/codalab/codabench/assets/11784999/e1ae30fa-8158-4800-a7b1-e482ea48ed36">

**Comment by ihsaan-ullah** [comment]
We can use https://pypi.org/project/scholarly/ for `hall of papers`

**Comment by ihsaan-ullah** [comment]
Shifted to discussions: #1332
