### ISSUE TITLE
Submit as Organization

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#964]
<img width="464" alt="Screenshot 2023-06-20 at 3 44 49 AM" src="https://github.com/codalab/codabench/assets/13259262/129baab2-b500-4550-8448-63131f6834f0">

When you submit a submission, you always see `submit as : Yourself. This is confusing when you don't have any organizaiton.

This should be made clear with some text and a possible link to add an organization.

**Comment by Didayolo** [comment]
Yeah, maybe if you have no organization and click here, its should scrolls with a `Add organization` item which redirect to organization creation.
