### ISSUE TITLE
Codabench Test

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#969]
On https://codabench-test.lri.fr/

1. Competition upload is stuck here
<img width="606" alt="Screenshot 2023-06-20 at 6 32 31 PM" src="https://github.com/codalab/codabench/assets/13259262/8d0244b9-2d64-4cfd-a01d-d91f26e7803d">

2. Did not receive email for account verification after signup 
username: ihsan

**Comment by dtuantran** [comment]
It's back to normal now. This issue is possibly due to a network incident from the Openstack Lab yesterday.

**Comment by ihsaan-ullah** [comment]
@dtuantran I cannot access my account: username `ihsan` because I did not receive an email after signup. Can you please delete this account so that I can create it again
