### ISSUE TITLE
Export CSV from ../analytics doesn't work

### ISSUE THREAD

**Issue by dtuantran** [codalab/codabench#980]
![image](https://github.com/codalab/codabench/assets/7440668/7959c16c-dc54-4b5b-ad24-f9156623fab9)

We can't download the csv file after clicking the button and it shows "Failed server problem".

# Todo:

- [x] fix download functionality in analytics

**Comment by Didayolo** [comment]
I think this is reported here:
- #713
- #649

**Comment by Didayolo** [comment]
We can keep track of this in the PR
